title: DRAGON Analyzer
description: DRAGON analysis codes
show_downloads: true
git_branch: master
logo_url: http://dragon.triumf.ca/images/Dragon-Symbol.jpg
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: true
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
