DRAGON Analyzer: dragon::Mcp Class Reference
dragon::Mcp Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Mcp ()
Constructor, initialize data.
void reset ()
Reset all data to VME::none.
void read_data (const vme::V785 adcs[], const vme::V1190 &tdc)
Read midas event data.
void calculate ()
Calibrate ADC/TDC signals, calculate x and y positions.
Public Attributes
double anode [MAX_CHANNELS]
Anode signals.
double tcal [NUM_DETECTORS]
TDC signals.
double esum
Sum of anode signals.
double tac
TAC signal (MCP_TOF).
double x
x-position
double y
y-position
Mcp::Variables variables
Variables instance.
Static Public Attributes
static const int MAX_CHANNELS = 4
Number of anodes on MCP0.
static const int NUM_DETECTORS = 2
Number of separate mcp detctors.
Detailed Description
Micro channel plates
Definition at line 257 of file Dragon.hxx.
Constructor & Destructor Documentation
Mcp()
dragon::Mcp::Mcp ()
Constructor, initialize data.
::
Definition at line 490 of file Dragon.cxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::Mcp::calculate ()
Calibrate ADC/TDC signals, calculate x and y positions.
Calibrates anode, tcal, and tac values; calculates x- and y-positions.
Note
Position calculation algorithm taken from the MSc thesis of Michael Lamey, Simon Fraser University, 2001, p. 25; available online at dragon.triumf.ca/docs/Lamey_thesis.pdf
Definition at line 518 of file Dragon.cxx.
References dragon::utils::calculate_sum(), dragon::utils::is_valid_all(), and dragon::utils::linear_calibrate().
 {
   /*!
    * Calibrates anode, tcal, and tac values; calculates x- and
    * y-positions.
    *
    * \note Position calculation algorithm taken from the MSc thesis of
    * Michael Lamey, Simon Fraser University, 2001, p. 25; available online at
    * <a href="http://dragon.triumf.ca/docs/Lamey_thesis.pdf">
    * dragon.triumf.ca/docs/Lamey_thesis.pdf</a>
    */
   dutils::linear_calibrate(anode, MAX_CHANNELS, variables.adc);
   dutils::linear_calibrate(tcal, NUM_DETECTORS, variables.tdc);
   dutils::linear_calibrate(tac, variables.tac_adc);
   dutils::calculate_sum(anode, anode + MAX_CHANNELS);
   // Position calculation if we have all valid anode signals
   if(dutils::is_valid_all(anode, MAX_CHANNELS)) {
     const double Lhalf = 25.;  // half the length of a single side of the MCP (50/2 [mm])
     double sum = 0;
     for(int i=0; i< MAX_CHANNELS; ++i) sum += anode[i];
     if(sum != 0) {
       x = Lhalf * ( (anode[1] + anode[2]) - (anode[0] + anode[3]) ) / sum;
       y = Lhalf * ( (anode[0] + anode[1]) - (anode[2] + anode[3]) ) / sum;
     }
   }
 }
read_data()
void dragon::Mcp::read_data (const vme::V785 adcs[], const vme::V1190 & tdc)
Read midas event data.
Copies ADC and TDC data into anode, tcal, and tac parameters.
Delegates work to dutils::channel_map()
Parameters
[in] adcs Array of vme::V785 adc modules from which data can be taken
[in] tdc vme::V1190 tdc module from which data can be read
Definition at line 504 of file Dragon.cxx.
References dragon::utils::channel_map().
 {
   /*!
    * Copies ADC and TDC data into anode, tcal, and tac parameters.
    *
    * Delegates work to dutils::channel_map()
    * \param [in] adcs Array of vme::V785 adc modules from which data can be taken
    * \param [in] tdc vme::V1190 tdc module from which data can be read
    */
   dutils::channel_map(anode, MAX_CHANNELS, variables.adc.channel, variables.adc.module, adcs);
   dutils::channel_map(tcal, NUM_DETECTORS, variables.tdc.channel, tdc);
   dutils::channel_map(tac, variables.tac_adc.channel, variables.tac_adc.module, adcs);
 }
reset()
void dragon::Mcp::reset ()
Reset all data to VME::none.
::
Definition at line 496 of file Dragon.cxx.
References dragon::utils::reset_array(), and dragon::utils::reset_data().
 {
   /// ::
   dutils::reset_data(esum, tac, x, y);
   dutils::reset_array(MAX_CHANNELS, anode);
   dutils::reset_array(NUM_DETECTORS, tcal);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx