DRAGON Analyzer: vme::V1190 Class Reference
vme::V1190 Class Reference
#include <Vme.hxx>
Classes
struct Channel
Encloses measurement data for a single v1190 TDC channel.
class Fifo
Holds measurement information in a first-in-first-out structure.
Public Types
enum HitType { LEADING, TRAILING }
Hit types (leading or trailing edge)
Public Member Functions
V1190 ()
Calls reset()
bool unpack (const midas::Event &event, const char *bankName, bool reportMissing=false)
Unpack TDC data from a MIDAS event.
void reset ()
Reset data fields to default values.
int32_t get_data (int16_t ch) const
Get a data value, with bounds checking.
int32_t get_leading (int16_t ch, int16_t hit=0) const
Find leading edge hit.
int32_t get_trailing (int16_t ch, int16_t hit=0) const
Find trailing edge hit.
Public Attributes
int16_t n_ch
Number of channels present in an event.
int32_t count
Event counter.
int16_t word_count
Word count.
int16_t trailer_word_count
Global trailer word count.
int16_t event_id
Event id.
int16_t bunch_id
Bunch id.
int16_t status
Module status.
int16_t type
Measurement type.
int32_t extended_trigger
Extended trigger time.
int16_t error
Error flag.
int fMessagePeriod
Error message printing period.
Channel channel [MAX_CHANNELS]
Array of all measurement channels (not transient)
Fifo fifo0
Leading edge measurements.
Fifo fifo1
Trailing edge measurements.
Static Public Attributes
static const uint16_t TDC_HEADER = 0x1
Header buffer code.
static const uint16_t TDC_MEASUREMENT = 0x0
Measurement (data) buffer code.
static const uint16_t TDC_ERROR = 0x4
Error buffer code.
static const uint16_t TDC_TRAILER = 0x3
Trailer buffer code.
static const uint16_t GLOBAL_HEADER = 0x8
Global header buffer code.
static const uint16_t GLOBAL_TRAILER = 0x10
Global trailer buffer code.
static const uint16_t EXTENDED_TRIGGER_TIME = 0x11
Extended trigger time buffer code.
static const uint16_t MAX_CHANNELS = 64
Number of data channels available in the TDC.
Private Member Functions
bool unpack_buffer (const uint32_t *const pbuffer, const char *bankName)
Unpack a generic V1190 buffer.
void unpack_footer_buffer (const uint32_t *const pbuffer, const char *bankName)
Unpack footer buffer.
void handle_error_buffer (const uint32_t *const pbuffer, const char *bankName)
Deals with V1190 error codes.
bool unpack_data_buffer (const uint32_t *const pbuffer)
Unpack event data buffer.
Detailed Description
CAEN V1190 TDC module
Definition at line 76 of file Vme.hxx.
Class Documentation
struct vme::V1190::Channel
Encloses measurement data for a single v1190 TDC channel.
Definition at line 150 of file Vme.hxx.
Class Members
vector< int32_t > fLeading Temporary storage of leading edge hits.
vector< int32_t > fTrailing Temporary storage of trailing edge hits.
int32_t nleading Number of leading-edge hits in the current event.
int32_t ntrailing Number of trailing-edge hits in the current event.
Member Function Documentation
int32_t vme::V1190::get_data (int16_t ch) const
Get a data value, with bounds checking.
Parameters
ch Channel number to get data from
Returns
the leading edge time value of the first hit on channel ch. If ch is out of bounds, prints a warning message and returns dragon::DR_NO_DATA.
Definition at line 162 of file Vme.cxx.
References dragon::NoData< T >::value().
 {
   /*!
    * \param ch Channel number to get data from
    * \returns the leading edge time value of the first hit on
    * channel \e ch. If \e ch is out of bounds, prints a warning
    * message and returns dragon::DR_NO_DATA.
    */
   if (ch >= 0 && ch < MAX_CHANNELS) {
     if(!channel[ch].fLeading.empty())
       return channel[ch].fLeading[0];
     else
       return dragon::NoData<int32_t>::value();
   }
   else {
     dutils::Warning("V1190::get_data")
       << "Channel number " << ch << " out of bounds (valid range: [0, "
       << MAX_CHANNELS -1 << "]\n";
     return dragon::NoData<int32_t>::value();
   }
 }
void vme::V1190::handle_error_buffer (const uint32_t *const pbuffer, const char * bankName) private
Deals with V1190 error codes.
Error encoding is handled with a bitmask, bits 0 - 13. Here we print the appropriate messages as given in the V1190 manual and set the error flag to the corresponding code.
Parameters
[in] pbuffer Pointer to the error buffer longword
[in] bankName Name of the MIDAS bank containing the data in question
Definition at line 249 of file Vme.cxx.
References dragon::utils::gDelayedMessageFactory, dragon::utils::DelayedMessageFactory::Get(), dragon::utils::ADelayedMessagePrinter::Incr(), and dragon::utils::DelayedMessageFactory::Register().
 {
   /*!
    * Error encoding is handled with a bitmask, bits 0 - 13. Here we print the
    * appropriate messages as given in the V1190 manual and set the `error` flag
    * to the corresponding code.
    * \param [in] pbuffer Pointer to the error buffer longword
    * \param [in] bankName Name of the MIDAS bank containing the data in question
    */
   std::string errors[15] = {
     "Hit lost in group 0 from read-out FIFO overflow.",
     "Hit lost in group 0 from L1 buffer overflow",
     "Hit error have been detected in group 0.",
     "Hit lost in group 1 from read-out FIFO overflow.",
     "Hit lost in group 1 from L1 buffer overflow",
     "Hit error have been detected in group 1.",
     "Hit data lost in group 2 from read-out FIFO overflow.",
     "Hit lost in group 2 from L1 buffer overflow",
     "Hit error have been detected in group 2.",
     "Hit lost in group 3 from read-out FIFO overflow.",
     "Hit lost in group 3 from L1 buffer overflow",
     "Hit error have been detected in group 3.",
     "Hits rejected because of programmed event size limit",
     "Event lost (trigger FIFO overflow).",
     "Internal fatal chip error has been detected."
   };
   for(int i=0; i< 14; ++i) {
     if((*pbuffer >> i) & READ1) {
       error = i; // set error code
       dutils::ADelayedMessagePrinter* msg = dutils::gDelayedMessageFactory.Get(this, i);
       if(!msg) {
         std::stringstream temp;
         temp << "TDC error (bank \"" << bankName << "\", addr " << this << "): " << errors[i];
         msg = dutils::gDelayedMessageFactory.Register<dutils::Error>
           (this, i, "vme::V1190::handle_error_buffer", fMessagePeriod, __FILE__, __LINE__, temp.str().c_str());
       }
       if(msg) msg->Incr();
     }
   }
 }
bool vme::V1190::unpack (const midas::Event & event, const char * bankName, bool reportMissing = false)
Unpack TDC data from a MIDAS event.
Parameters
[in] event The midas event to unpack
[in] bankName Name of the bank to unpack
[in] reportMissing False specifies to silently return if bankName isn't found in the event. True specifies to print a warning message if this is the case.
Returns
True if the event was successfully unpacked, false otherwise
Definition at line 341 of file Vme.cxx.
 {
   /*!
    * \param [in] event The midas event to unpack
    * \param [in] bankName Name of the bank to unpack
    * \param [in] reportMissing False specifies to silently return if \e bankName isn't found in
    *             the event. True specifies to print a warning message if this is the case.
    * \returns True if the event was successfully unpacked, false otherwise
    */
   int bank_len;
   uint32_t* pbank32 =
     event.GetBankPointer<uint32_t>(bankName, &bank_len, reportMissing, true);
   // Loop over all data words in the bank
   bool ret = true;
   for (int i=0; i< bank_len; ++i) {
     bool success = unpack_buffer(pbank32++, bankName);
     if(!success) ret = false;
   }
   return ret;
 }
bool vme::V1190::unpack_buffer (const uint32_t *const pbuffer, const char * bankName) private
Unpack a generic V1190 buffer.
Parameters
[in] pbuffer Pointer to the buffer data
[in] bankName Name of the midas bank being unpacked
Returns
True if the buffer was successfully unpacked, false otherwise
V1190 buffers are 32 bit words. Bits 27-31 specify the type of data contained in the buffer. In this function, we read the buffer type and then handle appropriately.
case GLOBAL_HEADER: read event counter from bits 5 - 26
case GLOBAL_TRAILER: read status word from bits 24-26 and word count from bits 5-21
case EXTENDED_TRIGGER_TIME: read extended trigger from bits 0 - 26
case TDC_HEADER: read bunch id from bits 0 - 12, event id from bits 12 - 23
case TDC_MEASUREMENT: See unpack_data_buffer()
case TDC_ERROR: See handle_error_buffer()
case TDC_TRAILER: See unpack_footer_buffer()
Bail out if we read an unknown buffer code
Definition at line 293 of file Vme.cxx.
References DRAGON_ERR_FILE_LINE.
 {
   /*!
    * \param [in] pbuffer Pointer to the buffer data
    * \param [in] bankName Name of the midas bank being unpacked
    * \returns True if the buffer was successfully unpacked, false otherwise
    *
    * V1190 buffers are 32 bit words. Bits 27-31 specify the type of data contained
    * in the buffer. In this function, we read the buffer type and then handle appropriately.
    */
   bool success = true;
   uint32_t type = (*pbuffer >> 27) & READ5;
   switch (type) {
   case GLOBAL_HEADER:  /// case GLOBAL_HEADER: read event counter from bits 5 - 26
     count = (*pbuffer >> 5) & READ22;
     break;
   case GLOBAL_TRAILER: /// case GLOBAL_TRAILER: read status word from bits 24-26 and word count from bits 5-21
     status = (*pbuffer >> 24) & READ3;
     trailer_word_count = (*pbuffer >> 5) & READ16;
     break;
   case EXTENDED_TRIGGER_TIME: /// case EXTENDED_TRIGGER_TIME: read extended trigger from bits 0 - 26
     extended_trigger = (*pbuffer >> 0) & READ27;
     break;
   case TDC_HEADER: /// case TDC_HEADER: read bunch id from bits 0 - 12, event id from bits 12 - 23
     bunch_id = (*pbuffer >> 0)  & READ12;
     event_id = (*pbuffer >> 12) & READ12;
     break;
   case TDC_MEASUREMENT: /// case TDC_MEASUREMENT: See unpack_data_buffer()
     success = unpack_data_buffer(pbuffer);
     break;
   case TDC_ERROR:   /// case TDC_ERROR: See handle_error_buffer()
     handle_error_buffer(pbuffer, bankName);
     success = false;
     break;
   case TDC_TRAILER: /// case TDC_TRAILER: See unpack_footer_buffer()
     unpack_footer_buffer(pbuffer, bankName);
     break;
   default: /// Bail out if we read an unknown buffer code
     dutils::Error("vme::V1190::unpack_buffer", __FILE__, __LINE__)
       << DRAGON_ERR_FILE_LINE << "Bank name: \"" << bankName
       << "\": Unknown TDC buffer code: 0x" << std::hex << type << ". Skipping...\n";
     success = false;
     break;
   }
   return success;
 }
bool vme::V1190::unpack_data_buffer (const uint32_t *const pbuffer) private
Unpack event data buffer.
Parameters
[in] pbuffer Pointer to the data buffer word.
A data buffer encodes the measurement value (i.e. the pulse time) for a single TDC measurement. The TDC is multi-hit, so more than one measurement per channel can be read in a single event.
See below for bitpacking instructions.
Bit 26 tells the measurement type (leading or trailing)
Bits 19-25 tell the channel number
Bits 0 - 18 encode the measurement value
Definition at line 185 of file Vme.cxx.
References DRAGON_ERR_FILE_LINE, vme::V1190::Channel::fLeading, vme::V1190::Channel::fTrailing, vme::V1190::Channel::nleading, and vme::V1190::Channel::ntrailing.
 {
   /*!
    * \param [in] pbuffer Pointer to the data buffer word.
    *
    * A data buffer encodes the measurement value (i.e. the pulse time)
    * for a single TDC measurement. The TDC is multi-hit, so more than one measurement
    * per channel can be read in a single event.
    *
    * See below for bitpacking instructions.
    */
   type     = (*pbuffer >> 26) & READ1; /// - Bit 26 tells the measurement type (leading or trailing)
   int ch   = (*pbuffer >> 19) & READ7; /// - Bits 19-25 tell the channel number
   if (ch >= MAX_CHANNELS) {
     dutils::Error("vme::V1190::unpack_data_buffer", __FILE__, __LINE__)
       << DRAGON_ERR_FILE_LINE << "Read a channel number (" << ch
       << ") which is >= the maximum (" << MAX_CHANNELS << "). Skipping...\n";
     return false;
   }
   if ( !(type==1 || type == 0) ) {
     dutils::Error("vme::V1190::unpack_data_buffer", __FILE__, __LINE__)
       << "\"type\" bitfield == " << type << ": Should be impossible, skipping event..."
       << DRAGON_ERR_FILE_LINE;
     return false;
   }
   int32_t measurement = (*pbuffer >> 0) & READ19; /// - Bits 0 - 18 encode the measurement value
   if (type == 0) // leading edge
   {
     channel[ch].fLeading.push_back(measurement);
   }
   else // trailing edge
     channel[ch].fTrailing.push_back(measurement);
   channel[ch].nleading  = channel[ch].fLeading.size();
   channel[ch].ntrailing = channel[ch].fTrailing.size();
   if(type == 0) fifo0.push_back(measurement, ch, channel[ch].nleading);
   else          fifo1.push_back(measurement, ch, channel[ch].ntrailing);
   return true;
 }
void vme::V1190::unpack_footer_buffer (const uint32_t *const pbuffer, const char * bankName) private
Unpack footer buffer.
Parameters
[in] pbuffer Pointer to the footer buffer
[in] bankName Name of the midas bank being unpacked
Note
Footer also contains the GEO information, which we ignore.
See below for the bitpacking instructions and what we read.
Bits 0 - 11 are the event counter (word_count)
Bits 12 - 23 are the event id (event_id), check for consistency w/ header
Definition at line 230 of file Vme.cxx.
References DRAGON_ERR_FILE_LINE.
 {
   /*!
    * \param [in] pbuffer Pointer to the footer buffer
    * \param [in] bankName Name of the midas bank being unpacked
    * \note Footer also contains the GEO information, which we ignore.
    *
    * See below for the bitpacking instructions and what we read.
    */
   word_count = (*pbuffer >> 0) & READ12; /// Bits 0 - 11 are the event counter (word_count)
   int16_t evtId = (*pbuffer >> 12) & READ12;
   if(evtId != event_id) { /// Bits 12 - 23 are the event id (event_id), check for consistency w/ header
     std::cerr << DRAGON_ERR_FILE_LINE;
     dutils::Warning("vme::V1190::unpack_footer_buffer")
       << DRAGON_ERR_FILE_LINE << "Bank name: \"" << bankName << "\": "
       << "Trailer event id (" << evtId << ") != header event Id (" << event_id << ")\n";
   }
 }
Member Data Documentation
int16_t vme::V1190::type
Measurement type.
0 = leading, 1 = trailing
Definition at line 129 of file Vme.hxx.
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Vme.hxx
/Users/dragon/packages/dragon/analyzer/src/Vme.cxx