DRAGON Analyzer: dragon::SurfaceBarrier Class Reference
dragon::SurfaceBarrier Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
SurfaceBarrier ()
Constructor, initialize data.
void reset ()
Reset all data to vme::NONE.
void read_data (const vme::V785 adcs[], const vme::V1190 &)
Read midas event data.
void calculate ()
Final energy calculation.
Public Attributes
double ecal [MAX_CHANNELS]
Energy signals.
SurfaceBarrier::Variables variables
Variables instance.
Static Public Attributes
static const int MAX_CHANNELS = 2
Number of detectors.
Detailed Description
Surface barrier detectors
Definition at line 320 of file Dragon.hxx.
Constructor & Destructor Documentation
SurfaceBarrier()
dragon::SurfaceBarrier::SurfaceBarrier ()
Constructor, initialize data.
::
Definition at line 615 of file Dragon.cxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::SurfaceBarrier::calculate ()
Final energy calculation.
Performs calibration of energies.
Delegates work to dutils::linear_calibrate()
Definition at line 639 of file Dragon.cxx.
References dragon::utils::linear_calibrate().
 {
   /*!
    * Performs calibration of energies.
    *
    * Delegates work to dutils::linear_calibrate()
    */
   dutils::linear_calibrate(ecal, MAX_CHANNELS, variables.adc);
 }
read_data()
void dragon::SurfaceBarrier::read_data (const vme::V785 adcs[], const vme::V1190 &)
Read midas event data.
Copies adc data into this->ecal[] with channel and module mapping taken from variables.adc.channel and variables.adc.modules
Delegates work to dutils::channel_map()
Parameters
[in] adcs Array of vme::V785 adc modules from which data can be taken
Definition at line 627 of file Dragon.cxx.
References dragon::utils::channel_map().
 {
   /*!
    * Copies adc data into \c this->ecal[] with channel and module mapping taken
    * from variables.adc.channel and variables.adc.modules
    *
    * Delegates work to dutils::channel_map()
    * \param [in] adcs Array of vme::V785 adc modules from which data can be taken
    */
   dutils::channel_map(ecal, MAX_CHANNELS, variables.adc.channel, variables.adc.module, adcs);
 }
reset()
void dragon::SurfaceBarrier::reset ()
Reset all data to vme::NONE.
::
Definition at line 621 of file Dragon.cxx.
References dragon::utils::reset_array().
 {
   /// ::
   dutils::reset_array(MAX_CHANNELS, ecal);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx