DRAGON Analyzer: dragon::LabCM Class Reference
dragon::LabCM Class Reference
Helper class for lab -> CM conversions (fully relativistic)
#include <RootAnalysis.hxx>
Public Member Functions
LabCM (int Zbeam, int Abeam, int Ztarget, int Atarget, double ecm=0, int qbeam=0, int qtarget=0)
LabCM (double mbeam, double mtarget, double ecm=0.)
double GetEcm () const
Get CM energy.
double GetEbeam () const
double GetV2beam () const
double GetEtarget () const
double GetV2target () const
double GetM1 () const
Get beam mass in amu.
double GetM2 () const
Get target mass in amu.
void SetEcm (double ecm)
void SetEbeam (double ebeam)
void SetV2beam (double ebeam)
void SetEtarget (double etarget)
void SetV2target (double etarget)
void SetM1 (double m1)
Set beam mass in amu.
void SetM2 (double m2)
Set target mass in amu.
Private Member Functions
void Init (int Zbeam, int Abeam, int Ztarget, int Atarget, double ecm, int qbeam, int qtarget)
Ctor helper.
Private Attributes
double fM1
Beam mass [keV/c^2].
double fM2
Target mass [keV/c^2].
double fTcm
Center of mass kinetic energy [keV].
Detailed Description
Helper class for lab -> CM conversions (fully relativistic)
Calulations are fully relativistic: For a moving beam (1) and stationary target (2): Ecm^2 = m1^2 + m2^2 + 2*m2*E1 or in terms of kinetic energy: (Tcm + m1 + m2)^2 = m1^2 + m2^2 + 2*m2*(m1 + T1)
Definition at line 259 of file RootAnalysis.hxx.
Constructor & Destructor Documentation
dragon::LabCM::LabCM (int Zbeam, int Abeam, int Ztarget, int Atarget, double ecm = 0, int qbeam = 0, int qtarget = 0)
Ctor, w/ CM energy specification Sets beam and target masses from AME12 compilation. Energies are initially unset, use SetE*() functions to specify an energy.
Parameters
Zbeam Beam charge
Abeam Beam mass number
Ztarget Target charge
Atarget Target mass number
ecm Center-of-mass kinetic energy in keV
Attention
Uses "nuclear" (fully ionized) masses.
Definition at line 2384 of file RootAnalysis.cxx.
 {
   Init(Zbeam, Abeam, Ztarget, Atarget, ecm, qbeam, qtarget);
 }
dragon::LabCM::LabCM (double mbeam, double mtarget, double ecm = 0.)
Ctor, using amu masses ctor initialized with CM energy Uses specified masses directly
Parameters
mbeam Beam mass in AMU
mtarget Taret mass in AMU
ecm Center of mass energy in keV
Definition at line 2397 of file RootAnalysis.cxx.
 {
   SetM1(mbeam);
   SetM2(mtarget);
   fTcm = ecm;
 }
Member Function Documentation
double dragon::LabCM::GetEbeam () const
Get lab frame beam energy in keV
Definition at line 2468 of file RootAnalysis.cxx.
 {
   double Ecm = fTcm + fM1 + fM2; // total energy
   double E1 = (Ecm*Ecm - fM1*fM1 - fM2*fM2) / (2*fM2); // total energy
   double T1 = E1 - fM1; // kinetic energy
   return T1;
 }
double dragon::LabCM::GetEtarget () const
Get target frame energy in keV
Definition at line 2485 of file RootAnalysis.cxx.
 {
   double Ecm = fTcm + fM1 + fM2; // total energy
   double E2 = (Ecm*Ecm - fM1*fM1 - fM2*fM2) / (2*fM1); // total energy
   double T2 = E2 - fM2; // kinetic energy
   return T2;
 }
double dragon::LabCM::GetV2beam () const
Get squared velocity of the beam in keV / u
Definition at line 2461 of file RootAnalysis.cxx.
References dragon::Constants::AMU().
 {
   return GetEbeam() / (fM1/dragon::Constants::AMU());
 }
double dragon::LabCM::GetV2target () const
Get target frame squred velocity in keV/u
Definition at line 2478 of file RootAnalysis.cxx.
References dragon::Constants::AMU().
 {
   return GetEtarget() / (fM2/dragon::Constants::AMU());
 }
void dragon::LabCM::Init (int Zbeam, int Abeam, int Ztarget, int Atarget, double ecm, int qbeam, int qtarget) private
Ctor helper.
Initialize variables
Definition at line 2406 of file RootAnalysis.cxx.
References TAtomicMassTable::IonMass().
 {
   TAtomicMassTable mt; // AME16
   fM1 = mt.IonMass(Zbeam, Abeam, qbeam);
   fM2 = mt.IonMass(Ztarget, Atarget, qtarget);
   fTcm = ecm;
 }
void dragon::LabCM::SetEbeam (double ebeam)
Set lab frame beam energy in keV
Parameters
ebeam Beam energy in keV
Definition at line 2426 of file RootAnalysis.cxx.
 {
   double E1tot = ebeam + fM1; // total energy
   double Ecmtot = sqrt(fM1*fM1 + fM2*fM2 + 2*fM2*E1tot);
   fTcm = Ecmtot - fM1 - fM2;
 }
void dragon::LabCM::SetEcm (double ecm)
Set CM energy
Parameters
ecm Center-of-mass kinetic energy in keV
Definition at line 2418 of file RootAnalysis.cxx.
 {
   fTcm = ecm;
 }
void dragon::LabCM::SetEtarget (double etarget)
Set target frame energy in keV
Parameters
etarget Target energy in keV
Definition at line 2444 of file RootAnalysis.cxx.
 {
   double E2tot = etarget + fM2; // total energy
   double Ecmtot = sqrt(fM1*fM1 + fM2*fM2 + 2*fM1*E2tot);
   fTcm = Ecmtot - fM1 - fM2;
 }
void dragon::LabCM::SetV2beam (double ebeam)
Set squred velocity of the beam in keV/u
Parameters
ebeam Beam energy in keV/u
Definition at line 2436 of file RootAnalysis.cxx.
References dragon::Constants::AMU().
 {
   SetEbeam(ebeam*fM1/dragon::Constants::AMU()); // keV/u -> keV
 }
void dragon::LabCM::SetV2target (double etarget)
Set target frame energy in keV/u
Parameters
etarget Target energy in keV/u
Definition at line 2454 of file RootAnalysis.cxx.
References dragon::Constants::AMU().
 {
   SetEbeam(etarget*fM2/dragon::Constants::AMU()); // keV/u -> keV
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/utils/RootAnalysis.hxx
/Users/dragon/packages/dragon/analyzer/src/utils/RootAnalysis.cxx