DRAGON Analyzer: dragon::LiveTimeCalculator Class Reference
dragon::LiveTimeCalculator Class Reference
Live time calculator.
#include <RootAnalysis.hxx>
Public Member Functions
LiveTimeCalculator ()
Empty.
LiveTimeCalculator (TFile *file, Bool_t calculate=kTRUE)
Initialize with a run file and perform optional calculation.
void Calculate ()
Perform live time calculation across an entire run.
void CalculateSub (Double_t tbegin, Double_t tend)
Perform live time calculation across a subset of the run.
void CalculateChain (TChain *chain)
Perform live time calculation across a chain of runs.
Double_t GetBusytime (const char *which) const
Returns the sum of busy times during the run (or subrun) in seconds.
Double_t GetRuntime (const char *which) const
Returns the run time in seconds.
Double_t GetLivetime (const char *which) const
Returns the live time fraction.
Double_t GetLivetimeError (const char *which) const
Returns the error on the livetime.
TFile * GetFile () const
Reuturn pointer to the currently set run file.
void SetFile (TFile *file)
Change the run file.
void Reset ()
Reset all stored data (livetimes, etc.) to zero.
Static Public Member Functions
static Double_t CalculateRuntime (midas::Database *db, const char *which, Double_t &start, Double_t &stop)
Calculate the run time from saved ODB file.
static Double_t CalculateRuntime (midas::Database *db, const char *which)
Calculate the run time from saved ODB file.
Private Member Functions
Bool_t CheckFile (TTree *&t1, TTree *&t3, midas::Database *&db)
Make sure fFile is valid.
void DoCalculate (Double_t tbegin, Double_t tend)
Does the work of live time calculations.
Private Attributes
TFile * fFile
Run file (no ownership)
Double_t fRuntime [3]
Run times.
Double_t fBusytime [3]
Busy times.
Double_t fLivetime [3]
Live times.
Detailed Description
Live time calculator.
Calculates the live time by looking at the measured run time (with the IO32 clock, so 50 ns precision) and sum of measured busy times for each event. The live time is defined as: (<run time>=""> - <busy time>="">) / <run time>="">
Calculations can be performed for a complete run, subset of a run or a chain of runs. This class also calculates the live time for coincidences. For more information about how this is done, see the dragon::CoincBusytime class documentation
Definition at line 522 of file RootAnalysis.hxx.
Constructor & Destructor Documentation
LiveTimeCalculator() [1/2]
dragon::LiveTimeCalculator::LiveTimeCalculator ()
Empty.
Default Ctor.
Definition at line 1485 of file RootAnalysis.cxx.
References Reset().
                                             :
   fFile(0)
 {
   Reset();
 }
LiveTimeCalculator() [2/2]
dragon::LiveTimeCalculator::LiveTimeCalculator (TFile * file, Bool_t calculate = kTRUE)
Initialize with a run file and perform optional calculation.
Parameters
file Pointer to TFile containing run data. Takes no ownership.
calculate If set to true, performs a full-run live time calculation on initialization
Definition at line 1495 of file RootAnalysis.cxx.
References Calculate(), and Reset().
                                                                          :
   fFile(file)
 {
   Reset();
   if(calculate) Calculate();
 }
Member Function Documentation
Calculate()
void dragon::LiveTimeCalculator::Calculate ()
Perform live time calculation across an entire run.
Results can be viewed with GetLivetime(), GetBusytime(), etc.
Definition at line 1771 of file RootAnalysis.cxx.
Referenced by LiveTimeCalculator(), and dragon::BeamNorm::ReadSbCounts().
 {
   DoCalculate(-1, -1);
 }
CalculateChain()
void dragon::LiveTimeCalculator::CalculateChain (TChain * chain)
Perform live time calculation across a chain of runs.
Calculate overall times across a chain of runs. For this, the sum of running time and busy time across the chain are calculated and then used to figure out the live time fraction.
Definition at line 1799 of file RootAnalysis.cxx.
 {
   TFile* file0 = GetFile(); if(file0) { }
   Double_t sumbusy[3] = {0,0,0}, sumrun[3] = {0,0,0};
   for (Int_t i=0; i< chain->GetListOfFiles()->GetEntries(); ++i) {
     TFile* f = TFile::Open ( chain->GetListOfFiles()->At(i)->GetTitle() );
     if(f->IsZombie()) { f->Close(); continue; }
     SetFile(f);
     Calculate();
     sumrun[0]  += GetRuntime("head");
     sumrun[1]  += GetRuntime("tail");
     sumrun[2]  += GetRuntime("coinc");
     sumbusy[0] += GetBusytime("head");
     sumbusy[1] += GetBusytime("tail");
     sumbusy[2] += GetBusytime("coinc");
     f->Close();
   }
   for(int i=0; i< 3; ++i) {
     fBusytime[i] = sumbusy[i];
     fRuntime[i]  = sumrun[i];
     fLivetime[i] = (sumrun[i] - sumbusy[i]) / sumrun[i];
   }
 }
CalculateRuntime()
Double_t dragon::LiveTimeCalculator::CalculateRuntime (midas::Database * db, const char * which, Double_t & start, Double_t & stop) static
Calculate the run time from saved ODB file.
Parameters
[in] db Pointer to the "odbstop" database for the current run
[in] which "head", "tail", or "coinc"
[out] start Run start time (relative to TSC reset)
[out] stop Run stop time (relative to TSC reset)
Returns
Total run time in seconds. Note that in the case of "coinc", the runtime is calculated as < smallest stop time > - < largest start time >, i.e. it is the total time during which both acquisitions are taking triggers.
Attention
In some cases this could fail to correctly calculate the rollover due to mismatches in the clocks... I think. This will be extremely rare but is something to keep in the back of your mind.
Definition at line 1615 of file RootAnalysis.cxx.
References midas::Database::ReadArray(), and midas::Database::ReadValue().
Referenced by CalculateRuntime().
 {
   Int_t time0, time1, tclock;
   db->ReadValue("/Runinfo/Start time binary", time0); // computer clock start
   db->ReadValue("/Runinfo/Stop time binary",  time1); // computer clock stop
   tclock = time1 - time0;
   // Read TSC start, stop times from the ODB
   double trigStart[2], trigStop[2];
   db->ReadArray("/Experiment/Run Parameters/TSC_TriggerStart", trigStart, 2);
   db->ReadArray("/Experiment/Run Parameters/TSC_TriggerStop",  trigStop,  2);
   // Append rollovers to stop time
   const Double_t rolltime = 0xffffffff / 20e6; // 32-bit clock rollover in seconds
   int nroll = tclock / rolltime;
   for(int i=0; i<2; ++i) trigStop[i] += nroll*rolltime;
   // now calculte the appropriate run time
   switch(get_which_indx(which)) {
   case 0: // "head"
     stop  = trigStop[0];
     start = trigStart[0];
     break;
   case 1: // "tail"
     stop  = trigStop[1];
     start = trigStart[1];
     break;
   case 2: // "coinc"
     stop  = *std::min_element(trigStop, trigStop + 2);
     start = *std::max_element(trigStart, trigStart + 2);
     break;
   default:
     utils::Error("CalculateRuntime", __FILE__, __LINE__)
       << "Invalid \"which\" specification: \"" << which << "\", valid options "
       << "are \"head\", \"tail\", or \"coinc\"";
     stop = 0;
     start = 0;
     break;
   }
   return stop - start;
 }
CalculateSub()
void dragon::LiveTimeCalculator::CalculateSub (Double_t tbegin, Double_t tend)
Perform live time calculation across a subset of the run.
Parameters
tbegin Beginning of the run sub section (in seconds)
tend End of the run sub section (seconds). If specified greater than the end of the run, this will just calculate up to the end of the run.
The parameters tbegin and tend are both relative to the "trigger start", which is the time at which the frontend begins to accept triggers (this is ~2 seconds later than the "run start" time, which would be when the user pushed start on the MIDAS page. The difference is due to the time it takes for the frontend programs to complete their startup routines.
Results can be viewed with GetLivetime(), GetBusytime(), etc.
Definition at line 1789 of file RootAnalysis.cxx.
Referenced by dragon::BeamNorm::ReadSbCounts().
 {
   DoCalculate(tbegin, tend);
 }
CheckFile()
Bool_t dragon::LiveTimeCalculator::CheckFile (TTree *& t1, TTree *& t3, midas::Database *& db) private
Make sure fFile is valid.
Also sets tree and DB pointers.
Definition at line 1554 of file RootAnalysis.cxx.
 {
   if(!fFile || fFile->IsZombie()) {
     dutils::Error("LiveTimeCalculator::CheckFile", __FILE__, __LINE__)
       << "Invalid or no file loaded.";
     return kFALSE;
   }
   Bool_t okay = kTRUE;
   if(okay) okay = fFile->Get("t1") && fFile->Get("t1")->IsA() == TTree::Class();
   if(okay) okay = fFile->Get("t3") && fFile->Get("t3")->IsA() == TTree::Class();
   if(!okay) {
     dutils::Error("LiveTimeCalculator::CheckFile", __FILE__, __LINE__)
       << "missing necessary trees in loaded file";
     return kFALSE;
   } else {
     t1 = static_cast<TTree*>(fFile->Get("t1"));
     t3 = static_cast<TTree*>(fFile->Get("t3"));
   }
   if(okay) okay = t1->GetLeaf("io32.busy_time");
   if(okay) okay = t3->GetLeaf("io32.busy_time");
   if(!okay) {
     dutils::Error("LiveTimeCalculator::CheckFile", __FILE__, __LINE__)
       << "missing leaf \"io32.busy_time\" in either \"t1\" or \"t3\"";
     return kFALSE;
   }
   if(okay) okay = t1->GetLeaf("io32.tsc4.trig_time");
   if(okay) okay = t3->GetLeaf("io32.tsc4.trig_time");
   if(!okay) {
     dutils::Error("LiveTimeCalculator::CheckFile", __FILE__, __LINE__)
       << "missing leaf \"io32.tsc4.trig_time\" in either \"t1\" or \"t3\"";
     return kFALSE;
   }
   okay = fFile->Get("odbstop") && fFile->Get("odbstop")->InheritsFrom(midas::Database::Class());
   if(!okay) {
     dutils::Error("LiveTimeCalculator::CheckFile", __FILE__, __LINE__)
       << "Loaded file is missing database \"odbstop\"";
     return kFALSE;
   }
   db = static_cast<midas::Database*>(fFile->Get("odbstop"));
   return kTRUE;
 }
DoCalculate()
void dragon::LiveTimeCalculator::DoCalculate (Double_t tbegin, Double_t tend) private
Does the work of live time calculations.
Generic function called by public functions Calculate() and CalculateSub()
Definition at line 1689 of file RootAnalysis.cxx.
References dragon::CoincBusytime::AddEvent(), and dragon::CoincBusytime::Calculate().
 {
   // reset to default values
   Reset();
   // make sure arguments are workable, checkif full calculation or not
   Bool_t isFull = (tbegin < 0 || tend < 0);
   if (isFull) {
     if(tbegin > 0 || tend > 0) {
       utils::Error("LiveTimeCalculator::DoCalculate", __FILE__, __LINE__)
         << "Invalid parameters to LiveTimeCalculator::DoCalculate(): "
         << "tbegin = " << tbegin <<  ", tend = " << tend;
       return;
     }
   }
   if (!isFull && tend <= tbegin) {
     utils::Error("LiveTimeCalculator::DoCalculate", __FILE__, __LINE__)
       << "Cannot have tend <= tbegin: tend, tbegin = " << tend << ", " << tbegin;
     return;
   }
   // Initialize midas database, TTrees, etc
   midas::Database* db = 0;
   TTree* trees[2] = { 0, 0 };
   if(!CheckFile(trees[0], trees[1], db)) { // CheckFile now sets trees[i], db if they're valid
     utils::Error("LiveTimeCalculator::DoCalculate", __FILE__, __LINE__)
       << "Invalid file or trees";
     return;
   }
   size_t nentries = trees[0]->GetEntries() + trees[1]->GetEntries();
   CoincBusytime coincBusy(nentries);
   // Ensure to reset branch addresses when done
   AutoResetBranchAddresses Rst_(trees, 2);
   // Get run times
   double trigStart[3], trigStop[3];
   CalculateRuntime(db, "head",  trigStart[0], trigStop[0]);
   CalculateRuntime(db, "tail",  trigStart[1], trigStop[1]);
   CalculateRuntime(db, "coinc", trigStart[2], trigStop[2]);
   // Loop over trees
   for(int i=0; i< 2; ++i) {
     // Set MakeClass to 1 (resets at end of loop or return)
     SetMakeClass_t dummy(trees[i], 1);
     // Find branches
     UInt_t busy_time;
     Double_t trig_time;
     TBranch* trigBranch = get_branch(trees[i], trig_time, "io32.tsc4.trig_time",
                                      "LiveTimeCalculator::DoCalculate");
     TBranch* busyBranch = get_branch(trees[i], busy_time, "io32.busy_time",
                                      "LiveTimeCalculator::DoCalculate");
     if(!trigBranch || !busyBranch) return;
     // Correct TSC4 rollover for early runs taken with a frontend bug
     Double_t rollCorrect = correct_rollover_fe_bug(trigBranch, trig_time);
     Long64_t busyTotal = 0;
     Long64_t nentries = trees[i]->GetEntries();
     for(Long64_t entry = 0; entry< nentries; ++entry) {
       // read entries
       trigBranch->GetEntry(entry);
       busyBranch->GetEntry(entry);
       const Double_t trigtime = trig_time - rollCorrect - trigStart[i];
       // check cut condition
       if (!isFull && !(trigtime > tbegin*1e6 && trigtime < tend*1e6))
         continue;
       // accuulate busy time
       busyTotal += busy_time;
       coincBusy.AddEvent(trigtime, busy_time/20.);
     }
     // calculate variables
     fBusytime[i] = busyTotal / 20e6;
     fRuntime[i]  = isFull ? trigStop[i] - trigStart[i] : tend - tbegin;
     fLivetime[i] = (fRuntime[i] - fBusytime[i]) / fRuntime[i];
   }
   fRuntime[2]  = isFull ? trigStop[2] - trigStart[2] : tend - tbegin;
   fBusytime[2] = coincBusy.Calculate();
   fLivetime[2] = (fRuntime[2] - fBusytime[2]) / fRuntime[2];
 }
GetLivetimeError()
Double_t dragon::LiveTimeCalculator::GetLivetimeError (const char * which) const inline
Returns the error on the livetime.
The relative error should
Definition at line 545 of file RootAnalysis.hxx.
References GetLivetime().
     { return GetLivetime(which) * 50/1e6; } // seconds
SetFile()
void dragon::LiveTimeCalculator::SetFile (TFile * file) inline
Change the run file.
Attention
Does not clear previous calculations
Definition at line 552 of file RootAnalysis.hxx.
References fFile.
Referenced by dragon::BeamNorm::ReadSbCounts().
 { fFile = file; }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/utils/RootAnalysis.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/utils/RootAnalysis.cxx