DRAGON Analyzer: Sonik::Variables Class Reference
Sonik::Variables Class Reference
#include <Sonik.hxx>
Public Member Functions
Variables ()
Constructor, sets data to generic values.
bool set (const char *dbfile)
Set data values from an database (file or online)
bool set (const midas::Database *db)
Set data values from a constructed database.
void reset ()
Reset all variable values to defaults.
Public Attributes
dragon::utils::AdcVariables< 32 > adc
Adc variables for the energy signals.
dragon::utils::TdcVariables< 1 > tdc
Tdc variables.
dragon::utils::TdcVariables< 1 > rf_tdc
RF TDC channel variables.
dragon::utils::TdcVariables< 1 > tdc0
Trigger TDC channel variables.
Detailed Description
Sonik Variables Class
Definition at line 59 of file Sonik.hxx.
Constructor & Destructor Documentation
Variables()
Sonik::Variables::Variables ()
Constructor, sets data to generic values.
Calls reset()
Definition at line 135 of file Sonik.cxx.
References reset().
 {
   /*! Calls reset() */
   reset();
 }
Member Function Documentation
reset()
void Sonik::Variables::reset ()
Reset all variable values to defaults.
::
Definition at line 141 of file Sonik.cxx.
References DSSSD_ADC0, DSSSD_MODULE, DSSSD_TDC0, dragon::utils::index_fill(), and Sonik::MAX_CHANNELS.
Referenced by Variables().
 {
   /// ::
   std::fill(adc.module, adc.module + MAX_CHANNELS, DSSSD_MODULE);
   dutils::index_fill(adc.channel, adc.channel + MAX_CHANNELS, DSSSD_ADC0);
   std::fill(adc.pedestal, adc.pedestal + MAX_CHANNELS, 0);
   std::fill(adc.slope,  adc.slope + MAX_CHANNELS, 1.);
   std::fill(adc.offset, adc.offset + MAX_CHANNELS, 0.);
   tdc.module  = 0; // unused
   tdc.channel = DSSSD_TDC0;
   tdc.slope   = 1.;
   tdc.offset  = 0.;
   tdc0.module  = 0; // unused
   tdc0.channel = 9;
   tdc0.slope   = 1.;
   tdc0.offset  = 0.;
   rf_tdc.module  = 0; // unused
   rf_tdc.channel = 8;
   rf_tdc.slope   = 1.;
   rf_tdc.offset  = 0.;
 }
set() [1/2]
bool Sonik::Variables::set (const char * dbfile)
Set data values from an database (file or online)
Parameters
[in] dbfile Path of the odb file from which you are extracting variable values
Definition at line 168 of file Sonik.cxx.
Referenced by Sonik::set_variables().
 {
   /*!
    * \param [in] dbfile Path of the odb file from which you are extracting variable values
    */
   return do_setv(this, dbfile);
 }
set() [2/2]
bool Sonik::Variables::set (const midas::Database * db)
Set data values from a constructed database.
Parameters
[in] Pointer to a constructed database.
Definition at line 176 of file Sonik.cxx.
References Sonik::MAX_CHANNELS, midas::Database::ReadArray(), and midas::Database::ReadValue().
 {
   /*!
    * \param [in] Pointer to a constructed database.
    */
   bool success = check_db(db, "Sonik");
   if(success) success = db->ReadArray("/sonik/variables/adc/module",   adc.module,   MAX_CHANNELS);
   if(success) success = db->ReadArray("/sonik/variables/adc/channel",  adc.channel,  MAX_CHANNELS);
   if(success) success = db->ReadArray("/sonik/variables/adc/slope",    adc.slope,    MAX_CHANNELS);
   if(success) success = db->ReadArray("/sonik/variables/adc/offset",   adc.offset,   MAX_CHANNELS);
   if(success) success = db->ReadValue("/sonik/variables/tdc/channel", tdc.channel);
   if(success) success = db->ReadValue("/sonik/variables/tdc/slope",   tdc.slope);
   if(success) success = db->ReadValue("/sonik/variables/tdc/offset",  tdc.offset);
   if(success) success = db->ReadValue("/sonik/variables/tdc0/channel", tdc0.channel);
   if(success) success = db->ReadValue("/sonik/variables/tdc0/slope",   tdc0.slope);
   if(success) success = db->ReadValue("/sonik/variables/tdc0/offset",  tdc0.offset);
   return success;
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Sonik.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Sonik.cxx