DRAGON Analyzer: dragon::Epics Class Reference
dragon::Epics Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Epics ()
Initialize data.
void reset ()
Reset all data to zero.
void unpack (const midas::Event &event)
Unpack Midas event data into scalar data structiures.
const std::string & channel_name (int ch) const
Returns the name of a given scaler channel.
bool set_variables (const char *dbfile)
Reads all variable values from an database (file or online)
bool set_variables (const midas::Database *db)
Reads all variable values from a constructed database.
template<class T >
void set_aliases (T *t) const
Set branch alises in a ROOT TTree.
Public Attributes
TMidas_EVENT_HEADER header
Midas event header.
int32_t ch
Epics channel number for this event.
float val
EPICS value at ch for this event.
Variables variables
Variables instance.
Detailed Description
DRAGON EPICS parameters
Definition at line 852 of file Dragon.hxx.
Constructor & Destructor Documentation
Epics()
dragon::Epics::Epics ()
Initialize data.
Calls reset()
Definition at line 1550 of file Dragon.cxx.
References dragon::Scaler::reset().
 {
   /*! Calls reset() */
   reset();
 }
Member Function Documentation
channel_name()
const std::string & dragon::Epics::channel_name (int ch) const
Returns the name of a given scaler channel.
Parameters
ch Channel number
Definition at line 1600 of file Dragon.cxx.
References dragon::Scaler::Variables::names, and dragon::Scaler::variables.
 {
   /*!
    * \param ch Channel number
    */
   if (ch >= 0 && (unsigned)ch < variables.names.size())
     return variables.names[ch];
   dutils::Error("dragon::Epics::channel_name", __FILE__, __LINE__)
     << "Invalid channel number: " << ch << ". Valid arguments are 0 <= ch < " << variables.names.size();
   static std::string junk = "";
   return junk;
 }
reset()
void dragon::Epics::reset ()
Reset all data to zero.
Sets all ch and val to vme::NONE, header to all zeroes.
Definition at line 1556 of file Dragon.cxx.
References dragon::utils::reset_data().
 {
   /*! Sets all ch and val to vme::NONE, header to all zeroes. */
   const midas::Event::Header temp = { 0, 0, 0, 0, 0 };
   header = temp;
   utils::reset_data(ch, val);
 }
set_aliases()
template<class T > void dragon::Epics::set_aliases (T * t) const inline
Set branch alises in a ROOT TTree.
See dragon::Scaler::set_aliases()
Definition at line 986 of file Dragon.hxx.
 {
   /*!
    * See dragon::Scaler::set_aliases()
    */
   for(unsigned int k=0; k< variables.names.size(); ++k) {
     std::stringstream oldName;
     oldName << "1*" << k << "";
     std::string newName1 = variables.names[k];
     for(size_t j=0; j< newName1.size(); ++j) {
       if(newName1[j] == ' ') newName1[j] = '_';
     }
     t->SetAlias(newName1.c_str(), oldName.str().c_str());
   }
 }
set_variables() [1/2]
bool dragon::Epics::set_variables (const char * dbfile)
Reads all variable values from an database (file or online)
Delegates to dragon::Epics::Variables::Set()
Definition at line 1564 of file Dragon.cxx.
References dragon::Scaler::Variables::set(), and dragon::Scaler::variables.
 {
   /*!
    * Delegates to dragon::Epics::Variables::Set()
    */
   return variables.set(dbfile);
 }
set_variables() [2/2]
bool dragon::Epics::set_variables (const midas::Database * db)
Reads all variable values from a constructed database.
Delegates to dragon::Epics::Variables::Set()
Definition at line 1572 of file Dragon.cxx.
References dragon::Scaler::Variables::set(), and dragon::Scaler::variables.
 {
   /*!
    * Delegates to dragon::Epics::Variables::Set()
    */
   return variables.set(db);
 }
unpack()
void dragon::Epics::unpack (const midas::Event & event)
Unpack Midas event data into scalar data structiures.
::
Read channel number and value from the bank
Copy event header
Definition at line 1580 of file Dragon.cxx.
References dragon::Scaler::variables.
 {
   /// ::
   bool report = true;
   int bank_len;
   float* pch = event.GetBankPointer<float>(variables.bkname, &bank_len, report, true);
   /// - Read channel number and value from the bank
   if(bank_len == 2) {
     ch  = static_cast<int32_t>(*pch++);
     val = *pch++;
   } else {
     dutils::Error("Epics::unpack", __FILE__, __LINE__)
       << "Bank len != 2, skipping!";
   }
   /// - Copy event header
   event.CopyHeader(header);
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx