DRAGON Analyzer: dragon::StoppingPowerCalculator Class Reference
dragon::StoppingPowerCalculator Class Reference
Stopping power calculator.
#include <RootAnalysis.hxx>
Classes
struct Measurement_t
Public Types
enum XAxisType_t { kPRESSURE, kDENSITY }
enum YAxisType_t { kMD1, kENERGY }
Public Member Functions
StoppingPowerCalculator ()
Dummy constructor.
StoppingPowerCalculator (Int_t beamCharge, Double_t beamMass, Int_t nmol, Double_t temp=300., Double_t targetLen=12.3, Double_t targetLenErr=0.4, Double_t cmd1=4.815e-7, Double_t cmd1Err=0.0015 *4.815e-7)
Construct a stopping power calculator with parameters.
UDouble_t GetTargetLength () const
Get the target length.
void SetTargetLength (Double_t len, Double_t err)
Set the target length.
Double_t GetTemp () const
Get the temperature.
void SetTemp (Double_t temp)
Set the temperature.
Int_t GetQbeam () const
Get beam charge.
void SetQbeam (Int_t q)
Set beam charge.
Double_t GetBeamMass () const
Get beam mass.
void SetBeamMass (Double_t mass)
Set beam mass.
Int_t GetNmol () const
Get atoms/molecule.
void SetNmol (Int_t nmol)
Set atoms/molecule.
UDouble_t GetMd1Constant () const
Get MD1 constant.
void SetMd1Constant (Double_t md1, Double_t md1Err)
Set MD1 constant.
void AddMeasurement (Double_t pressure, Double_t pressureErr, Double_t md1, Double_t md1Err)
Add a pressure, energy measurement.
Measurement_t GetMeasurement (Int_t index) const
Get a pressure, energy measurement.
Int_t GetNmeasurements () const
Get the number of measurements.
void RemoveMeasurement (Int_t index)
Remove a pressure, energy measurement.
TGraphAsymmErrors * PlotMeasurements (XAxisType_t xaxis=kPRESSURE, YAxisType_t yaxis=kENERGY, Bool_t draw=kTRUE, Bool_t print=kTRUE) const
Plot energy vs. pressure or density.
UDouble_t CalculateEpsilon (TGraphAsymmErrors **plot=0, UDouble_t *ebeam=0)
Calculate the epsilon parameter - slope of eloss vs. (atoms/cm^2)
UDouble_t CalculateEbeam (TGraphAsymmErrors **plot=0)
Calculate the beam energy (intercept of E vs. P)
Static Public Member Functions
static Double_t TorrCgs (Double_t torr)
Convert pressure in torr to dyn/cm^2.
static UDouble_t TorrCgs (UDouble_t torr)
Convert pressure in torr to dyn/cm^2 (with uncertainty)
static Double_t CalculateDensity (Double_t pressure, Double_t length, Int_t nmol, Double_t temp=300.)
Calculate target density in atoms/cm^2.
static UDouble_t CalculateDensity (UDouble_t pressure, UDouble_t length, Int_t nmol, Double_t temp=300.)
Calculate target density in atoms/cm^2 (with uncertainty)
static UDouble_t CalculateEnergy (Double_t md1, Double_t md1Err, Int_t q, Double_t m, Double_t cmd1=4.815e-7, Double_t cmd1Err=0.0015 *4.815e-7)
Calculate beam energy from MD1 field.
Private Attributes
Double_t fBeamMass
Atomic mass of beam.
Int_t fBeamCharge
Charge of beam.
Int_t fNmol
Target atoms / gas molecule.
UDouble_t fTargetLength
Target effective length.
Double_t fTemp
Temperature.
UDouble_t fMd1Constant
MD1 constant.
std::vector< UDouble_t > fPressures
Pressure measurements.
std::vector< UDouble_t > fDensities
Pressure measurements.
std::vector< UDouble_t > fMd1
MD1 measurements.
std::vector< UDouble_t > fEnergies
Energy measurements.
Detailed Description
Stopping power calculator.
Definition at line 412 of file RootAnalysis.hxx.
Class Documentation
dragon::StoppingPowerCalculator::Measurement_t
struct dragon::StoppingPowerCalculator::Measurement_t
Definition at line 422 of file RootAnalysis.hxx.
Class Members
UDouble_t density
UDouble_t energy
UDouble_t md1
UDouble_t pressure
Constructor & Destructor Documentation
StoppingPowerCalculator()
dragon::StoppingPowerCalculator::StoppingPowerCalculator (Int_t beamCharge, Double_t beamMass, Int_t nmol, Double_t temp = 300., Double_t targetLen = 12.3, Double_t targetLenErr = 0.4, Double_t cmd1 = 4.815e-7, Double_t cmd1Err = 0.0015*4.815e-7)
Construct a stopping power calculator with parameters.
Ctor
Parameters
beamCharge Beam charge state
beamMass Beam mass in AMU
nmol Number of atoms per molecule in the target
targetLen Effective gas target length in cm
targetLenErr Absolute error on targetLen
cmd1 "Magnetic constant" for MD1 in (keV/u)*G2
cmd1Err Absolute error on cmd1
temp Ambient temperature in kelvin
Definition at line 1958 of file RootAnalysis.cxx.
                                                                           :
   fBeamMass(beamMass),
   fBeamCharge(beamCharge),
   fNmol(nmol),
   fTargetLength(targetLen, targetLenErr),
   fTemp(temp),
   fMd1Constant(cmd1, cmd1Err)
 {
   ;
 }
Member Function Documentation
AddMeasurement()
void dragon::StoppingPowerCalculator::AddMeasurement (Double_t pressure, Double_t pressureErr, Double_t md1, Double_t md1Err)
Add a pressure, energy measurement.
Parameters
pressure Measured pressure in torr
pressureErr Error (absolute) on the pressure measurement
md1 Measured MD1 field
md1Err Error (absolute) on measured MD1 field
Definition at line 2049 of file RootAnalysis.cxx.
 {
   UDouble_t upressure (pressure, pressureErr);
   UDouble_t energy = CalculateEnergy(md1, md1Err, fBeamCharge, fBeamMass,
                                      fMd1Constant.GetNominal(), fMd1Constant.GetErrLow());
   UDouble_t density = CalculateDensity(upressure, fTargetLength, fNmol, fTemp);
   fEnergies.push_back(energy);
   fDensities.push_back(density);
   fPressures.push_back(upressure);
   UDouble_t umd1(md1, md1Err);
   fMd1.push_back(umd1);
 }
CalculateDensity() [1/2]
Double_t dragon::StoppingPowerCalculator::CalculateDensity (Double_t pressure, Double_t length, Int_t nmol, Double_t temp = 300.) static
Calculate target density in atoms/cm^2.
Parameters
pressure Gas pressure in torr
length Effective target length in cm
nmol Number of atoms per molecule in the gas
temp Temperature in kelvin
Returns
Density in atoms / cm2
Definition at line 1998 of file RootAnalysis.cxx.
Referenced by dragon::CrossSectionCalculator::CalculateCrossSection().
 {
   return nmol * TorrCgs(pressure) * length / TMath::Kcgs() / temp;
 }
CalculateDensity() [2/2]
UDouble_t dragon::StoppingPowerCalculator::CalculateDensity (UDouble_t pressure, UDouble_t length, Int_t nmol, Double_t temp = 300.) static
Calculate target density in atoms/cm^2 (with uncertainty)
Parameters
pressure Gas pressure in torr (with uncertainty)
length Effective target length in cm (with uncertainty)
nmol Number of atoms per molecule in the gas
temp Temperature in kelvin
Returns
Density in atoms / cm2 (with uncertainty)
Definition at line 2010 of file RootAnalysis.cxx.
 {
   return nmol * TorrCgs(pressure) * length / TMath::Kcgs() / temp;
 }
CalculateEbeam()
UDouble_t dragon::StoppingPowerCalculator::CalculateEbeam (TGraphAsymmErrors ** plot = 0)
Calculate the beam energy (intercept of E vs. P)
Parameters
[out] plot Address of a pointer to a TGraph that will contain a plot of energy vs. pressure upon successful return. Passing a non-NULL plot argument also causes the plot to be drawn with option "AP". The default argument (NULL) bypasses any plotting and simply calculates the beam energy.
Returns
The beam energy at zero pressure from a linear fit of E vs. P.
Definition at line 2148 of file RootAnalysis.cxx.
 {
   UDouble_t out(0,0);
   std::auto_ptr<TGraphAsymmErrors> g(new TGraphAsymmErrors(GetNmeasurements()));
   // calculate density, energy w/ random errors only
   std::vector<UDouble_t> pres(GetNmeasurements()), energy(GetNmeasurements());
   for(Int_t i=0; i< GetNmeasurements(); ++i) {
     double md1err = fMd1[i].GetErrLow() < fMd1[i].GetErrHigh() ? fMd1[i].GetErrHigh()
                                           : fMd1[i].GetErrLow();
     pres[i] = fPressures[i];
     energy[i] = CalculateEnergy(fMd1[i].GetNominal(), md1err, fBeamCharge,
                                 fBeamMass, fMd1Constant.GetNominal(), 0);
   }
   // plot and fit to get dE/d[n/A]
   g.reset(PlotUncertainties(GetNmeasurements(), &pres[0], &energy[0]));
   dragon::LinearFitter fit;
   fit.Fit(g.get());
   out = fit.GetOffset();
   // plot if requested
   if(plot) {
     *plot = (TGraphAsymmErrors*)g->Clone();
     (*plot)->SetMarkerStyle(20);
     (*plot)->SetTitle(Form("Beam energy: %.2f^{+ %.3f}_{-%.3f} keV/u; Pressure [Torr]; Energy [keV/u]",
                            out.GetNominal(), out.GetErrHigh(), out.GetErrLow() ) );
     (*plot)->GetXaxis()->CenterTitle();
     (*plot)->GetYaxis()->CenterTitle();
     (*plot)->Draw("AP");
     if(fit.GetFunction()) {
       TF1* ffit2 = (TF1*)fit.GetFunction()->Clone();
       ffit2->SetLineColor(4); ffit2->Draw("SAME");
     }
     else std::cerr << "No function!\n";
   }
   return out;
 }
CalculateEnergy()
UDouble_t dragon::StoppingPowerCalculator::CalculateEnergy (Double_t md1, Double_t md1Err, Int_t q, Double_t m, Double_t cmd1 = 4.815e-7, Double_t cmd1Err = 0.0015*4.815e-7) static
Calculate beam energy from MD1 field.
Energy is calculated using equation 2 from Dave Hutcheon's NIM paper on BGO z-position E/m = cmd1 * (qB/m)<sup>2</sup> - [1/(2*u*c<sup>2</sup>)] * (E/m)<sup>2</sup>
Parameters
md1 MD1 field in Gauss
md1Err Absolute error on MD1 field
q Beam charge state
m Beam mass in AMU
cmd1 "Magnetic constant" for MD1 in (keV/u)*G2
cmd1Err Absolute error on cmd1
Returns
Beam energy in keV/u
Definition at line 2029 of file RootAnalysis.cxx.
References dragon::Constants::AMU(), and dragon::Constants::AMUUnc().
 {
   UDouble_t ucmd1 (cmd1, cmd1Err);
   UDouble_t uAMU  (dragon::Constants::AMU(), dragon::Constants::AMUUnc());
   UDouble_t a = 1/(2*uAMU);
   Double_t  b = 1.;
   UDouble_t c = -1*ucmd1*UDouble_t::pow((q*UDouble_t(md1, md1Err) / m), 2);
   return 1.e3*(-b + UDouble_t::sqrt(b*b - 4*a*c)) / (2.*a); // relativistic beam energy in keV / u
   // return -1.e3*c // non relativistic
 }
CalculateEpsilon()
UDouble_t dragon::StoppingPowerCalculator::CalculateEpsilon (TGraphAsymmErrors ** plot = 0, UDouble_t * ebeam = 0)
Calculate the epsilon parameter - slope of eloss vs. (atoms/cm^2)
Parameters
[out] plot Address of a pointer to a TGraph that will contain a plot of energy vs. density upon successful return. Passing a non-NULL plot argument also causes the plot to be drawn with option "AP". The default argument (NULL) bypasses any plotting and simply calculates the epsilon parameter.
[out] ebeam Pointer to UDouble_t holding beam energy from offset of linear fit.
Returns
The epslion parameter used in calculations of omega-gamma, in units of eV / [atoms / cm2]
Note
For treatment of errors, we should only include random errors in the plot to be fit. Systematic errors (i.e target pressure and c_md1) will pull all points in the same direction and should only be added back after the linear fit is done.
Definition at line 2201 of file RootAnalysis.cxx.
 {
   UDouble_t out(0,0);
   std::auto_ptr<TGraph> g(new TGraphAsymmErrors(GetNmeasurements()));
   // calculate density, energy w/ random errors only
   std::vector<UDouble_t> dens(GetNmeasurements()), energy(GetNmeasurements());
   for(Int_t i=0; i< GetNmeasurements(); ++i) {
     double md1err = fMd1[i].GetErrLow() < fMd1[i].GetErrHigh() ?
                                           fMd1[i].GetErrHigh() : fMd1[i].GetErrLow();
     dens[i] = CalculateDensity(fPressures[i], UDouble_t(fTargetLength.GetNominal(), 0),
                                fNmol, fTemp);
     energy[i] = CalculateEnergy(fMd1[i].GetNominal(), md1err, fBeamCharge, fBeamMass,
                                 fMd1Constant.GetNominal(), 0);
   }
   // plot and fit to get dE/d[n/A]
   g.reset(PlotUncertainties(GetNmeasurements(), &dens[0], &energy[0]));
   dragon::LinearFitter fit;
   fit.Fit(g.get());
   out = -1*fit.GetSlope();
   out *= fBeamMass; // keV/u -> keV
   out *= 1e3; // keV -> eV
   if(ebeam) {
     *ebeam = 1*fit.GetOffset(); // keV/u;
   }
   // add back systematic errors
   out *= fMd1Constant / fMd1Constant.GetNominal();
   out *= fTargetLength / fTargetLength.GetNominal();
   if(ebeam) {
     // *ebeam *= fMd1Constant / fMd1Constant.GetNominal();
     // *ebeam *= fTargetLength / fTargetLength.GetNominal();
   }
   // plot if requested
   if(plot) {
     *plot = (TGraphAsymmErrors*)g->Clone();
     (*plot)->SetMarkerStyle(21);
     char buf[256];
     if(out.GetErrHigh() != out.GetErrLow()) {
       sprintf(buf, "Stopping power: %g ^{+%g}_{-%g} eV cm^{2} / atom;Density [atoms/cm^{2}];Beam energy [keV/u]",
               out.GetNominal(), out.GetErrLow(), out.GetErrHigh());
     }
     else {
       sprintf(buf, "Stopping power: %g +/-%g eV cm^{2} / atom;Density [atoms/cm^{2}];Beam energy [keV/u]",
               out.GetNominal(), out.GetErrLow());
     }
     (*plot)->SetTitle(buf);
     (*plot)->Draw("AP");
     if(fit.GetFunction()) {
       TF1* ffit2 = (TF1*)fit.GetFunction()->Clone();
       ffit2->Draw("SAME");
     }
     else std::cerr << "No function!\n";
   }
   return out;
 }
GetMeasurement()
dragon::StoppingPowerCalculator::Measurement_t dragon::StoppingPowerCalculator::GetMeasurement (Int_t index) const
Get a pressure, energy measurement.
Parameters
index Which measurement to return
Definition at line 2067 of file RootAnalysis.cxx.
 {
   Measurement_t retval = {0, 0, 0, 0};
   size_t index0 = index;
   if(index0 < fEnergies.size()) {
     retval.pressure = fPressures.at(index0);
     retval.energy = fEnergies.at(index0);
     retval.density = fDensities.at(index0);
     retval.md1 = fMd1.at(index0);
   } else {
     dutils::Error("StoppingPowerCalculator::GetMeasurement", __FILE__, __LINE__)
       << "invalid index " << index << ", valid options are [0, ) " << fEnergies.size();
   }
   return retval;
 }
PlotMeasurements()
TGraphAsymmErrors * dragon::StoppingPowerCalculator::PlotMeasurements (XAxisType_t xaxis = kPRESSURE, YAxisType_t yaxis = kENERGY, Bool_t draw = kTRUE, Bool_t print = kTRUE) const
Plot energy vs. pressure or density.
Parameters
xaxis Specify the x axis. Valid options are dragon::StoppingPowerCalculator::kPRESSURE (== 0) to plot pressure (torr), or dragon::StoppingPowerCalculator::kDENSITY (== 1) to plot density (atoms/cm2).
yaxis Specify the y axis. Valid options are dragon::StoppingPowerCalculator::kMD1 (== 0) to plot MD1 field (gauss) or dragon::StoppingPowerCalculator::kENERGY (== 1) to plot energy (keV/u).
draw Argument true plots the graph with option "AP" in addition to returning it.
Returns
TGraph of pressure vs. energy, with asymmetric error bars on both axes. Responsibility is on the user to delete the returned graph.
Definition at line 2110 of file RootAnalysis.cxx.
 {
   TGraphAsymmErrors* out = 0;
   if(!fEnergies.empty()) {
     const UDouble_t* x = xaxis == kDENSITY ? &fDensities[0] : &fPressures[0];
     const UDouble_t* y = yaxis == kMD1     ? &fMd1[0]       : &fEnergies[0];
     out = PlotUncertainties(fEnergies.size(), x, y);
   }
   if(out) {
     out->SetTitle("");
     if(xaxis == kPRESSURE){
       out->GetXaxis()->SetTitle("Pressure [Torr]");
     } else {
       out->GetXaxis()->SetTitle("Density [10^{15} atoms / cm^{2}]");
     }
     if(yaxis == kENERGY){
       out->GetYaxis()->SetTitle("Energy [keV / u]");
     } else {
       out->GetYaxis()->SetTitle("NMR1 Field [Gauss]");
     }
     out->SetMarkerStyle(20);
     out->GetXaxis()->CenterTitle();
     out->GetYaxis()->CenterTitle();
     if(draw) out->Draw("AP");
     if(print) out->Print();
   }
   return out;
 }
RemoveMeasurement()
void dragon::StoppingPowerCalculator::RemoveMeasurement (Int_t index)
Remove a pressure, energy measurement.
Parameters
index Which measurement to remove
Definition at line 2085 of file RootAnalysis.cxx.
 {
   size_t index0 = index;
   if(index0 < fEnergies.size()) {
     fPressures.erase(fPressures.begin() + index0);
     fEnergies.erase (fPressures.begin() + index0);
   } else {
     dutils::Error("StoppingPowerCalculator::GetMeasurement", __FILE__, __LINE__)
       << "invalid index " << index << ", valid options are [0, ) " << fEnergies.size();
   }
 }
TorrCgs() [1/2]
Double_t dragon::StoppingPowerCalculator::TorrCgs (Double_t torr) static
Convert pressure in torr to dyn/cm^2.
Parameters
torr Pressure in torr
Returns
Pressure in dyn/cm<sup>2</sup>
Definition at line 1979 of file RootAnalysis.cxx.
 {
   return 10 * torr * 101325 / 760.;
 }
TorrCgs() [2/2]
UDouble_t dragon::StoppingPowerCalculator::TorrCgs (UDouble_t torr) static
Convert pressure in torr to dyn/cm^2 (with uncertainty)
Parameters
torr Pressure in torr (with uncertainty)
Returns
Pressure in dyn/cm<sup>2</sup> (with uncertainty)
Definition at line 1987 of file RootAnalysis.cxx.
 {
   return 10. * torr * 101325. / 760.0;
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/utils/RootAnalysis.hxx
/Users/dragon/packages/dragon/analyzer/src/utils/RootAnalysis.cxx