DRAGON Analyzer: midas::Database Class Reference
midas::Database Class Reference
Generic database reading class.
#include <Database.hxx>
Public Member Functions
Database ()
Default constructor for ROOT I/O.
Database (const char *filename)
Determines online or offline mode.
Database (char *buf, int length)
Read from buffered XML data.
bool IsZombie () const
Tell the public if a zombie or not.
void Dump (std::ostream &strm) const
Dump odb contents to an output stream.
void Dump () const
Default dump to std::cout.
template<typename T >
bool ReadValue (const char *path, T &value) const
Read a single value.
int ReadArrayLength (const char *path) const
Read the length of an array.
template<typename T >
int ReadArray (const char *path, T *array, int length) const
Read an array.
void Print (const char *path) const
Print value of a parameter.
bool CheckPath (const char *path)
Check if a path exists.
ClassDef (midas::Database, MIDAS_XML_CLASS_VERSION)
Private Attributes
XML_POINTER_t fXml
Pointer to Xml reader (NULL if in 'online mode')
bool fIsOnline
Flag specifying online mode.
bool fIsZombie
Flag specifying 'zombie' status.
Detailed Description
Generic database reading class.
With this class, users can read data from either the ODB or from a saved XML (or .mid) file using a single structure. Whether to read from the ODB or a file is specified by the constructor argument, which is either the path to a file containing XML data, or "online" to read from the ODB.
Definition at line 42 of file Database.hxx.
Constructor & Destructor Documentation
Database() [1/2]
midas::Database::Database (const char * filename) inline
Determines online or offline mode.
Parameters
filename Name of the XML (or .mid) file from which to read data.
Note
Specifying "online" reads from the ODB if connected to an experiment.
Definition at line 70 of file Database.hxx.
References fIsOnline, fIsZombie, fXml, and midas::Odb::GetHandle().
                                  : fXml(0), fIsOnline(false), fIsZombie(false)
     {
       /*!
        * \param filename Name of the XML (or .mid) file from which to read
        *  data. \note Specifying "online" reads from the ODB if connected to an
        *  experiment.
        */
       if (strcmp(filename, "online")) {
         fXml.reset(new Xml(filename));
         if (fXml->IsZombie()) {
           fXml.reset(0);
           fIsZombie = true;
         }
       }
       else {
         fIsOnline = true;
         if (Odb::GetHandle() == 0)
           fIsZombie = true;
       }
       if (fIsZombie) {
         dragon::utils::Error("midas::Database::Database", __FILE__, __LINE__)
           << "Failed opening the database: \"" << filename << "\"";
       }
     }
Database() [2/2]
midas::Database::Database (char * buf, int length) inline
Read from buffered XML data.
Parameters
buf Buffer containing xml data.
length Size of the buffer in bytes
Definition at line 96 of file Database.hxx.
References fIsZombie, and fXml.
                                   : fXml(0), fIsOnline(false), fIsZombie(false)
     {
       /*!
        * \param buf Buffer containing xml data.
        * \param length Size of the buffer in bytes
        */
       fXml.reset(new Xml(buf, length));
       if (fXml->IsZombie()) {
         fXml.reset(0);
         fIsZombie = true;
       }
       if (fIsZombie) {
         dragon::utils::Error("midas::Database::Database", __FILE__, __LINE__)
           << "Failed parsing the XML data.";
       }
     }
Member Function Documentation
ReadArray()
template<typename T > int midas::Database::ReadArray (const char * path, T * array, int length) const inline
Read an array.
Parameters
[in] path Path ODB directory path of what is to be read
[out] array The value you want to read
[in] length Length of the array to be read
Template Parameters
T The type of the data in the array to be read
Returns
The length of the array that was read (0 if error)
Definition at line 164 of file Database.hxx.
References fIsOnline, fIsZombie, fXml, and midas::Odb::ReadArray().
Referenced by dragon::LiveTimeCalculator::CalculateRuntime(), dragon::utils::DsssdCalibrator::DsssdCalibrator(), dragon::RunParameters::read_data(), Sonik::Variables::set(), dragon::Bgo::Variables::set(), dragon::Dsssd::Variables::set(), dragon::IonChamber::Variables::set(), dragon::Mcp::Variables::set(), dragon::SurfaceBarrier::Variables::set(), dragon::NaI::Variables::set(), dragon::Scaler::Variables::set(), and dragon::Epics::Variables::set().
     {
       /*!
        * \param [in] path Path ODB directory path of what is to be read
        * \param [out] array The value you want to read
        * \param [in] length Length of the array to be read
        * \tparam T The type of the data in the array to be read
        * \returns The length of the array that was read (0 if error)
        */
       if(fIsZombie) return 0;
       if(fIsOnline) return Odb::ReadArray(path, array, length);
       else if (fXml.get()) {
         bool success;
         fXml->GetArray(path, length, array, &success);
         return length;
       }
       else return 0;
     }
ReadArrayLength()
int midas::Database::ReadArrayLength (const char * path) const inline
Read the length of an array.
Parameters
[in] path Path ODB directory path of what is to be read
Returns
The length of the array upon success, -1 upon failure.
Definition at line 151 of file Database.hxx.
References fIsOnline, fIsZombie, fXml, and midas::Odb::ReadArraySize().
Referenced by dragon::Epics::Variables::set().
     {
       /*!
        * \param [in] path Path ODB directory path of what is to be read
        * \returns The length of the array upon success, -1 upon failure.
        */
       if      (fIsZombie)  return -1;
       else if (fIsOnline)  return Odb::ReadArraySize(path);
       else if (fXml.get()) return fXml->GetArrayLength(path);
       else                 return -1;
     }
ReadValue()
template<typename T > bool midas::Database::ReadValue (const char * path, T & value) const inline
Read a single value.
Parameters
[in] path Path ODB directory path of what is to be read
[out] array The value you want to read
Template Parameters
T The type of the data to be read
Returns
true if read was successful, false otherwise
Definition at line 132 of file Database.hxx.
References fIsOnline, fIsZombie, and fXml.
Referenced by dragon::BeamNorm::CalculateRecoils(), dragon::LiveTimeCalculator::CalculateRuntime(), m2r::main_(), dragon::BeamNorm::ReadSbCounts(), rbdragon::MidasBuffer::RunStartTransition(), Sonik::Variables::set(), dragon::Dsssd::Variables::set(), dragon::Mcp::Variables::set(), dragon::Ge::Variables::set(), dragon::TdcChannel< MAX_HITS >::Variables::set(), dragon::Head::Variables::set(), dragon::Tail::Variables::set(), dragon::Coinc::Variables::set(), dragon::Head::set_variables(), and dragon::Tail::set_variables().
     {
       /*!
        * \param [in] path Path ODB directory path of what is to be read
        * \param [out] array The value you want to read
        * \tparam T The type of the data to be read
        * \returns true if read was successful, false otherwise
        */
       if(fIsZombie) return false;
       if (fIsOnline) return Odb::ReadValue(path, value);
       else if (fXml.get()) {
         bool success;
         fXml->GetValue(path, value, &success);
         return success;
       }
       else return false;
     }
The documentation for this class was generated from the following file:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/midas/Database.hxx