DRAGON Analyzer: dragon::Head Class Reference
dragon::Head Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Head ()
Initializes data values.
void reset ()
Sets all data values to vme::NONE or other defaults.
bool set_variables (const char *dbfile)
Reads all variable values from an database (file or online)
bool set_variables (const midas::Database *db)
Reads all variable values from a constructed database.
void unpack (const midas::Event &event)
Unpack raw data into VME modules.
void calculate ()
Calculate higher-level data for each detector, or across detectors.
Public Attributes
TMidas_EVENT_HEADER header
Midas event header.
vme::Io32 io32
IO32 FPGA.
vme::V792 v792
CAEN V792 QDC.
vme::V1190 v1190
CAEN V1190 TDC.
dragon::Bgo bgo
Bgo array.
TdcChannel< MAX_RF_HITS > trf
RF times.
double tcal0
Head [bgo] trigger time.
double tcalx
Crossover [tail] trigger time.
double tcal_rf
RF time.
Head::Variables variables
Variables instance.
Static Public Attributes
static const int MAX_RF_HITS = 5
Max number of RF hits to store.
Detailed Description
Collection of all head detectors and VME modules
Definition at line 527 of file Dragon.hxx.
Constructor & Destructor Documentation
Head()
dragon::Head::Head ()
Initializes data values.
Set bank names, resets data to default values
Definition at line 883 of file Dragon.cxx.
 {
   /*!
    * Set bank names, resets data to default values
    */
   reset();
 }
Member Function Documentation
calculate()
void dragon::Head::calculate ()
Calculate higher-level data for each detector, or across detectors.
This is where the raw data recorded in VME fields is mapped to a more abstract location in a detector class. This covers a wide range of parameter calculation, from, e.g. simply mapping ADC channels to corresponding (uncalibrated) detector signals, up to calculation of abstract physics quantities that depend on multiple calibrated detector signals.
In the specific implementation, the following are done:
Read BGO data and calculate (see dragon::Head::Bgo).
Read and calibrate "crossover" TDC channel.
Read and calibrate RF TDC channel.
Read and calibrate t0 (trigger) channel
Definition at line 960 of file Dragon.cxx.
References dragon::utils::channel_map(), and dragon::utils::linear_calibrate().
 {
   /*!
    * This is where the raw data recorded in VME fields is mapped to a more
    * abstract location in a detector class. This covers a wide range of parameter
    * calculation, from, e.g. simply mapping ADC channels to corresponding (uncalibrated)
    * detector signals, up to calculation of abstract physics quantities that depend on multiple
    * calibrated detector signals.
    *
    * In the specific implementation, the following are done:
    */
   /// - Read BGO data and calculate (see dragon::Head::Bgo).
   bgo.read_data(v792, v1190);
   bgo.calculate();
   trf.read_data(v1190);
   trf.calculate();
   /// - Read and calibrate "crossover" TDC channel.
   dutils::channel_map(tcalx, variables.xtdc.channel, v1190);
   dutils::linear_calibrate(tcalx, variables.xtdc);
   /// - Read and calibrate RF TDC channel.
   dutils::channel_map(tcal_rf, variables.rf_tdc.channel, v1190);
   dutils::linear_calibrate(tcal_rf, variables.rf_tdc);
   /// - Read and calibrate t0 (trigger) channel
   dutils::channel_map(tcal0, variables.tdc0.channel, v1190);
   dutils::linear_calibrate(tcal0, variables.tdc0);
 }
reset()
void dragon::Head::reset ()
Sets all data values to vme::NONE or other defaults.
Call reset() for all members that are classes, reset raw data to defaults.
Definition at line 891 of file Dragon.cxx.
References dragon::utils::reset_data().
 {
   /*!
    * Call reset() for all members that are classes, reset raw data to defaults.
    */
   const midas::Event::Header temp = { 0, 0, 0, 0, 0 };
   header = temp;
   io32.reset();
   v792.reset();
   v1190.reset();
   bgo.reset();
   trf.reset();
   dutils::reset_data(tcalx, tcal0, tcal_rf);
 }
set_variables() [1/2]
bool dragon::Head::set_variables (const char * dbfile)
Reads all variable values from an database (file or online)
Parameters
[in] dbfile Name of the XML database file
Note
Passing "online" looks at the online ODB.
Definition at line 906 of file Dragon.cxx.
 {
   /*!
    * \param [in] dbfile Name of the XML database file
    * \note Passing \c "online" looks at the online ODB.
    */
   return do_setv(this, dbfile);
 }
set_variables() [2/2]
bool dragon::Head::set_variables (const midas::Database * db)
Reads all variable values from a constructed database.
Parameters
[in] odb_file Pointer to the database from which to read the variables.
Definition at line 915 of file Dragon.cxx.
References midas::Database::ReadValue().
 {
   /*!
    * \param [in] odb_file Pointer to the database from which to read the variables.
    */
   bool success = check_db(db, "dragon::Head::set_variables");
   if(success) success = bgo.variables.set(db);
   if(success) success = trf.variables.set(db, "/dragon/head/variables/rf_tdc");
   if(success) success = this->variables.set(db);
   if(success) {
     dragon::utils::ChangeErrorIgnore dummy(9001);
     int period = 0;
     if(db->ReadValue("/dragon/errormessage/v1190/period", period))
       v1190.fMessagePeriod = period;
     else
       v1190.fMessagePeriod = 0;
   }
   return success;
 }
unpack()
void dragon::Head::unpack (const midas::Event & event)
Unpack raw data into VME modules.
Parameters
[in] event Reference to a Midas event structure
Here is where the low-level work is done to take bitpacked data read directly from a MIDAS file and convert it into the corresponding measurement values of various ADC modules.
In the specific case of unpacking the dragon::Head VME data, we delegate the work to the unpack() routines of the relevant vme::* classes.
Note
Recompile with report = true to print warning messages for missing banks
Definition at line 938 of file Dragon.cxx.
 {
   /*!
    * \param [in] event Reference to a Midas event structure
    *
    * Here is where the low-level work is done to take bitpacked data read directly
    * from a MIDAS file and convert it into the corresponding measurement values
    * of various ADC modules.
    *
    * In the specific case of unpacking the dragon::Head VME data, we delegate
    * the work to the unpack() routines of the relevant vme::* classes.
    *
    * \note Recompile with <c> report = true </c> to print warning messages
    *  for missing banks
    */
   const bool report = true;
   io32.unpack (event, variables.bk_io32, report);
   v792.unpack (event, variables.bk_adc , report);
   v1190.unpack(event, variables.bk_tdc,  report);
   event.CopyHeader(header);
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx