DRAGON Analyzer: dragon::RunParameters Class Reference
dragon::RunParameters Class Reference
#include <Dragon.hxx>
Public Member Functions
RunParameters ()
Constructor, calls reset()
void reset ()
Sets all data to defaults.
bool read_data (const midas::Database *db)
Reads data from the ODB or a midas file.
Public Attributes
double run_start [MAX_FRONTENDS]
Run start time from the tsc (in seconds)
double run_stop [MAX_FRONTENDS]
Run stop time from the tsc (in seconds)
double trigger_start [MAX_FRONTENDS]
Trigger start time from the tsc (in seconds)
double trigger_stop [MAX_FRONTENDS]
Trigger stop time from the tsc (in seconds)
Static Public Attributes
static const int MAX_FRONTENDS = 2
Detailed Description
Global run parameters
Definition at line 43 of file Dragon.hxx.
Constructor & Destructor Documentation
RunParameters()
dragon::RunParameters::RunParameters ()
Constructor, calls reset()
::
Definition at line 116 of file Dragon.cxx.
References reset().
 {
   /// ::
   reset();
 }
Member Function Documentation
read_data()
bool dragon::RunParameters::read_data (const midas::Database * db)
Reads data from the ODB or a midas file.
::
Definition at line 131 of file Dragon.cxx.
References midas::Database::IsZombie(), and midas::Database::ReadArray().
 {
   /// ::
   if(db == 0 || db->IsZombie()) {
     dutils::Error("dragon::RunParameters::read_data", __FILE__, __LINE__)
       << "Zombie database";
     return false;
   }
   bool success = true;
   if(success) success = db->ReadArray("/Experiment/Run Parameters/TSC_RunStart", run_start, MAX_FRONTENDS);
   if(success) success = db->ReadArray("/Experiment/Run Parameters/TSC_RunStop", run_stop, MAX_FRONTENDS);
   if(success) success = db->ReadArray("/Experiment/Run Parameters/TSC_TriggerStart", trigger_start, MAX_FRONTENDS);
   if(success) success = db->ReadArray("/Experiment/Run Parameters/TSC_TriggerStop", trigger_stop, MAX_FRONTENDS);
   if(!success) {
     dutils::Error("dragon::RunParameters::read_data", __FILE__, __LINE__)
       << "Failed reading one of the ODB parameters.";
   }
   return success;
 }
reset()
void dragon::RunParameters::reset ()
Sets all data to defaults.
::
Definition at line 122 of file Dragon.cxx.
Referenced by RunParameters().
 {
   /// ::
   double* parrays[4] = { run_start, run_stop, trigger_start, trigger_stop };
   for(int i=0; i< 4; ++i) {
     std::fill(parrays[i], parrays[i] + MAX_FRONTENDS, 0.);
   }
 }
Member Data Documentation
run_start
double dragon::RunParameters::run_start[MAX_FRONTENDS]
Run start time from the tsc (in seconds)
[0]: head, [1]: tail
Definition at line 57 of file Dragon.hxx.
run_stop
double dragon::RunParameters::run_stop[MAX_FRONTENDS]
Run stop time from the tsc (in seconds)
[0]: head, [1]: tail
Definition at line 60 of file Dragon.hxx.
trigger_start
double dragon::RunParameters::trigger_start[MAX_FRONTENDS]
Trigger start time from the tsc (in seconds)
[0]: head, [1]: tail
Definition at line 63 of file Dragon.hxx.
trigger_stop
double dragon::RunParameters::trigger_stop[MAX_FRONTENDS]
Trigger stop time from the tsc (in seconds)
[0]: head, [1]: tail
Definition at line 66 of file Dragon.hxx.
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx