DRAGON Analyzer: dragon::TdcChannel< MAX_HITS > Class Template Reference
dragon::TdcChannel< MAX_HITS > Class Template Reference
Class for tdc stuff.
#include <Dragon.hxx>
Classes
class Variables
TcdChannel variables.
Public Member Functions
TdcChannel ()
Sets data to defaults.
void reset ()
Sets data to dragon::NO_DATA.
void read_data (const vme::V1190 &tdc)
Reads data from TDC module.
void calculate ()
Calibrates TDC channels.
double get_tof (double other, int hitnum, bool edge=vme::V1190::LEADING)
Calculate TOF to another TDC hit.
Public Attributes
double leading [MAX_HITS]
Array of leading edge hits (calibrated)
double trailing [MAX_HITS]
Array of trailing edge hits (calibrated)
Variables variables
Detailed Description
template<int MAX_HITS>
class dragon::TdcChannel< MAX_HITS >
Class for tdc stuff.
Stores values of multiple leading and trailing edge hits
Template Parameters
MAX_HITS Maximum number of hits desired for storage
Definition at line 458 of file Dragon.hxx.
Constructor & Destructor Documentation
template<int MAX_HITS> dragon::TdcChannel< MAX_HITS >::TdcChannel () inline
Sets data to defaults.
::
Definition at line 1010 of file Dragon.hxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
template<int MAX_HITS> void dragon::TdcChannel< MAX_HITS >::calculate () inline
Calibrates TDC channels.
::
Definition at line 1035 of file Dragon.hxx.
References dragon::utils::linear_calibrate().
Referenced by Sonik::calculate().
 {
   /// ::
   for (int i=0; i< MAX_HITS; ++i) {
     dragon::utils::linear_calibrate(leading[i], variables.tdc);
     dragon::utils::linear_calibrate(trailing[i], variables.tdc);
   }
 }
template<int MAX_HITS> double dragon::TdcChannel< MAX_HITS >::get_tof (double other, int hitnum, bool edge = vme::V1190::LEADING) inline
Calculate TOF to another TDC hit.
Parameters
other Value of the other TDC channel for TOF calculation
hitnum Desired hit number
edge leading (0) or trailing (1) edge
Returns
this - other (time difference) if hitnum is vald; -1 otherwise
Definition at line 1045 of file Dragon.hxx.
Referenced by Sonik::calculate().
 {
   /// \param other Value of the other TDC channel for TOF calculation
   /// \param hitnum Desired hit number
   /// \param edge leading (0) or trailing (1) edge
   /// \returns `this - other` (time difference) if hitnum is vald; -1 otherwise
   if((unsigned)hitnum >= MAX_HITS) return -1;
   return edge == vme::V1190::LEADING ?
     leading[hitnum] - other : trailing[hitnum] - other;
 }
template<int MAX_HITS> void dragon::TdcChannel< MAX_HITS >::read_data (const vme::V1190 & tdc) inline
Reads data from TDC module.
::
Definition at line 1025 of file Dragon.hxx.
References vme::V1190::get_leading(), and vme::V1190::get_trailing().
Referenced by Sonik::read_data().
 {
   /// ::
   for (int i=0; i< MAX_HITS; ++i) {
     leading[i] = tdc.get_leading(variables.tdc.channel, i);
     trailing[i] = tdc.get_trailing(variables.tdc.channel, i);
   }
 }
template<int MAX_HITS> void dragon::TdcChannel< MAX_HITS >::reset () inline
Sets data to dragon::NO_DATA.
::
Definition at line 1017 of file Dragon.hxx.
References dragon::utils::reset_array().
Referenced by Sonik::reset().
 {
   /// ::
   dragon::utils::reset_array(MAX_HITS, leading);
   dragon::utils::reset_array(MAX_HITS, trailing);
 }
The documentation for this class was generated from the following file:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx