DRAGON Analyzer: Sonik Class Reference
Sonik Class Reference
#include <Sonik.hxx>
Classes
class Variables
Public Member Functions
Sonik ()
Constructor, initialize data.
~Sonik ()
Destructor.
void reset ()
Reset all data to VME::none.
void read_data (const vme::V785 adcs[], const vme::V1190 &tdc)
Read data from vme modules.
void calculate ()
Performs energy and time calibrations.
bool set_variables (midas::Database *db)
Set variables.
Public Attributes
double ecal [MAX_CHANNELS]
Calibrated energy signals.
double ehit
Energy signal of the hit detector (the one w/ highest energy)
uint32_t hit
Index of the hit (highest-energy) detector.
double thit
Calibrated time signal of the trigger (OR of all detectors)
double rf_tof
Time-of-flights.
dragon::TdcChannel< 5 > trf
RF times.
double tcal0
Trigger [tail] tdc value.
Sonik::Variables variables
Instance of Dsssd::Variables.
Static Public Attributes
static const int MAX_CHANNELS = 32
Number of channels.
Detailed Description
SONIK Detectors
Definition at line 20 of file Sonik.hxx.
Constructor & Destructor Documentation
Sonik()
Sonik::Sonik ()
Constructor, initialize data.
::
Definition at line 65 of file Sonik.cxx.
References reset().
             :
   variables()
 {
   /// ::
   reset();
 }
~Sonik()
Sonik::~Sonik ()
Destructor.
::
Definition at line 72 of file Sonik.cxx.
 {
   /// ::
   ;
 }
Member Function Documentation
calculate()
void Sonik::calculate ()
Performs energy and time calibrations.
Does a linear transformation on each element in this->ecal[] using the slopes and offsets from variables.adc_slope and variables.adc_offset, respectively. Also calibrates the TDC signal; calculates ehit, hit.
Definition at line 103 of file Sonik.cxx.
References Sonik::Variables::adc, dragon::TdcChannel< MAX_HITS >::calculate(), ecal, ehit, dragon::TdcChannel< MAX_HITS >::get_tof(), hit, dragon::utils::is_valid_any(), dragon::utils::linear_calibrate(), MAX_CHANNELS, rf_tof, tcal0, Sonik::Variables::tdc, Sonik::Variables::tdc0, thit, trf, and variables.
Referenced by m2r::main_().
 {
   /*!
    * Does a linear transformation on each element in \c this->ecal[] using the slopes and offsets
    * from variables.adc_slope and variables.adc_offset, respectively. Also calibrates the TDC
    * signal; calculates ehit, hit.
    */
   dutils::linear_calibrate(ecal, MAX_CHANNELS, variables.adc);
   dutils::linear_calibrate(thit, variables.tdc);
   dutils::linear_calibrate(tcal0, variables.tdc0);
   trf.calculate();
   rf_tof = trf.get_tof(tcal0, 1, vme::V1190::TRAILING);
   if(dutils::is_valid_any(ecal, MAX_CHANNELS)) {
     const double* const pmax_front = std::max_element(ecal, ecal+MAX_CHANNELS);
     ehit = *pmax_front;
     hit  = pmax_front - ecal;
   }
 }
read_data()
void Sonik::read_data (const vme::V785 adcs[], const vme::V1190 & tdc)
Read data from vme modules.
Copies adc data into this->ecal[] with channel and module mapping taken from variables.adc.channel and variables.adc.modules
Delegates work to dutils::channel_map()
Parameters
[in] adcs Array of vme::V785 adc modules from which data can be taken
[in] tdc vme::V1190 tdc module from which data can be read
Definition at line 87 of file Sonik.cxx.
References Sonik::Variables::adc, dragon::utils::AdcVariables< N >::channel, dragon::utils::TdcVariables< 1 >::channel, dragon::utils::channel_map(), ecal, MAX_CHANNELS, dragon::utils::AdcVariables< N >::module, dragon::TdcChannel< MAX_HITS >::read_data(), tcal0, Sonik::Variables::tdc, Sonik::Variables::tdc0, thit, trf, and variables.
Referenced by m2r::main_().
 {
   /*!
    * Copies adc data into \c this->ecal[] with channel and module mapping taken
    * from variables.adc.channel and variables.adc.modules
    *
    * Delegates work to dutils::channel_map()
    * \param [in] adcs Array of vme::V785 adc modules from which data can be taken
    * \param [in] tdc vme::V1190 tdc module from which data can be read
    */
   dutils::channel_map(ecal, MAX_CHANNELS, variables.adc.channel, variables.adc.module, adcs);
   dutils::channel_map(thit, variables.tdc.channel, tdc);
   dutils::channel_map(tcal0, variables.tdc0.channel, tdc);
   trf.read_data(tdc);
 }
reset()
void Sonik::reset ()
Reset all data to VME::none.
::
Definition at line 78 of file Sonik.cxx.
References ecal, ehit, hit, MAX_CHANNELS, dragon::TdcChannel< MAX_HITS >::reset(), dragon::utils::reset_array(), dragon::utils::reset_data(), rf_tof, tcal0, thit, and trf.
Referenced by m2r::main_(), and Sonik().
 {
   /// ::
   trf.reset();
   dutils::reset_data(ehit, hit, thit, rf_tof, tcal0);
   dutils::reset_array(MAX_CHANNELS, ecal);
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Sonik.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Sonik.cxx