DRAGON Analyzer: dragon::Ge Class Reference
dragon::Ge Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Ge ()
Constructor, initialize data.
void reset ()
Reset all data to vme::NONE.
void read_data (const vme::V785 adcs[], const vme::V1190 &)
Read event data from the ADC.
void calculate ()
Do energy calibrations, pedestal subtractions.
Public Attributes
double ecal
Calibrated energy signal.
Ge::Variables variables
Variables instance.
Detailed Description
Germanium (Ge) detector
Definition at line 412 of file Dragon.hxx.
Constructor & Destructor Documentation
Ge()
dragon::Ge::Ge ()
Constructor, initialize data.
::
Definition at line 770 of file Dragon.cxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::Ge::calculate ()
Do energy calibrations, pedestal subtractions.
Calibration of energies
Definition at line 794 of file Dragon.cxx.
References dragon::utils::linear_calibrate().
 {
   /// Calibration of energies
   dutils::linear_calibrate(ecal, variables.adc);
 }
read_data()
void dragon::Ge::read_data (const vme::V785 adcs[], const vme::V1190 &)
Read event data from the ADC.
Copies adc data into this->ecal[] with channel and module mapping taken from variables.adc.channel and variables.adc.module
Delegates work to dutils::channel_map()
Parameters
[in] adcs Array of vme::V785 adc modules from which data can be taken
Definition at line 782 of file Dragon.cxx.
References dragon::utils::channel_map().
 {
   /*!
    * Copies adc data into \c this->ecal[] with channel and module mapping taken
    * from variables.adc.channel and variables.adc.module
    *
    * Delegates work to dutils::channel_map()
    * \param [in] adcs Array of vme::V785 adc modules from which data can be taken
    */
   dutils::channel_map(ecal, variables.adc.channel, variables.adc.module, adcs);
 }
reset()
void dragon::Ge::reset ()
Reset all data to vme::NONE.
::
Definition at line 776 of file Dragon.cxx.
References dragon::utils::reset_data().
 {
   /// ::
   dutils::reset_data(ecal);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx