DRAGON Analyzer: dragon::Constants Class Reference
dragon::Constants Class Reference
Class containing useful physical constants as static members.
#include <Constants.hxx>
Static Public Member Functions
static double Avogadro ()
static double AvogadroUnc ()
static double AMU ()
static double AMUUnc ()
static double AMUkg ()
static double AMUkgUnc ()
static double Alpha ()
static double AlphaUnc ()
static double BohrR ()
static double BohrRUnc ()
static double Boltzmann ()
static double BoltzUnc ()
static double CMD1 ()
static double CMD1Unc ()
static double ElectronCharge ()
static double ElectronChargeUnc ()
static double QeSquared ()
static double ElectronMass ()
static double EMassUnc ()
static double Eps0 ()
static double HbarC ()
static double HbarCUnc ()
static double Ldra ()
static double LdraUnc ()
static double Lmcp ()
static double LmcpUnc ()
static double Mu0 ()
static double Losch ()
static double LoschUnc ()
static double T_std ()
static double P_std ()
Detailed Description
Class containing useful physical constants as static members.
Example use:
std::cout << "The electron charge in coulombs is: " << dragon::Constants::ElectronCharge() << "\n";
Attention
Future developers: if more constnats are needed, please extend this file rather than hard-coding in your source files.
Note
All values taken from 2014 CODATA values: http://physics.nist.gov/cuu/Constants/index.html These values should be updated in 2019 when the CODATA values are adjusted to adhere to the revision of the International System of Units (SI).
Todo:
consider adding functionality (similar to TAtomicMassTable::ParseFile) to read and parse a text file containing physical constant data.
Definition at line 33 of file Constants.hxx.
Member Function Documentation
static double dragon::Constants::Alpha () inline static
fine structure constant 7.2973525664(17)e-3
Definition at line 62 of file Constants.hxx.
Referenced by QeSquared().
 { return 7.2973525664e-3; }
static double dragon::Constants::AlphaUnc () inline static
fine structure constant uncertainty
Definition at line 66 of file Constants.hxx.
 { return 0.0000000017e-3; }
static double dragon::Constants::AMU () inline static
atomic mass unit (energy equivalent) 931.4940954(57) MeV c-2
Definition at line 46 of file Constants.hxx.
Referenced by dragon::StoppingPowerCalculator::CalculateEnergy(), dragon::ResonanceStrengthCalculator::CalculateWavelength(), dragon::LabCM::GetM1(), dragon::LabCM::GetM2(), dragon::LabCM::GetV2beam(), dragon::LabCM::GetV2target(), dragon::LabCM::SetM1(), dragon::LabCM::SetM2(), dragon::LabCM::SetV2beam(), and dragon::LabCM::SetV2target().
 { return 931.4940954; }
static double dragon::Constants::AMUkg () inline static
atomic mass unit 1.660539040(20) kg
Definition at line 54 of file Constants.hxx.
 { return 1.660538921e-27; }
static double dragon::Constants::AMUkgUnc () inline static
atomic mass unit uncertainty (in kg)
Definition at line 58 of file Constants.hxx.
 { return 0.000000020e-27; }
static double dragon::Constants::AMUUnc () inline static
atomic mass unit (energy equivalent) uncertainty (in MeV c-2)
Definition at line 50 of file Constants.hxx.
Referenced by dragon::StoppingPowerCalculator::CalculateEnergy().
 { return 0.0000057; }
static double dragon::Constants::Avogadro () inline static
Avogadro's number 6.022140857(74)e23 mol-1
Definition at line 38 of file Constants.hxx.
 { return 6.022140857e23; }
static double dragon::Constants::AvogadroUnc () inline static
Avogadro uncertainty (mol-1)
Definition at line 42 of file Constants.hxx.
 { return 0.000000074e23; }
static double dragon::Constants::BohrR () inline static
Bohr radius in m 0.52917721067(12)
Definition at line 70 of file Constants.hxx.
 { return 0.52917721067e-10; }
static double dragon::Constants::BohrRUnc () inline static
Bohr radius uncertainty
Definition at line 74 of file Constants.hxx.
 { return 0.00000000012e-10; }
static double dragon::Constants::Boltzmann () inline static
Boltzmann constant 8.6173303(50)e-5 eV K-1
Definition at line 78 of file Constants.hxx.
 { return 8.6173303e-5; }
static double dragon::Constants::BoltzUnc () inline static
Boltzmann constant uncertainty
Definition at line 82 of file Constants.hxx.
 { return 0.0000050e-5; }
static double dragon::Constants::CMD1 () inline static
DRAGON MD1 constant 48.15 MeV / T2
Definition at line 86 of file Constants.hxx.
 { return 48.15; }
static double dragon::Constants::CMD1Unc () inline static
Absolute uncertainty of DRAGON MD1 constant in MeV / T2
Definition at line 90 of file Constants.hxx.
 { return 0.072225; }
static double dragon::Constants::ElectronCharge () inline static
Electron charge 1.6021766208(98)e-19 A*s
Note
Implemented in ROOT's TMath::Qe(), but its value is outdated.
Definition at line 94 of file Constants.hxx.
 { return 1.6021766208e-19; }
static double dragon::Constants::ElectronChargeUnc () inline static
Electron charge uncertainty
Definition at line 98 of file Constants.hxx.
 { return 0.0000000098e-19; }
static double dragon::Constants::ElectronMass () inline static
Electron mass in MeV / c2 0.5109989461(31)
Definition at line 106 of file Constants.hxx.
 { return 0.5109989461; }
static double dragon::Constants::EMassUnc () inline static
Electron mass uncertainty
Definition at line 110 of file Constants.hxx.
 { return 0.0000000031; }
static double dragon::Constants::Eps0 () inline static
Vacuum permittivity F*m-1
Definition at line 114 of file Constants.hxx.
References Mu0().
 { return 1 / ( Mu0()*pow(TMath::C(),2) ); }
static double dragon::Constants::HbarC () inline static
hbar*c 197.3269788(12) MeV*fm
Definition at line 118 of file Constants.hxx.
Referenced by dragon::ResonanceStrengthCalculator::CalculateWavelength(), and QeSquared().
 { return 197.3269788; }
static double dragon::Constants::HbarCUnc () inline static
Hbar*c uncertainty
Definition at line 122 of file Constants.hxx.
 { return 0.0000012; }
static double dragon::Constants::Ldra () inline static
Distance between DRAGON's gas target and focal plane m
Definition at line 126 of file Constants.hxx.
Referenced by dragon::Kin2Body::Init().
 { return 21.0; }
static double dragon::Constants::LdraUnc () inline static
Uncertainty in distance between DRAGON's gas target and focal plane m
Attention
this is just a guess.
Definition at line 131 of file Constants.hxx.
 { return 0.3; }
static double dragon::Constants::Lmcp () inline static
Distance between DRAGON's MCP foils cm
Definition at line 135 of file Constants.hxx.
Referenced by dragon::Kin2Body::Init().
 { return 0.59; }
static double dragon::Constants::LmcpUnc () inline static
Uncertainty in distance between DRAGON's MCP foils m
Definition at line 139 of file Constants.hxx.
 { return 0.005; }
static double dragon::Constants::Losch () inline static
Loschmidt constant at 273.15 K and 101.325 kPa 2.6867811(15)e19 cm-3
Definition at line 147 of file Constants.hxx.
 { return 2.6867811e19; }
static double dragon::Constants::LoschUnc () inline static
Loschmidt constant uncertainty
Definition at line 151 of file Constants.hxx.
 { return 0.0000015; }
static double dragon::Constants::Mu0 () inline static
vacuum permeability N*A-2
Definition at line 143 of file Constants.hxx.
Referenced by Eps0().
 { return 4*TMath::Pi()*1e-7; }
static double dragon::Constants::P_std () inline static
standard atm in Torr
Definition at line 159 of file Constants.hxx.
 { return 760; }
static double dragon::Constants::QeSquared () inline static
Electron charge squared in MeV*fm
Definition at line 102 of file Constants.hxx.
References Alpha(), and HbarC().
 { return Alpha()*HbarC(); }
static double dragon::Constants::T_std () inline static
NIST normal temperature in K
Definition at line 155 of file Constants.hxx.
 { return 293.15; }
The documentation for this class was generated from the following file:
/Users/dragon/packages/dragon/analyzer/src/utils/Constants.hxx