DRAGON Analyzer: dragon::RossumData Class Reference
dragon::RossumData Class Reference
Class to extract data from rossum output files.
#include <RootAnalysis.hxx>
Public Member Functions
RossumData ()
Empty constructor.
RossumData (const char *name, const char *filename)
Opens a rossumData file.
~RossumData ()
Free memry allocated to TTrees.
void CloseFile ()
Close rossumData file.
TTree * GetTree (Int_t runnum, const char *time=0) const
Return the tree containing rossum data for a given run.
void ListTrees () const
List available trees.
std::vector< Int_t > & GetRunsVector () const
List available trees.
Bool_t OpenFile (const char *name, Bool_t parse=kTRUE)
Open a rossumData file.
Bool_t ParseFile ()
Parse the relevant information from a rossumData file.
Bool_t IsFileOpen ()
Check if a rossumData file is currently open.
UDouble_t AverageCurrent (Int_t run, Int_t cup, Int_t iteration=0, Double_t skipBegin=10, Double_t skipEnd=5)
Get the average beam current from a set of cup readings.
TGraph * PlotTransmission (Int_t *runs, Int_t nruns)
Plot FC4 / FC1 for a series of runs.
Private Types
typedef std::multimap< Int_t, std::pair< TTree *, std::string > > TreeMap_t
Private Member Functions
void SetCups ()
TTree * MakeTree ()
Create a ROOT tree of rossum data.
RossumData (const RossumData &)
RossumData & operator= (const RossumData &)
ClassDef (RossumData, 1)
Static Private Member Functions
static TTree * GetTree_ (TreeMap_t::const_iterator &it)
static TTree * GetTree_ (TreeMap_t::iterator &it)
static std::string GetTime_ (TreeMap_t::const_iterator &it)
static std::string GetTime_ (TreeMap_t::iterator &it)
Private Attributes
dragon::utils::AutoPtr< std::ifstream > fFile
TreeMap_t fTrees
std::map< std::string, Int_t > fWhichCup
Int_t fCup
Int_t fIteration
Double_t fTime
Double_t fCurrent
Detailed Description
Class to extract data from rossum output files.
This class facilitates extraction of data saved into *.rossumData files by the DRAGON "autopilot" program rossum. For each separate rossum reading, the class generates a ROOT tree containig the current, time and cup information as branches. These trees can be identified either by the run number of the run started directly after the cup readings were taken, or they can be identified by the timestamp corresponding to when the rossum query was started. Note that in the case of rossum readings that do not precede a run start, the timestamp is the only valid means of identification.
Here is an example showing some of the class's more useful features:
dragon::RossumData rossumData("rossumData", "/path/to/rossum/data/file/some_beam.rossumData");
// The above line constructs a dragon::RossumData instance to read information from the specified file
rossumData.ListTrees(); // get a listing of all trees parsed from the file
TTree* tree = rossumData.GetTree(1000); // get a pointer to the tree preceding run 1000
tree->Draw("current:time", "", "L"); // draw all cup readings vs. time, for the query preceding run 1000
tree->Draw("current:time", "cup == 0", ""); // only draw FC4 readings [see AverageCurrent() for more about the cup id]
tree->Draw("current:time", "cup == 0 && iteration == 0", ""); // only draw the first iteration of FC4 readings
rossumData.AverageCurrent(1000, 0, 0).Print(); // print the average current in the first FC4 iteration
rossumData.AverageCurrent(1000, 1, 0).Print(); // print the average current in the first FC1 iteration
Definition at line 202 of file RootAnalysis.hxx.
Constructor & Destructor Documentation
RossumData() [1/2]
dragon::RossumData::RossumData ()
Empty constructor.
Default Ctor.
Definition at line 487 of file RootAnalysis.cxx.
                             :
   fFile(0)
 {
   SetCups();
 }
RossumData() [2/2]
dragon::RossumData::RossumData (const char * name, const char * filename)
Opens a rossumData file.
Ctor.
Definition at line 495 of file RootAnalysis.cxx.
References CloseFile(), and OpenFile().
                                                                   :
   fFile(0)
 {
   SetNameTitle(name, filename);
   SetCups();
   bool opened = OpenFile(filename, kTRUE);
   if(!opened) CloseFile();
 }
~RossumData()
dragon::RossumData::~RossumData ()
Free memry allocated to TTrees.
Dtor.
Definition at line 506 of file RootAnalysis.cxx.
 {
   for(TreeMap_t::iterator it = fTrees.begin(); it != fTrees.end(); ++it)
     if(GetTree_(it)) GetTree_(it)->Delete();
 }
Member Function Documentation
AverageCurrent()
UDouble_t dragon::RossumData::AverageCurrent (Int_t run, Int_t cup, Int_t iteration = 0, Double_t skipBegin = 10, Double_t skipEnd = 5)
Get the average beam current from a set of cup readings.
Calculate average current for a given cup reading and cup
Parameters
run Run number from which to get cup readings; this will look at the readings just before starting the specified run number
cup Specifies the farady cup from which to read, in order of upstream -> downstream:
0 : FC4
1 : FC1
2 : FCCH
3 : FCM
4 : FCF
iteration If more than one cup reading was taken, specifices which reading to take the average of (0 == first iteration).
skipBegin Length of time in seconds to skip at the beginning of the cup readings
skipEnd Length of time in seconds to skip at the end of the cup readings
Returns
Average current value for the parameters specified. This is returned as a class that holds both the nominal average value and the 1-sigma error. The 1-sigma error is calculated as the standard deviation of each individual cup reading over the specified duration. Note that to see the mean & error as part of a ROOT session, you can do
rossumData->AverageCurrent(1000, 0, 0)->Print();
Definition at line 708 of file RootAnalysis.cxx.
References dragon::utils::calculate_mean(), and dragon::utils::calculate_stddev().
 {
   TTree* tree = GetTree(run);
   if(!tree) {
     utils::Error("RossumData::AverageCurrent", __FILE__, __LINE__)
       << "Invalid run " << run;
     return UDouble_t(0);
   }
   Double_t time_, current_;
   Int_t cup_, iteration_, success;
   success = tree->SetBranchAddress("current", &current_);
   success = tree->SetBranchAddress("time", &time_);
   success = tree->SetBranchAddress("cup", &cup_);
   success = tree->SetBranchAddress("iteration", &iteration_);
   if(success) {
     utils::Error("RossumData::AverageCurrent", __FILE__, __LINE__)
       << "Failure to set branch addresses";
     return UDouble_t(0);
   }
   AutoResetBranchAddresses Rst_(tree);
   Double_t t0 = -1;
   std::vector<Double_t> current, time;
   for(Long64_t entry = 0; entry< tree->GetEntries(); ++entry) {
     tree->GetEntry(entry);
     if(cup_ != cup || iteration_ != iteration)
       continue; // failed cut
     assert(time_ >= 0);
     if(t0 < 0) t0 = time_;
     if(time_ - t0 > skipBegin) {
       if(!time.empty() && !(time_ >= time.back())) {
         utils::Error("RossumData::AverageCurrent", __FILE__, __LINE__)
           << "Non sequential current readings: " << "this, last = "
           << time_ << ", " << time.back() << "\n";
         return UDouble_t(0, 0);
       }
       current.push_back(current_);
       time.push_back(time_);
     }
   }
   // Find last time
   const std::vector<Double_t>::iterator::difference_type diffLast =
     std::lower_bound(time.begin(), time.end(), time.back() - skipEnd,
                      std::less_equal<Double_t>()) - time.begin();
   const std::vector<Double_t>::iterator lastCurrent =
     current.begin() + diffLast;
   Double_t avg = utils::calculate_mean(current.begin(), lastCurrent);
   Double_t stddev = utils::calculate_stddev(current.begin(), lastCurrent, avg);
   return UDouble_t(avg, stddev);
 }
OpenFile()
Bool_t dragon::RossumData::OpenFile (const char * filename, Bool_t parse = kTRUE)
Open a rossumData file.
Parameters
filename Path to the rossum file
parse If true, go ahead and attempt parsing the specified rossum file, if false, a separate call to ParseFile() will be needed.
Definition at line 532 of file RootAnalysis.cxx.
Referenced by RossumData().
 {
   TString filename2 = filename;
   Bool_t expand = gSystem->ExpandPathName(filename2);
   if(!expand)
     fFile.reset(new std::ifstream(filename2));
   else
     std::cerr << "Invalid file: " << filename2 << "\n";
   Bool_t retval = fFile.get() && fFile->good();
   if(!retval) CloseFile();
   else if(parse) ParseFile();
   return retval;
 }
ParseFile()
Bool_t dragon::RossumData::ParseFile ()
Parse the relevant information from a rossumData file.
Parse rossum data (*.rossumdata) file.
Definition at line 560 of file RootAnalysis.cxx.
 {
   if(!fFile.get()) {
     dutils::Error("RossumData::ParseFile", __FILE__, __LINE__)
       << "No rossum data file open.";
     return kFALSE;
   }
   Int_t runnum = 0;
   Bool_t retval = kTRUE;
   fFile->seekg(0);
   while (1) {
     std::string line0;
     std::getline(*fFile, line0);
     if(!fFile->good())
       break;
     if(line0.substr(0, 5) == "START") {
       std::string strTime = "Thu Jan  1 00:00:00 1970";
       size_t posTime = line0.rfind("\t");
       if(posTime+1 < line0.size()) strTime = line0.substr(posTime+1);
       TTree* tree = MakeTree();
       AutoResetBranchAddresses Rst_(tree);
       tree->SetDirectory(0);
       std::map<Int_t, Int_t> cupIteration;
       Bool_t fullRun = kFALSE;
       while(1) {
         std::getline(*fFile, line0);
         if(!fFile->good())
           break;
         else if(line0.substr(0, 4) == "STOP")
           break;
         else if(line0.substr(0, 5) == "begin") {
           runnum = 0;
           size_t curpos = line0.find("Current");
           if(curpos > line0.size()) {
             dutils::Error("RossumData::ParseFile", __FILE__, __LINE__)
               << "could not parse cup name from line: " << line0;
             retval = kFALSE;
             continue;
           }
           std::string which = line0.substr(6, curpos-6);
           std::map<std::string, Int_t>::iterator itWhich = fWhichCup.find(which);
           if(itWhich == fWhichCup.end()) {
             dutils::Error("RossumData::ParseFile", __FILE__, __LINE__)
               << "could not parse cup name from line: " << line0;
             retval = kFALSE;
             continue;
           }
           {
             fCup = itWhich->second;
             std::map<Int_t, Int_t>::iterator itCupIteration = cupIteration.find(fCup);
             if(itCupIteration == cupIteration.end())
               cupIteration.insert(std::make_pair(fCup, 0));
             else
               ++(itCupIteration->second);
             itCupIteration = cupIteration.find(fCup);
             fIteration = itCupIteration->second;
           }
           while(1) {
             std::getline(*fFile, line0);
             TString line(line0);
             if(!fFile->good())
               break;
             else if(line.Contains("end"))
               break;
             else {
               std::auto_ptr<TObjArray> tok (line.Tokenize("\t"));
               if(!tok.get() || tok->GetEntries() != 2) {
                 {
                   dutils::Error err("RossumData::ParseFile", __FILE__, __LINE__);
                   err << "invalid current read line: " << line;
                   if(tok.get())
                     err << " : ntokens == " << tok->GetEntries() << "\n";
                   else
                     err << " : tok.get() == 0\n";
                 }
                 retval = kFALSE;
                 continue;
               }
               fTime =    ((TObjString*)tok->At(0))->GetString().Atof();
               fCurrent = ((TObjString*)tok->At(1))->GetString().Atof();
               tree->Fill();
             }
           }
         }
         else if(line0.find("STARTED midas run") < line0.size()) {
           TString line =
             line0.substr(line0.find("STARTED")+std::string("STARTED midas run ").size()).c_str();
           runnum = line.Atoi();
         }
       }
       fTrees.insert(std::make_pair(runnum, std::make_pair(tree, strTime)));
       fullRun = kTRUE;
       std::stringstream ssname, sstitle;
       ssname << "tcup" << runnum;
       if(runnum == 0) {
         static int i = 0;
         ssname << "_" << i++ ;
       }
       sstitle << "Farady cup readings preceding run " << runnum;
       tree->SetNameTitle(ssname.str().c_str(), sstitle.str().c_str());
       if(!fullRun) tree->Delete();
     }
   }
   return retval;
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/utils/RootAnalysis.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/utils/RootAnalysis.cxx