DRAGON Analyzer: dragon::Dsssd Class Reference
dragon::Dsssd Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Dsssd ()
Constructor, initialize data.
void reset ()
Reset all data to VME::none.
void read_data (const vme::V785 adcs[], const vme::V1190 &tdc)
Read data from vme modules.
void calculate ()
Performs energy and time calibrations.
Public Attributes
double ecal [MAX_CHANNELS]
Calibrated energy signals.
double efront
Highest energy signal in the front strips (0 - 15)
double eback
Highest energy signal in the back strips (16 - 31)
uint32_t hit_front
Which strip was hit in the front strips.
uint32_t hit_back
Which strip was hit in the back strips.
double tfront
Calibrated time signal from the front strips.
double tback
Calibrated time signal from the back strips.
Dsssd::Variables variables
Instance of Dsssd::Variables.
Static Public Attributes
static const int MAX_CHANNELS = 32
Number of channels.
Detailed Description
Double-Sided Silicon Strip Detector
Definition at line 139 of file Dragon.hxx.
Constructor & Destructor Documentation
Dsssd()
dragon::Dsssd::Dsssd ()
Constructor, initialize data.
::
Definition at line 277 of file Dragon.cxx.
References reset().
                   :
   variables()
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::Dsssd::calculate ()
Performs energy and time calibrations.
Does a linear transformation on each element in this->ecal[] using the slopes and offsets from variables.adc_slope and variables.adc_offset, respectively. Also calibrates the TDC signal; calculates efront, hit_front, eback, and hit_back.
Delegates the work to dutils::linear_calibrate
Note
Do we want to add a zero suppression threshold here?
Definition at line 306 of file Dragon.cxx.
References dragon::utils::is_valid_any(), and dragon::utils::linear_calibrate().
Referenced by dragon::DsssdCalibrate::ProcessEntry().
 {
   /*!
    * Does a linear transformation on each element in \c this->ecal[] using the slopes and offsets
    * from variables.adc_slope and variables.adc_offset, respectively. Also calibrates the TDC
    * signal; calculates efront, hit_front, eback, and hit_back.
    *
    * Delegates the work to dutils::linear_calibrate
    * \note Do we want to add a zero suppression threshold here?
    */
   dutils::linear_calibrate(ecal, MAX_CHANNELS, variables.adc);
   dutils::linear_calibrate(tfront, variables.tdc_front);
   dutils::linear_calibrate(tback,  variables.tdc_back);
   if(dutils::is_valid_any(ecal, 16)) {
     const double* const pmax_front = std::max_element(ecal, ecal+16);
     efront = *pmax_front;
     hit_front = pmax_front - ecal;
   }
   if(dutils::is_valid_any(ecal+16, 16)) {
     const double* const pmax_back  = std::max_element(ecal+16, ecal+32);
     eback  = *pmax_back;
     hit_back = pmax_back - ecal;
   }
 }
read_data()
void dragon::Dsssd::read_data (const vme::V785 adcs[], const vme::V1190 & tdc)
Read data from vme modules.
Copies adc data into this->ecal[] with channel and module mapping taken from variables.adc.channel and variables.adc.modules
Delegates work to dutils::channel_map()
Parameters
[in] adcs Array of vme::V785 adc modules from which data can be taken
[in] tdc vme::V1190 tdc module from which data can be read
Definition at line 291 of file Dragon.cxx.
References dragon::utils::channel_map().
Referenced by dragon::DsssdCalibrate::ProcessEntry().
 {
   /*!
    * Copies adc data into \c this->ecal[] with channel and module mapping taken
    * from variables.adc.channel and variables.adc.modules
    *
    * Delegates work to dutils::channel_map()
    * \param [in] adcs Array of vme::V785 adc modules from which data can be taken
    * \param [in] tdc vme::V1190 tdc module from which data can be read
    */
   dutils::channel_map(ecal, MAX_CHANNELS, variables.adc.channel, variables.adc.module, adcs);
   dutils::channel_map(tfront, variables.tdc_front.channel, tdc);
   dutils::channel_map(tback,  variables.tdc_back.channel,  tdc);
 }
reset()
void dragon::Dsssd::reset ()
Reset all data to VME::none.
::
Definition at line 284 of file Dragon.cxx.
References dragon::utils::reset_array(), and dragon::utils::reset_data().
Referenced by Dsssd().
 {
   /// ::
   dutils::reset_data(efront, eback, hit_front, hit_back, tfront, tback);
   dutils::reset_array(MAX_CHANNELS, ecal);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx