DRAGON Analyzer: rbdragon::MidasBuffer Class Reference
rbdragon::MidasBuffer Class Reference
Dragon-specific r::MidasBuffer class.
#include <rbdragon.hxx>
Public Member Functions
MidasBuffer ()
Constructor.
~MidasBuffer ()
No actions needed.
Bool_t UnpackEvent (void *header, char *data)
Look at the event id and handle as appropriate.
void RunStartTransition (Int_t runnum)
Virtual run start transition handler.
void RunStopTransition (Int_t runnum)
Virtual run stop transition handler.
void ReadVariables (midas::Database *db)
Helper function to read variables from online or offline database.
Protected Attributes
dragon::Unpacker fUnpacker
Unpacker instance.
Additional Inherited Members
Static Public Member Functions inherited from rb::MidasBuffer
static MidasBuffer::Instance ()
Create new instance of the rdbragon::MidasBuffer class.
Detailed Description
Dragon-specific r::MidasBuffer class.
Definition at line 32 of file rbdragon.hxx.
Constructor & Destructor Documentation
MidasBuffer()
rbdragon::MidasBuffer::MidasBuffer ()
Constructor.
Set transition priorities different from default (750 for stop), set buffer size to 1024*1024, initialize fUnpacker w/ rb::Event<> instances.
Definition at line 83 of file rbdragon.cxx.
                                 :
   rb::MidasBuffer(1024*1024, 500, 750, 500, 500),
   fUnpacker(rb::Event::Instance<rbdragon::GammaEvent>()->Get(),
             rb::Event::Instance<rbdragon::HeavyIonEvent>()->Get(),
             rb::Event::Instance<rbdragon::CoincEvent>()->Get(),
             rb::Event::Instance<rbdragon::EpicsEvent>()->Get(),
             rb::Event::Instance<rbdragon::HeadScaler>()->Get(),
             rb::Event::Instance<rbdragon::TailScaler>()->Get(),
             rb::Event::Instance<rbdragon::AuxScaler>()->Get(),
             rb::Event::Instance<rbdragon::RunParameters>()->Get(),
             rb::Event::Instance<rbdragon::TStampDiagnostics>()->Get())
 {
   ///
   /// Set transition priorities different from default (750 for stop), set buffer size to 1024*1024,
   /// initialize fUnpacker w/ rb::Event<> instances.
   ;
 }
Member Function Documentation
RunStartTransition()
void rbdragon::MidasBuffer::RunStartTransition (Int_t runnum)
Virtual run start transition handler.
Does the following:
Reset scalers
Read variables from the ODB if online and if told to (SetAutoZeroOdb)
Zero all histograms if online and enabled:
Level 0 - do nothing
Level 1 - clear scalers only
Level 2 - clear everything
Look at ODB and set canvas to web saving if enabled
Call parent class implementation (prints a message)
Definition at line 107 of file rbdragon.cxx.
References DRAGON_AUX_SCALER, DRAGON_HEAD_SCALER, DRAGON_TAIL_SCALER, rbdragon::GetAutoZero(), rbdragon::GetAutoZeroOdb(), midas::Odb::ReadBool(), midas::Database::ReadValue(), and rbdragon::SetAutoZero().
 {
   ///
   /// Does the following:
   /// - Reset scalers
   rb::Event::Instance<rbdragon::HeadScaler>()->Reset();
   rb::Event::Instance<rbdragon::TailScaler>()->Reset();
   rb::Event::Instance<rbdragon::AuxScaler>()->Reset();
   rb::Event::Instance<rbdragon::RunParameters>()->Reset();
   rb::Event::Instance<rbdragon::TStampDiagnostics>()->Reset();
   /// - Read variables from the ODB if online and if told to (SetAutoZeroOdb)
   if (fType == rb::MidasBuffer::ONLINE && GetAutoZeroOdb() == true) {
     dragon::utils::Info("rbdragon::MidasBuffer")
       << "Syncing variable values with the online database.";
     midas::Database db("online");
     ReadVariables(&db);
     // Also set auto zero level from "/dragon/rootbeer/AutoZero"
     {
       Int_t autoZeroLevel = 0;
       Bool_t success = db.ReadValue("/dragon/rootbeer/AutoZero", autoZeroLevel);
       if(success) {
         SetAutoZero(autoZeroLevel);
       }
       else {
         dragon::utils::Warning("RunStartTransition")
           << "Unable to read auto zero level from MIDAS database \"/dragon/rootbeer/AutoZero\", "
           << "defaulting to level 1.";
         SetAutoZero(1);
       }
     }
   }
   /// - Zero all histograms if online and enabled:
   if (fType == rb::MidasBuffer::ONLINE) {
     switch (GetAutoZero()) {
     case 0:       /// - Level 0 - do nothing
       break;
     case 1:       /// - Level 1 - clear scalers only
       {
         Int_t codes[] = { DRAGON_HEAD_SCALER, DRAGON_TAIL_SCALER, DRAGON_AUX_SCALER };
         Int_t ncodes = sizeof(codes) / sizeof(Int_t);
         for(Int_t i=0; i< ncodes; ++i) {
           rb::Event* evt = rb::Rint::gApp()->GetEvent (codes[i]);
           if(!evt) continue;
           rb::hist::Manager* manager = evt->GetHistManager();
           if(manager) manager->ClearAll();
         }
       }
       break;
     case 2:       /// - Level 2 - clear everything
       rb::hist::ClearAll();
       break;
     default:
       break;
     }
   }
   /// - Look at ODB and set canvas to web saving if enabled
   if (fType == rb::MidasBuffer::ONLINE) {
     midas::Database db("online");
     std::string webFile = "";
     Bool_t saveCanvas = true, success = kTRUE;
     if(success) saveCanvas = midas::Odb::ReadBool("/dragon/rootbeer/canvas/SaveToWeb");
     if(success) success = db.ReadValue("/dragon/rootbeer/canvas/WebFile", webFile);
     if(success && !webFile.empty()) {
       rb::canvas::SetWebFile(webFile.c_str());
     } else {
       if(!success) {
         dragon::utils::Warning("RunStartTransition")
           << "Couldn't read web canvas settings from ODB";
       } else {
         dragon::utils::Warning("RunStartTransition")
           << "Empty \"/dragon/rootbeer/WebFile\" in ODB";
       }
     }
   }
   /// - Call parent class implementation (prints a message)
   rb::MidasBuffer::RunStartTransition(runnum);
 }
RunStopTransition()
void rbdragon::MidasBuffer::RunStopTransition (Int_t runnum)
Virtual run stop transition handler.
Does the following:
Flush timestamp queue (max 15 seconds for online)
Print delayed error messages
Call parent class implementation (prints a message)
Definition at line 211 of file rbdragon.cxx.
References dragon::utils::DelayedMessageFactory::Flush(), and dragon::utils::gDelayedMessageFactory.
 {
   ///
   /// Does the following:
   /// - Flush timestamp queue (max 15 seconds for online)
   Int_t flush_time = fType == ONLINE ? 15 : -1;
   time_t t_begin = time(0);
   size_t qsize;
   while (1) {
     if (flush_time >= 0 &&
         (difftime(time(0), t_begin) > flush_time))
       break;
     fUnpacker.ClearUnpackedCodes();
     qsize = fUnpacker.FlushQueueIterative(); // Fills classes implicitly
     if (qsize == 0) break;
     std::vector<Int_t> v = fUnpacker.GetUnpackedCodes();
     process_events(v);
   }
   if (qsize) {
     fUnpacker.GetQueue()->FlushTimeoutMessage(flush_time);
     fUnpacker.GetQueue()->Clear();
   }
   /// - Print delayed error messages
   dragon::utils::gDelayedMessageFactory.Flush();
   /// - Call parent class implementation (prints a message)
   rb::MidasBuffer::RunStopTransition(runnum);
 }
UnpackEvent()
Bool_t rbdragon::MidasBuffer::UnpackEvent (void * header, char * data)
Look at the event id and handle as appropriate.
Does the following:
If BOR event (ODB dump), set variables from there
For all other events, delegate to rb::Unpacker, then call the Process() function
Definition at line 255 of file rbdragon.cxx.
References MIDAS_BOR.
 {
   ///
   /// Does the following:
   midas::Event::Header* phead = reinterpret_cast<midas::Event::Header*>(header);
   /// - If BOR event (ODB dump), set variables from there
   if (phead->fEventId == MIDAS_BOR) {
     midas::Database db(data, phead->fDataSize);
     ReadVariables(&db);
   }
   /// - For all other events, delegate to rb::Unpacker, then call the Process() function
   std::vector<Int_t> v = fUnpacker.UnpackMidasEvent(phead, data);
   process_events(v);
   return kTRUE;
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/rootbeer/rbdragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/rootbeer/rbdragon.cxx