DRAGON Analyzer: dragon::Bgo Class Reference
dragon::Bgo Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Bgo ()
Constructor, initializes data values.
void reset ()
Sets all data values to dragon::NO_DATA.
void read_data (const vme::V792 &adc, const vme::V1190 &tdc)
Read adc & tdc data.
void calculate ()
Do higher-level parameter calculations.
Public Attributes
double ecal [MAX_CHANNELS]
Calibrated energies.
double tcal [MAX_CHANNELS]
Calibrates times.
double esort [MAX_CHANNELS]
Sorted (high->low) energies.
double sum
Sum of all valid energies.
int hit0
Which detector was the highest energy hit.
double x0
x position of the highest energy hit
double y0
y position of the highest energy hit
double z0
z position of the highest energy hit
double t0
time of the highest energy hit
Bgo::Variables variables
Instance of Bgo::Variables.
Static Public Attributes
static const int MAX_CHANNELS = 30
Number of channels in the BGO array.
Detailed Description
The BGO array
Definition at line 72 of file Dragon.hxx.
Constructor & Destructor Documentation
Bgo()
dragon::Bgo::Bgo ()
Constructor, initializes data values.
::
Definition at line 157 of file Dragon.cxx.
References reset().
               :
   variables()
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::Bgo::calculate ()
Do higher-level parameter calculations.
Does the following:
Pedestal subtract, zero suppress and calibrate energy values
Calibrate time values
Calculate descending-order energy indices and map into esort[]
If we have at least one good hit, calculate sum, x0, y0, z0, and t0
Definition at line 184 of file Dragon.cxx.
References dragon::utils::calculate_sum(), dragon::utils::channel_map_from_array(), dragon::utils::index_sort(), dragon::utils::is_valid(), dragon::utils::linear_calibrate(), dragon::utils::pedestal_subtract(), and dragon::utils::zero_suppress1().
 {
   /*!
    * Does the following:
    */
   /// - Pedestal subtract, zero suppress and calibrate energy values
   dutils::pedestal_subtract(ecal, MAX_CHANNELS, variables.adc);
   dutils::zero_suppress1(ecal, MAX_CHANNELS, 10.);
   dutils::linear_calibrate(ecal, MAX_CHANNELS, variables.adc);
   /// - Calibrate time values
   dutils::linear_calibrate(tcal, MAX_CHANNELS, variables.tdc);
   /// - Calculate descending-order energy indices and map into \c esort[]
   int isort[MAX_CHANNELS];
   dutils::index_sort(ecal, ecal+MAX_CHANNELS, isort, dutils::greater_and_valid<double>());
   dutils::channel_map_from_array(esort, MAX_CHANNELS, isort, ecal);
   /// - If we have at least one good hit, calculate sum, x0, y0, z0, and t0
   if(dutils::is_valid(esort[0])) {
     hit0 = isort[0];
     sum = dutils::calculate_sum(ecal, ecal + MAX_CHANNELS);
     x0 = variables.pos.x[ isort[0] ];
     y0 = variables.pos.y[ isort[0] ];
     z0 = variables.pos.z[ isort[0] ];
     t0 = tcal[ isort[0] ];
   }
 }
read_data()
void dragon::Bgo::read_data (const vme::V792 & adc, const vme::V1190 & tdc)
Read adc & tdc data.
Does channel mapping from ADC and TDC modules
Parameters
[in] adc Adc module
[in] tdc Tdc module
Definition at line 173 of file Dragon.cxx.
References dragon::utils::channel_map().
 {
   /*!
    * Does channel mapping from ADC and TDC modules
    * \param [in] adc Adc module
    * \param [in] tdc Tdc module
    */
   dutils::channel_map(ecal, MAX_CHANNELS, variables.adc.channel, adc);
   dutils::channel_map(tcal, MAX_CHANNELS, variables.tdc.channel, tdc);
 }
reset()
void dragon::Bgo::reset ()
Sets all data values to dragon::NO_DATA.
::
Definition at line 164 of file Dragon.cxx.
References dragon::utils::reset_array(), and dragon::utils::reset_data().
Referenced by Bgo().
 {
   /// ::
   dutils::reset_array(MAX_CHANNELS, ecal);
   dutils::reset_array(MAX_CHANNELS, tcal);
   dutils::reset_array(MAX_CHANNELS, esort);
   dutils::reset_data(sum, x0, y0, z0, t0, hit0);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx