DRAGON Analyzer: dragon::Epics::Variables Class Reference
dragon::Epics::Variables Class Reference
#include <Dragon.hxx>
Public Member Functions
Variables ()
Constuctor.
void reset ()
Resets names to default values.
bool set (const char *dbfile)
Set data values from an database (file or online)
bool set (const midas::Database *db)
Set data values from a constructed database.
Public Attributes
std::vector< std::string > names
Name of a given channel.
midas::Bank_t bkname
Bank name.
Detailed Description
EPICS variables
Definition at line 883 of file Dragon.hxx.
Constructor & Destructor Documentation
Variables()
dragon::Epics::Variables::Variables ()
Constuctor.
Calls reset()
Definition at line 1616 of file Dragon.cxx.
References dragon::Scaler::reset().
 {
   /*! Calls reset() */
   reset();
 }
Member Function Documentation
reset()
void dragon::Epics::Variables::reset ()
Resets names to default values.
Call vector::clear() on names
Set bank name to "EPCS"
Definition at line 1622 of file Dragon.cxx.
References dragon::utils::set_bank_name().
 {
   /// Call `vector::clear()` on names
   names.clear();
   /// Set bank name to `"EPCS"`
   dutils::set_bank_name("EPCS", bkname);
 }
set() [1/2]
bool dragon::Epics::Variables::set (const char * dbfile)
Set data values from an database (file or online)
Parameters
[in] dbfile Name of the database file from which to read variables ("online" for the ODB).
Definition at line 1630 of file Dragon.cxx.
References midas::Database::IsZombie().
 {
   /*!
    * \param [in] dbfile Name of the database file from which to read variables ("online" for the ODB).
    */
   midas::Database db(dbfile);
   if(db.IsZombie()) {
     dutils::Error("Epics::Variables::Set", __FILE__, __LINE__)
       << "Zombie database: " << dbfile;
     return false;
   }
   return this->set(&db);
 }
set() [2/2]
bool dragon::Epics::Variables::set (const midas::Database * db)
Set data values from a constructed database.
Parameters
[in] db Pointer to a valid database.
Definition at line 1644 of file Dragon.cxx.
References midas::Database::ReadArray(), and midas::Database::ReadArrayLength().
 {
   /*!
    * \param [in] db Pointer to a valid database.
    */
   bool success = check_db(db, "dragon::Epics");
   int length = db->ReadArrayLength("/Equipment/Epics/Settings/names Epics_Values");
   if(length < 0) success = false;
   if(success) {
     names.clear();
     names.resize(length);
     success = db->ReadArray("/Equipment/Epics/Settings/names Epics_Values", &names[0], length);
   }
   if(success) success = odb_set_bank(&bkname, db, "/dragon/epics/bank_name");
   return success;
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx