DRAGON Analyzer: dragon::Scaler::Variables Class Reference
dragon::Scaler::Variables Class Reference
#include <Dragon.hxx>
Public Member Functions
Variables ()
Constuctor.
void reset ()
Resets names to default values.
bool set (const char *dbfile, const char *dir)
Set data values from an database (file or online)
bool set (const midas::Database *db, const char *dir)
Set data values from a constructed database.
Public Attributes
std::string names [MAX_CHANNELS]
Name of a given channel.
midas::Bank_t bk_count
count bank name
midas::Bank_t bk_rate
rate bank name
midas::Bank_t bk_sum
sum bank name
std::string odb_path
Base odb path.
Detailed Description
Scalar variables
Definition at line 820 of file Dragon.hxx.
Constructor & Destructor Documentation
Variables()
dragon::Scaler::Variables::Variables ()
Constuctor.
Calls reset()
Definition at line 1366 of file Dragon.cxx.
References reset().
                                 :
   odb_path("/dragon/scaler/")
 {
   /*!
    * Calls reset()
    */
   reset();
 }
Member Function Documentation
reset()
void dragon::Scaler::Variables::reset ()
Resets names to default values.
Resets every channel to a default name: channel_n
Set bank names to dummy values
Definition at line 1375 of file Dragon.cxx.
References dragon::Scaler::MAX_CHANNELS, and dragon::utils::set_bank_name().
Referenced by Variables().
 {
   /*! Resets every channel to a default name: \c channel_n*/
   for (int i=0; i< MAX_CHANNELS; ++i) {
     std::stringstream strm_name;
     strm_name << "channel_" << i;
     names[i] = strm_name.str();
   }
   /// - Set bank names to dummy values
   dutils::set_bank_name("NULD", bk_count);
   dutils::set_bank_name("NULR", bk_rate);
   dutils::set_bank_name("NULS", bk_sum);
 }
set() [1/2]
bool dragon::Scaler::Variables::set (const char * dbfile, const char * dir)
Set data values from an database (file or online)
Parameters
[in] dbfile Name of the database file from which to read variables ("online" for the ODB).
[in] dir String specifying the scaler subdirectory in which to look for the variables data, e.g. "head" looks in "/dragon/scaler/head", "tail": "/dragon/scaler/tail".
Definition at line 1390 of file Dragon.cxx.
References midas::Database::IsZombie().
Referenced by dragon::Coinc::set_variables(), and dragon::Epics::set_variables().
 {
   /*!
    * \param [in] dbfile Name of the database file from which to read variables ("online" for the ODB).
    * \param [in] dir String specifying the scaler subdirectory in which to look for
    *  the variables data, e.g. "head" looks in "/dragon/scaler/head", "tail":
    * "/dragon/scaler/tail".
    */
   midas::Database db(dbfile);
   if(db.IsZombie()) {
     dutils::Error("Scaler::Variables::Set", __FILE__, __LINE__)
       << "Zombie database: " << dbfile;
     return false;
   }
   return this->set(&db, dir);
 }
set() [2/2]
bool dragon::Scaler::Variables::set (const midas::Database * db, const char * dir)
Set data values from a constructed database.
Parameters
[in] db Pointer to a valid database.
[in] dir String specifying the scaler subdirectory in which to look for the variables data, e.g. "head" looks in "/dragon/scaler/head", "tail": "/dragon/scaler/tail".
Definition at line 1407 of file Dragon.cxx.
References dragon::Scaler::MAX_CHANNELS, and midas::Database::ReadArray().
 {
   /*!
    * \param [in] db Pointer to a valid database.
    * \param [in] dir String specifying the scaler subdirectory in which to look for
    *  the variables data, e.g. "head" looks in "/dragon/scaler/head", "tail":
    * "/dragon/scaler/tail".
    */
   std::string path1 = dir;
   if (path1 != "head" && path1 != "tail" && path1 != "aux") {
     dutils::Error("Scaler::Variables::set", __FILE__, __LINE__)
       << "Invalid subdirectory: \"" << path1 << "\"."
       << "Must be either \"head\" or \"tail\"";
     return false;
   }
   path1 = odb_path + path1;
   bool success = check_db(db, "dragon::Scaler");
   if(success) success = db->ReadArray((path1 + "/names").c_str(), names, MAX_CHANNELS);
   if(success) success = odb_set_bank(&bk_count, db, (path1 + "/bank_names/count").c_str());
   if(success) success = odb_set_bank(&bk_rate, db, (path1 + "/bank_names/rate").c_str());
   if(success) success = odb_set_bank(&bk_sum, db, (path1 + "/bank_names/sum").c_str());
   return success;
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx