DRAGON Analyzer: dragon::Unpacker Class Reference
dragon::Unpacker Class Reference
#include <Unpack.hxx>
Public Member Functions
Unpacker (dragon::Head *head, dragon::Tail *tail, dragon::Coinc *coinc, dragon::Epics *epics, dragon::Scaler *schead, dragon::Scaler *sctail, dragon::Scaler *scaux, dragon::RunParameters *runpar, tstamp::Diagnostics *tsdiag, bool singlesMode=false)
~Unpacker ()
void ClearUnpackedCodes ()
void FlushQueue (int flushTime=-1)
size_t FlushQueueIterative ()
tstamp::Queue * GetQueue () const
bool IsSinglesMode () const
double GetCoincWindow () const
double GetQueueTime () const
std::vector< int32_t > GetUnpackedCodes () const
void HandleBor (const char *dbname)
void Process (const midas::Event &event)
void Process (const midas::Event &event1, const midas::Event &event2)
void Process (tstamp::Diagnostics *)
void SetCoincMode ()
void SetCoincWindow (double window)
void SetSinglesMode (int qFlush=-1)
void SetQueueTime (double t)
void UnpackHead (const midas::Event &event)
void UnpackTail (const midas::Event &event)
void UnpackCoinc (const midas::CoincEvent &event)
void UnpackHeadScaler (const midas::Event &event)
void UnpackTailScaler (const midas::Event &event)
void UnpackAuxScaler (const midas::Event &event)
void UnpackEpics (const midas::Event &event)
void UnpackRunParameters (const midas::Database &db)
std::vector< int32_t > UnpackMidasEvent (char *databuf)
std::vector< int32_t > UnpackMidasEvent (void *header, char *data)
Private Attributes
double fCoincWindow
Size of the coincidence window in microseconds (defaults to 10)
std::auto_ptr< tstamp::Queue > fQueue
Timestamp queue for coincidence matching.
std::vector< int32_t > fUnpacked
Container of event codes of unpacked events.
dragon::Head * fHead
Pointer to external head class.
dragon::Tail * fTail
Pointer to external tail class.
dragon::Coinc * fCoinc
Pointer to external coinc class.
dragon::Epics * fEpics
Pointer to external epics class.
dragon::Scaler * fHeadScaler
Pointer to external scaler class (for head data)
dragon::Scaler * fTailScaler
Pointer to external scaler class (for tail data)
dragon::Scaler * fAuxScaler
Pointer to external scaler class (for aux data)
dragon::RunParameters * fRunpar
Pointer to external run parameters class.
tstamp::Diagnostics * fDiag
Pointer to external timestamp diagnostics class.
Static Private Attributes
static const int kQueueTimeDefault = 4
Default queue time in seconds.
static const int kCoincWindowDefault = 10
Default coincidence window in usec.
Detailed Description
Handles unpacking event data
Definition at line 27 of file Unpack.hxx.
Constructor & Destructor Documentation
dragon::Unpacker::Unpacker (dragon::Head * head, dragon::Tail * tail, dragon::Coinc * coinc, dragon::Epics * epics, dragon::Scaler * schead, dragon::Scaler * sctail, dragon::Scaler * scaux, dragon::RunParameters * runpar, tstamp::Diagnostics * tsdiag, bool singlesMode = false)
Sets pointers to container classes, initializes fQueue
Definition at line 18 of file Unpack.cxx.
References fQueue, and kQueueTimeDefault.
                                 :
   fCoincWindow(kCoincWindowDefault),
   fQueue(0),
   fHead(head),
   fTail(tail),
   fCoinc(coinc),
   fEpics(epics),
   fHeadScaler(schead),
   fTailScaler(sctail),
   fAuxScaler(scaux),
   fRunpar(runpar),
   fDiag(tsdiag)
 {
   if(!singlesMode)
     fQueue.reset(new tstamp::OwnedQueue<dragon::Unpacker>(kQueueTimeDefault*1e6, this));
}
dragon::Unpacker::~Unpacker ()
Nothing to do, all cleanup is automatic
Definition at line 44 of file Unpack.cxx.
 {
   ;
 }
Member Function Documentation
void dragon::Unpacker::ClearUnpackedCodes () inline
Clear vector of unpacked codes
Needed when the unpack routines are called implicitly, for example during a queue flush which calls Process(), not UnpackEvent()
Definition at line 213 of file Unpack.hxx.
 {
   /// Needed when the unpack routines are called implicitly, for example
   /// during a queue flush which calls Process(), not UnpackEvent()
   fUnpacked.clear();
 }
void dragon::Unpacker::FlushQueue (int flushTime = -1)
Flush the timestamp queue
Definition at line 49 of file Unpack.cxx.
 {
   fQueue->Flush(flushTime, fDiag);
 }
size_t dragon::Unpacker::FlushQueueIterative ()
Flush the timestamp queue, for only a single event
Returns
The size of the queue after removing the front event
Definition at line 54 of file Unpack.cxx.
Referenced by m2r::main_().
 {
   /// \returns The size of the queue after removing the front event
   fUnpacked.clear();
   return fQueue->FlushIterative(fDiag);
 }
double dragon::Unpacker::GetCoincWindow () const inline
Returns the length of the coincidence window in microseconds
Definition at line 162 of file Unpack.hxx.
Referenced by m2r::main_().
 {
   return fCoincWindow;
 }
tstamp::Queue * dragon::Unpacker::GetQueue () const inline
Return a pointer to fQueue
Definition at line 235 of file Unpack.hxx.
 {
   return fQueue.get();
 }
double dragon::Unpacker::GetQueueTime () const inline
Returns the queue buffering time in seconds
Definition at line 167 of file Unpack.hxx.
Referenced by m2r::main_().
 {
   return fQueue->GetMaxDelta() / 1e6;
 }
std::vector< int32_t > dragon::Unpacker::GetUnpackedCodes () const inline
Returns the event codes of unpacked events
Whenever a call to UnpackMidasEvent() is made, an internal vector<int32_t> is filled with the event codes corresponding to those event types which were unpacked into a class structure. This function allows the caller to see what those event codes are and, e.g. fill ROOT trees, ntuples, histograms, etc. as appripriate.
Definition at line 222 of file Unpack.hxx.
Referenced by m2r::main_().
 {
   /// Whenever a call to UnpackMidasEvent() is made, an
   /// internal vector<int32_t> is filled with the event codes
   /// corresponding to those event types which were unpacked into
   /// a class structure. This function allows the caller to see what
   /// those event codes are and, e.g. fill ROOT trees, ntuples, histograms,
   /// etc. as appripriate.
   return fUnpacked;
 }
void dragon::Unpacker::HandleBor (const char * dbname)
Perform actions at the beginning of a run
Reset head, tail scalers; run parameters; and timestamp diagnostics.
Read variables from the database corresponding to dbname (skip if dbname is NULL)
Definition at line 61 of file Unpack.cxx.
References midas::Database::CheckPath(), and midas::Database::IsZombie().
Referenced by m2r::main_().
 {
   /// - Reset head, tail scalers; run parameters; and timestamp diagnostics.
   fHeadScaler->reset();
   fTailScaler->reset();
   fAuxScaler->reset();
   fRunpar->reset();
   fDiag->reset();
   /// - Read variables from the database corresponding to \e dbname (skip if dbname is NULL)
   if (dbname) {
     midas::Database db(dbname);
     if(!db.IsZombie()) {
       fHead->set_variables(&db);
       fTail->set_variables(&db);
       fCoinc->set_variables(&db);
       fEpics->set_variables(&db);
       fHeadScaler->set_variables(&db, "head");
       fTailScaler->set_variables(&db, "tail");
       // Set sux scaler only if it's in the file
       if(db.CheckPath("/Equipment/AuxScaler/Settings/Route"))
         fAuxScaler->set_variables (&db, "aux" );
     }
   }
 }
bool dragon::Unpacker::IsSinglesMode () const inline
Returns true if we are in singles mode
Definition at line 157 of file Unpack.hxx.
References fQueue.
 {
   return !(fQueue.get());
 }
void dragon::Unpacker::Process (const midas::Event & event)
Process function to handle singles events popped from the queue
Definition at line 226 of file Unpack.cxx.
References DRAGON_HEAD_EVENT, and DRAGON_TAIL_EVENT.
 {
   switch (event.GetEventId())
     {
     case DRAGON_HEAD_EVENT:
       UnpackHead(event);
       break;
     case DRAGON_TAIL_EVENT:
       UnpackTail(event);
       break;
     default:
       utils::Error("utils::Unpacker::Process", __FILE__, __LINE__)
         << "Unknown event id: " << event.GetEventId() << ", skipping...\n";
       break;
     }
 }
void dragon::Unpacker::Process (const midas::Event & event1, const midas::Event & event2)
Process function to handle coincidence events popped from the queue
Definition at line 245 of file Unpack.cxx.
References midas::CoincEvent::fGamma, and midas::CoincEvent::fHeavyIon.
 {
   midas::CoincEvent coincEvent(event1, event2);
   if (coincEvent.fHeavyIon == 0 || coincEvent.fGamma == 0) {
     dragon::utils::Error("utils::unpacker::Process", __FILE__, __LINE__)
       << "Invalid coincidence event, skipping...\n";
     return;
   }
   UnpackCoinc(coincEvent);
 }
void dragon::Unpacker::Process (tstamp::Diagnostics *)
Process function for timestamp diagnostics [empty]
Definition at line 258 of file Unpack.cxx.
References DRAGON_TSTAMP_DIAGNOSTICS.
 {
   fUnpacked.push_back(DRAGON_TSTAMP_DIAGNOSTICS);
 }
void dragon::Unpacker::SetCoincMode () inline
Switch over to coincidence mode
If in singles mode when called, it switches over to coincidence mode with default coincidence window and queue time. To change these values, use SetCoincWindow() and SetQueueTime().
If we are already in coincidence mode, this has no effect.
Definition at line 195 of file Unpack.hxx.
 {
   /// If in singles mode when called, it switches over to coincidence
   /// mode with default coincidence window and queue time. To change
   /// these values, use SetCoincWindow() and SetQueueTime().
   ///
   /// If we are already in coincidence mode, this has no effect.
   if(!IsSinglesMode())
     fQueue.reset(new tstamp::OwnedQueue<Unpacker>(kQueueTimeDefault*1e6, this));
 }
void dragon::Unpacker::SetCoincWindow (double window) inline
Set the coincidence matching window
Note
Default value at construction is 10 usec.
Definition at line 172 of file Unpack.hxx.
Referenced by m2r::main_().
 {
   /// \note Default value at construction is 10 usec.
   fCoincWindow = window;
 }
void dragon::Unpacker::SetQueueTime (double t) inline
Set the queue buffering time
Note
Default value at construction is 4 sec.
Definition at line 178 of file Unpack.hxx.
Referenced by m2r::main_().
 {
   /// \note Default value at construction is 4 sec.
   fQueue->SetMaxDelta(t*1e6);
 }
void dragon::Unpacker::SetSinglesMode (int qFlush = -1) inline
Put the unpacker in singles mode
Any incoming events after this call are processed as singles only. If there are events in the queue, they are first flushed.
Parameters
qFlush Maximum flush time for events in the queue. Specifying a 0 skips flushing entirely and throws away any events in the queue. Negative numbers cause the entire queue to be flushed.
Definition at line 184 of file Unpack.hxx.
 {
   /// Any incoming events after this call are processed as singles only.
   /// If there are events in the queue, they are first flushed.
   /// \param qFlush Maximum flush time for events in the queue. Specifying a
   ///  0 skips flushing entirely and throws away any events in the queue. Negative
   ///  numbers cause the entire queue to be flushed.
   if(qFlush) FlushQueue(qFlush);
   fQueue.reset(0);
 }
void dragon::Unpacker::UnpackAuxScaler (const midas::Event & event)
Unpack a aux scaler event into fAuxScaler;
Read scaler data from the midas event
Definition at line 131 of file Unpack.cxx.
References DRAGON_AUX_SCALER.
 {
   fAuxScaler->unpack(event); /// - Read scaler data from the midas event
   fUnpacked.push_back(DRAGON_AUX_SCALER);
 }
void dragon::Unpacker::UnpackCoinc (const midas::CoincEvent & event)
Unpack a coincidence event into fCoinc
Reset the class to default values.
Read raw data from the MIDAS event.
Calculate abstract parameters.
Definition at line 104 of file Unpack.cxx.
References DRAGON_COINC_EVENT.
 {
   fCoinc->reset();       /// - Reset the class to default values.
   fCoinc->unpack(event); /// - Read raw data from the MIDAS event.
   fCoinc->calculate();   /// - Calculate abstract parameters.
   fUnpacked.push_back(DRAGON_COINC_EVENT);
 }
void dragon::Unpacker::UnpackEpics (const midas::Event & event)
Unpack an EPICS event into fEpics
Reset the class to default values.
Read raw data from the MIDAS event.
Definition at line 112 of file Unpack.cxx.
References DRAGON_EPICS_EVENT.
 {
   fEpics->reset();       /// - Reset the class to default values.
   fEpics->unpack(event); /// - Read raw data from the MIDAS event.
   fUnpacked.push_back(DRAGON_EPICS_EVENT);
 }
void dragon::Unpacker::UnpackHead (const midas::Event & event)
Unpack a head event into fHead
Reset the class to default values.
Read raw data from the MIDAS event.
Calculate abstract parameters.
Definition at line 88 of file Unpack.cxx.
References DRAGON_HEAD_EVENT.
 {
   fHead->reset();       /// - Reset the class to default values.
   fHead->unpack(event); /// - Read raw data from the MIDAS event.
   fHead->calculate();   /// - Calculate abstract parameters.
   fUnpacked.push_back(DRAGON_HEAD_EVENT);
 }
void dragon::Unpacker::UnpackHeadScaler (const midas::Event & event)
Unpack a head scaler event into fHeadScaler;
Read scaler data from the midas event
Definition at line 119 of file Unpack.cxx.
References DRAGON_HEAD_SCALER.
 {
   fHeadScaler->unpack(event); /// - Read scaler data from the midas event
   fUnpacked.push_back(DRAGON_HEAD_SCALER);
 }
std::vector< int32_t > dragon::Unpacker::UnpackMidasEvent (char * databuf) inline
Unpack a generic midas event (from full data buffer)
Forward all work to UnpackMidasEvent(void*, char*)
Definition at line 206 of file Unpack.hxx.
Referenced by m2r::main_().
 {
   /// Forward all work to UnpackMidasEvent(void*, char*)
   return UnpackMidasEvent(databuf, databuf + sizeof(midas::Event::Header));
 }
std::vector< int32_t > dragon::Unpacker::UnpackMidasEvent (void * header, char * data)
Unpack a generic midas event (from header + data)
Returns
The result of GetUnpackedCodes() after this event
Definition at line 143 of file Unpack.cxx.
References DRAGON_AUX_SCALER, DRAGON_EPICS_EVENT, DRAGON_EPICS_SCALER, DRAGON_HEAD_EVENT, DRAGON_HEAD_SCALER, DRAGON_TAIL_EVENT, DRAGON_TAIL_SCALER, MIDAS_BOR, and MIDAS_EOR.
 {
   fUnpacked.clear();
   midas::Event::Header* evtHeader = reinterpret_cast<midas::Event::Header*>(header);
   switch (evtHeader->fEventId)
     {
     case DRAGON_HEAD_EVENT:
       {
         if(IsSinglesMode()) {
           midas::Event event(header, data, evtHeader->fDataSize);
           UnpackHead(event);
         }
         else {
           midas::Event event(header, data, evtHeader->fDataSize, fHead->variables.bk_tsc, GetCoincWindow());
           fQueue->Push(event, fDiag);
         }
         break;
       }
     case DRAGON_TAIL_EVENT:
       {
         if(IsSinglesMode()) {
           midas::Event event(header, data, evtHeader->fDataSize);
           UnpackTail(event);
         }
         else {
           midas::Event event(header, data, evtHeader->fDataSize, fTail->variables.bk_tsc, GetCoincWindow());
           fQueue->Push(event, fDiag);
         }
         break;
       }
     case DRAGON_HEAD_SCALER:
       {
         midas::Event event(header, data, evtHeader->fDataSize);
         UnpackHeadScaler(event);
         break;
       }
     case DRAGON_TAIL_SCALER:
       {
         midas::Event event(header, data, evtHeader->fDataSize);
         UnpackTailScaler(event);
         break;
       }
     case DRAGON_AUX_SCALER:
       {
         midas::Event event(header, data, evtHeader->fDataSize);
         UnpackAuxScaler(event);
         break;
       }
     case DRAGON_EPICS_EVENT:
       {
         midas::Event event(header, data, evtHeader->fDataSize);
         UnpackEpics(event);
         break;
       }
     case DRAGON_EPICS_SCALER:
       {
         // EPICS virtaul scalers data are redundant, so do nothing
         break;
       }
     case MIDAS_BOR:
       {
         midas::Database db(data, evtHeader->fDataSize);
         UnpackRunParameters(db);
         break;
       }
     case MIDAS_EOR:
       {
         midas::Database db(data, evtHeader->fDataSize);
         UnpackRunParameters(db);
         break;
       }
     default:
       {
         utils::Warning("UnpackBuffer", __FILE__, __LINE__)
           << "Unkonwn event ID: " << evtHeader->fEventId;
         break;
       }
     }
   /// \returns The result of GetUnpackedCodes() after this event
   return fUnpacked;
 }
void dragon::Unpacker::UnpackRunParameters (const midas::Database & db)
Unpack run parameters into fRunpar
Calculate run parameters from an ODB dump event
Definition at line 137 of file Unpack.cxx.
References DRAGON_RUN_PARAMETERS.
 {
   fRunpar->read_data(&db); /// - Calculate run parameters from an ODB dump event
   fUnpacked.push_back(DRAGON_RUN_PARAMETERS);
 }
void dragon::Unpacker::UnpackTail (const midas::Event & event)
Unpack a tail event into fTail
Reset the class to default values.
Read raw data from the MIDAS event.
Calculate abstract parameters.
Definition at line 96 of file Unpack.cxx.
References DRAGON_TAIL_EVENT.
 {
   fTail->reset();       /// - Reset the class to default values.
   fTail->unpack(event); /// - Read raw data from the MIDAS event.
   fTail->calculate();   /// - Calculate abstract parameters.
   fUnpacked.push_back(DRAGON_TAIL_EVENT);
 }
void dragon::Unpacker::UnpackTailScaler (const midas::Event & event)
Unpack a tail scaler event into fTailScaler
Read scaler data from the midas event
Definition at line 125 of file Unpack.cxx.
References DRAGON_TAIL_SCALER.
 {
   fTailScaler->unpack(event); /// - Read scaler data from the midas event
   fUnpacked.push_back(DRAGON_TAIL_SCALER);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Unpack.hxx
/Users/dragon/packages/dragon/analyzer/src/Unpack.cxx