DRAGON Analyzer: dragon::Scaler Class Reference
dragon::Scaler Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Scaler ()
Initialize data.
void reset ()
Reset all data to zero.
void unpack (const midas::Event &event)
Unpack Midas event data into scalar data structiures.
const std::string & channel_name (int ch) const
Returns the name of a given scaler channel.
bool set_variables (const char *dbfile, const char *dir)
Reads all variable values from an database (file or online)
bool set_variables (const midas::Database *db, const char *dir)
Reads all variable values from a constructed database.
template<class T >
void set_aliases (T *t, bool print=false) const
Set branch alises in a ROOT TTree.
Static Public Member Functions
template<class T , class H >
static int64_t plot (T *tree, const char *varexp, const char *selection="", Option_t *option="")
Plot traditional scaler histograms using 1D bins.
Public Attributes
uint32_t count [MAX_CHANNELS]
Number of counts in a single read period.
uint32_t sum [MAX_CHANNELS]
Number of counts over the course of a run.
double rate [MAX_CHANNELS]
Average count rate over the course of a run.
Variables variables
Variables instance.
Static Public Attributes
static const int MAX_CHANNELS = 17
Number of scaler channels.
Detailed Description
Generic dragon scaler class
Definition at line 783 of file Dragon.hxx.
Constructor & Destructor Documentation
Scaler()
dragon::Scaler::Scaler ()
Initialize data.
Calls reset()
Definition at line 1287 of file Dragon.cxx.
References reset().
                     :
   variables()
 {
   /*! Calls reset() */
   reset();
 }
Member Function Documentation
channel_name()
const std::string & dragon::Scaler::channel_name (int ch) const
Returns the name of a given scaler channel.
Parameters
ch Channel number
Definition at line 1351 of file Dragon.cxx.
 {
   /*!
    * \param ch Channel number
    */
   if (ch >= 0 && ch < MAX_CHANNELS) return variables.names[ch];
   dutils::Error("dragon::Scaler::channel_name", __FILE__, __LINE__)
     << "Invalid channel number: " << ch << ". Valid arguments are 0 <= ch < " << MAX_CHANNELS;
   static std::string junk = "";
   return junk;
 }
plot()
template<class T , class H > int64_t dragon::Scaler::plot (T * tree, const char * varexp, const char * selection = "", Option_t * option = "") inline static
Plot traditional scaler histograms using 1D bins.
This function creates a "traditional" DRAGON scaler histograms, where the x-axis is time and the bin counts is the number of scaler counts. If one of the count[] variables is plotted, then the integral of the histogram will be the integral of scaler counts across the whole run
Parameters
tree Tree from which to plot (e.g. t2 for head t4 for tail)
varexp Same as you would use in TTree::Draw(), i.e. "count[10]>>hst(3600,0,3600)"
selection Cut selection, same as for TTree::Draw()
option DrawOption, same as for TTree::Draw()
Returns
Number of events plotted
Definition at line 955 of file Dragon.hxx.
 {
   ///
   /// This function creates a "traditional" DRAGON scaler histograms, where the x-axis is
   /// time and the bin counts is the number of scaler counts. If one of the `count[]` variables
   /// is plotted, then the integral of the histogram will be the integral of scaler counts across the
   /// whole run
   /// \param tree Tree from which to plot (e.g. `t2` for head `t4` for tail)
   /// \param varexp Same as you would use in TTree::Draw(), i.e. `"count[10]>>hst(3600,0,3600)"`
   /// \param selection Cut selection, same as for TTree::Draw()
   /// \param option DrawOption, same as for TTree::Draw()
   /// \returns Number of events plotted
   ///
   tree->SetEstimate(tree->GetEntries());
   int64_t nevts = tree->Draw(varexp, selection, "goff");
   H* hst = tree->GetHistogram();
   if(hst == 0) return 0;
   for(int bin = 0; bin< hst->GetNbinsX() + 1; ++bin)
     hst->SetBinContent(bin, 0);
   for(int64_t i=0; i< nevts; ++i) {
     int64_t bin = hst->FindBin(i);
     hst->SetBinContent(bin, hst->GetBinContent(bin) + tree->GetV1()[i]);
   }
   hst->Draw(option);
   return nevts;
 }
reset()
void dragon::Scaler::reset ()
Reset all data to zero.
Sets all count, rate, and sum to zero
Definition at line 1294 of file Dragon.cxx.
Referenced by dragon::Coinc::Coinc(), dragon::Epics::Epics(), Scaler(), dragon::Coinc::Variables::Variables(), and dragon::Epics::Variables::Variables().
 {
   /*! Sets all count, rate, and sum to zero */
   std::fill(count, count + MAX_CHANNELS, 0);
   std::fill(sum, sum + MAX_CHANNELS, 0);
   std::fill(rate, rate + MAX_CHANNELS, 0.);
 }
set_aliases()
template<class T > void dragon::Scaler::set_aliases (T * t, bool print = false) const inline
Set branch alises in a ROOT TTree.
Sets tree branch aliases based on variable values - results in easier to use branch names (e.g. something descriptive instead of 'scaler.sum[0]', etc.)
Parameters
t Pointer to a class having a "SetAlias(const char*, const char*) method (e.g. TTree) and for which you want to set aliases.
branchName "Base" name of the branch
Template Parameters
T Some class with a "SetAlias" method.
Note
Intended for TTree, but defined as a template function to maintain compatability with systems that don't use ROOT. In the case that ROOT is not available and this function is never used, it simply gets ignored by the compiler. Note also, that for systems with ROOT, a CINT dictionary definition is automoatically provided for TTree as the template parameter.
Example:
// (with a dragon root file loaded)
dragon::Scaler scaler;
scaler.set_variables(variables, "head")
scaler.set_aliases(t2);
t2->Draw("count_triggers_acquired/count_triggers_presented1:Entry$","","L")
Parameters
t Pointer to the TTree for which you want to set aliases.
print If true, prints each { alias, source } pair that's set.
Definition at line 911 of file Dragon.hxx.
References MAX_CHANNELS, dragon::Scaler::Variables::names, and variables.
 {
   /*!
    * Sets tree branch aliases based on variable values - results in easier to use
    * branch names (e.g. something descriptive instead of 'scaler.sum[0]', etc.)
    *
    * \param t Pointer to a class having a "SetAlias(const char*, const char*) method
    * (e.g. TTree) and for which you want to set aliases.
    * \param branchName "Base" name of the branch
    * \tparam T Some class with a "SetAlias" method.
    *
    * \note Intended for TTree, but defined as a template
    * function to maintain compatability with systems that don't use ROOT. In the case that ROOT is
    * not available and this function is never used, it simply gets ignored by the compiler. Note also,
    * that for systems with ROOT, a CINT dictionary definition is automoatically provided for TTree
    * as the template parameter.
    *
    * Example:
    * \code
    * // (with a dragon root file loaded)
    * dragon::Scaler scaler;
    * scaler.set_variables(variables, "head")
    * scaler.set_aliases(t2);
    * t2->Draw("count_triggers_acquired/count_triggers_presented1:Entry$","","L")
    * \endcode
    *
    * \param t Pointer to the TTree for which you want to set aliases.
    * \param print If true, prints each { alias, source } pair that's set.
    */
   const std::string chNames[3] = { "count", "sum", "rate" };
   for(int i=0; i< MAX_CHANNELS; ++i) {
     for(int j=0; j< 3; ++j) {
       std::stringstream oldName, newName;
       oldName << chNames[j] << "[" << i << "]";
       newName << chNames[j] << "_" << variables.names[i];
       t->SetAlias(newName.str().c_str(), oldName.str().c_str());
       if(print) {
         std::cout << "Set alias \"" << newName.str() << "\" == \"" << oldName.str() << "\"\n";
       }
     }
   }
 }
set_variables() [1/2]
bool dragon::Scaler::set_variables (const char * dbfile, const char * dir)
Reads all variable values from an database (file or online)
Delegates to dragon::Scaler::Variables::Set()
Definition at line 1302 of file Dragon.cxx.
 {
   /*!
    * Delegates to dragon::Scaler::Variables::Set()
    */
   return variables.set(dbfile, dir);
 }
set_variables() [2/2]
bool dragon::Scaler::set_variables (const midas::Database * db, const char * dir)
Reads all variable values from a constructed database.
Delegates to dragon::Scaler::Variables::Set()
Definition at line 1310 of file Dragon.cxx.
 {
   /*!
    * Delegates to dragon::Scaler::Variables::Set()
    */
   return variables.set(db, dir);
 }
unpack()
void dragon::Scaler::unpack (const midas::Event & event)
Unpack Midas event data into scalar data structiures.
Unpacks scaler data directly into the various array structures.
Definition at line 1331 of file Dragon.cxx.
 {
   /*!
    * Unpacks scaler data directly into the various array structures.
    */
   bool report = true;
   int bank_len;
   uint32_t* pcount = event.GetBankPointer<uint32_t>(variables.bk_count, &bank_len, report, true);
   if ( check_bank_len(MAX_CHANNELS, bank_len, variables.bk_count) )
     std::copy(pcount, pcount + bank_len, count);
   uint32_t* psum = event.GetBankPointer<uint32_t>(variables.bk_sum, &bank_len, report, true);
   if ( check_bank_len(MAX_CHANNELS, bank_len, variables.bk_sum) )
     std::copy(psum, psum + bank_len, sum);
   double* prate = event.GetBankPointer<double>(variables.bk_rate, &bank_len, report, true);
   if ( check_bank_len(MAX_CHANNELS, bank_len, variables.bk_rate) )
     std::copy(prate, prate + bank_len, rate);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx