DRAGON Analyzer: dragon::NaI Class Reference
dragon::NaI Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
NaI ()
Constructor, initialize data.
void reset ()
Reset all data to vme::NONE.
void read_data (const vme::V785 adcs[], const vme::V1190 &)
Read event data from vme modules.
void calculate ()
Do energy calibrations.
Public Attributes
double ecal [MAX_CHANNELS]
Calibrated energy signals.
NaI::Variables variables
Variables instance.
Static Public Attributes
static const int MAX_CHANNELS = 2
Number of detectors.
Detailed Description
Sodium Iodide (NaI) detectors
Definition at line 365 of file Dragon.hxx.
Constructor & Destructor Documentation
NaI()
dragon::NaI::NaI ()
Constructor, initialize data.
::
Definition at line 695 of file Dragon.cxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::NaI::calculate ()
Do energy calibrations.
Linear calibration of energies
Definition at line 719 of file Dragon.cxx.
References dragon::utils::linear_calibrate().
 {
   /// Linear calibration of energies
   dutils::linear_calibrate(ecal, MAX_CHANNELS, variables.adc);
 }
read_data()
void dragon::NaI::read_data (const vme::V785 adcs[], const vme::V1190 &)
Read event data from vme modules.
Copies adc data into this->ecal[] with channel and module mapping taken from variables.adc.channel and variables.adc.modules
Delegates work to dutils::channel_map()
Parameters
[in] adcs Array of vme::V785 adc modules from which data can be taken
Definition at line 707 of file Dragon.cxx.
References dragon::utils::channel_map().
 {
   /*!
    * Copies adc data into \c this->ecal[] with channel and module mapping taken
    * from variables.adc.channel and variables.adc.modules
    *
    * Delegates work to dutils::channel_map()
    * \param [in] adcs Array of vme::V785 adc modules from which data can be taken
    */
   dutils::channel_map(ecal, MAX_CHANNELS, variables.adc.channel, variables.adc.module, adcs);
 }
reset()
void dragon::NaI::reset ()
Reset all data to vme::NONE.
::
Definition at line 701 of file Dragon.cxx.
References dragon::utils::reset_array().
 {
   /// ::
   dutils::reset_array(MAX_CHANNELS, ecal);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx