DRAGON Analyzer: dragon::Dsssd::Variables Class Reference
dragon::Dsssd::Variables Class Reference
#include <Dragon.hxx>
Public Member Functions
Variables ()
Constructor, sets data to generic values.
bool set (const char *dbfile)
Set data values from an database (file or online)
bool set (const midas::Database *db)
Set data values from a constructed database.
void reset ()
Reset all variable values to defaults.
Public Attributes
dragon::utils::AdcVariables< 32 > adc
Adc variables for the energy signals.
dragon::utils::TdcVariables< 1 > tdc_front
Tdc variables (front strips)
dragon::utils::TdcVariables< 1 > tdc_back
Tdc variables (back strips)
Detailed Description
Dsssd Variables Class
Definition at line 174 of file Dragon.hxx.
Constructor & Destructor Documentation
Variables()
dragon::Dsssd::Variables::Variables ()
Constructor, sets data to generic values.
Calls reset()
Definition at line 336 of file Dragon.cxx.
 {
   /*! Calls reset() */
   reset();
 }
Member Function Documentation
reset()
void dragon::Dsssd::Variables::reset ()
Reset all variable values to defaults.
::
Definition at line 342 of file Dragon.cxx.
References DSSSD_ADC0, DSSSD_MODULE, DSSSD_TDC0, and dragon::utils::index_fill().
 {
   /// ::
   std::fill(adc.module, adc.module + MAX_CHANNELS, DSSSD_MODULE);
   dutils::index_fill(adc.channel, adc.channel + MAX_CHANNELS, DSSSD_ADC0);
   std::fill(adc.pedestal, adc.pedestal + MAX_CHANNELS, 0);
   std::fill(adc.slope,  adc.slope + MAX_CHANNELS, 1.);
   std::fill(adc.offset, adc.offset + MAX_CHANNELS, 0.);
   tdc_front.module  = 0; // unused
   tdc_front.channel = DSSSD_TDC0;
   tdc_front.slope   = 1.;
   tdc_front.offset  = 0.;
   tdc_back.module  = 0; // unused
   tdc_back.channel = DSSSD_TDC0 + 1;
   tdc_back.slope   = 1.;
   tdc_back.offset  = 0.;
 }
set() [1/2]
bool dragon::Dsssd::Variables::set (const char * dbfile)
Set data values from an database (file or online)
Parameters
[in] dbfile Path of the odb file from which you are extracting variable values
Definition at line 363 of file Dragon.cxx.
 {
   /*!
    * \param [in] dbfile Path of the odb file from which you are extracting variable values
    */
   return do_setv(this, dbfile);
 }
set() [2/2]
bool dragon::Dsssd::Variables::set (const midas::Database * db)
Set data values from a constructed database.
Parameters
[in] Pointer to a constructed database.
Definition at line 371 of file Dragon.cxx.
References midas::Database::ReadArray(), and midas::Database::ReadValue().
 {
   /*!
    * \param [in] Pointer to a constructed database.
    */
   bool success = check_db(db, "dragon::Dsssd");
   if(success) success = db->ReadArray("/dragon/dsssd/variables/adc/module",   adc.module,   MAX_CHANNELS);
   if(success) success = db->ReadArray("/dragon/dsssd/variables/adc/channel",  adc.channel,  MAX_CHANNELS);
   if(success) success = db->ReadArray("/dragon/dsssd/variables/adc/slope",    adc.slope,    MAX_CHANNELS);
   if(success) success = db->ReadArray("/dragon/dsssd/variables/adc/offset",   adc.offset,   MAX_CHANNELS);
   if(success) success = db->ReadValue("/dragon/dsssd/variables/tdc_front/channel", tdc_front.channel);
   if(success) success = db->ReadValue("/dragon/dsssd/variables/tdc_front/slope",   tdc_front.slope);
   if(success) success = db->ReadValue("/dragon/dsssd/variables/tdc_front/offset",  tdc_front.offset);
   if(success) success = db->ReadValue("/dragon/dsssd/variables/tdc_back/channel", tdc_back.channel);
   if(success) success = db->ReadValue("/dragon/dsssd/variables/tdc_back/slope",   tdc_back.slope);
   if(success) success = db->ReadValue("/dragon/dsssd/variables/tdc_back/offset",  tdc_back.offset);
   return success;
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx