DRAGON Analyzer: dragon::Tail Class Reference
dragon::Tail Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Tail ()
Initializes data values.
void reset ()
Sets all data values to vme::NONE or other defaults.
bool set_variables (const char *dbfile)
Reads all variable values from an database (file or online)
bool set_variables (const midas::Database *db)
Reads all variable values from a constructed database.
void unpack (const midas::Event &event)
Unpack raw data into VME modules.
void calculate ()
Calculate higher-level data for each detector, or across detectors.
Public Attributes
TMidas_EVENT_HEADER header
Midas event header.
vme::Io32 io32
IO32 FPGA.
vme::V785 v785 [NUM_ADC]
CAEN v785 ADC (x2)
vme::V1190 v1190
CAEN v1190 TDC.
Dsssd dsssd
DSSSD detector.
IonChamber ic
Ionization chamber.
NaI nai
NaI detetors.
Ge ge
Germanium detector.
Mcp mcp
MCPs.
SurfaceBarrier sb
Surface barrier detectors.
HiTof tof
Time-of-flights.
TdcChannel< MAX_RF_HITS > trf
RF times.
double tcal_rf
RF tdc value.
double tcal0
Trigger [tail] tdc value.
double tcalx
Crossover [head] tdc value.
Variables variables
Variables instance.
Static Public Attributes
static const int NUM_ADC = 2
Number of ADC (caen v785) modules.
static const int MAX_RF_HITS = 5
Max number of RF hits to store.
Detailed Description
Collection of all tail detectors and VME modules
Definition at line 614 of file Dragon.hxx.
Constructor & Destructor Documentation
Tail()
dragon::Tail::Tail ()
Initializes data values.
::
Definition at line 1059 of file Dragon.cxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::Tail::calculate ()
Calculate higher-level data for each detector, or across detectors.
Read data from VME modules into data structures
Perform calibrations, higher-order calculations, etc, detector-by-detector
Calculate TOF between HI detectors
Map and calibrate "crossover" TDC
Map and calibrate RF TDC
Map and calibrate "trigger" TDC
Definition at line 1117 of file Dragon.cxx.
References dragon::utils::channel_map(), and dragon::utils::linear_calibrate().
 {
   /// - Read data from VME modules into data structures
 #ifndef DRAGON_OMIT_DSSSD
   dsssd.read_data(v785, v1190);
 #endif
 #ifndef DRAGON_OMIT_IC
   ic.read_data(v785, v1190);
 #endif
   mcp.read_data(v785, v1190);
   sb.read_data(v785, v1190);
 #ifndef DRAGON_OMIT_NAI
   nai.read_data(v785, v1190);
 #endif
 #ifndef DRAGON_OMIT_GE
   ge.read_data(v785, v1190);
 #endif
   trf.read_data(v1190);
   /// - Perform calibrations, higher-order calculations, etc, detector-by-detector
 #ifndef DRAGON_OMIT_DSSSD
   dsssd.calculate();
 #endif
 #ifndef DRAGON_OMIT_IC
   ic.calculate();
 #endif
   mcp.calculate();
   sb.calculate();
 #ifndef DRAGON_OMIT_NAI
   nai.calculate();
 #endif
 #ifndef DRAGON_OMIT_GE
   ge.calculate();
 #endif
   trf.calculate();
   /// - Calculate TOF between HI detectors
   tof.calculate(this);
   /// - Map and calibrate "crossover" TDC
   dutils::channel_map(tcalx, variables.xtdc.channel, v1190);
   dutils::linear_calibrate(tcalx, variables.xtdc);
   /// - Map and calibrate RF TDC
   dutils::channel_map(tcal_rf, variables.rf_tdc.channel, v1190);
   dutils::linear_calibrate(tcal_rf, variables.rf_tdc);
   /// - Map and calibrate "trigger" TDC
   dutils::channel_map(tcal0, variables.tdc0.channel, v1190);
   dutils::linear_calibrate(tcal0, variables.tdc0);
 }
reset()
void dragon::Tail::reset ()
Sets all data values to vme::NONE or other defaults.
::
Definition at line 1065 of file Dragon.cxx.
References dragon::utils::reset_data().
 {
   /// ::
   io32.reset();
   v1190.reset();
   for (int i=0; i< NUM_ADC; ++i) {
     v785[i].reset();
   }
   trf.reset();
 #ifndef DRAGON_OMIT_DSSSD
   dsssd.reset();
 #endif
 #ifndef DRAGON_OMIT_IC
   ic.reset();
 #endif
 #ifndef DRAGON_OMIT_NAI
   nai.reset();
 #endif
 #ifndef DRAGON_OMIT_GE
   ge.reset();
 #endif
   mcp.reset();
   sb.reset();
   tof.reset();
   dutils::reset_data(tcalx, tcal0, tcal_rf);
 }
set_variables() [1/2]
bool dragon::Tail::set_variables (const char * dbfile)
Reads all variable values from an database (file or online)
Parameters
[in] dbfile Name of the XML database file
Note
Passing "online" looks at the online ODB.
Definition at line 1169 of file Dragon.cxx.
 {
   /*!
    * \param [in] dbfile Name of the XML database file
    * \note Passing \c "online" looks at the online ODB.
    */
   return do_setv(this, dbfile);
 }
set_variables() [2/2]
bool dragon::Tail::set_variables (const midas::Database * db)
Reads all variable values from a constructed database.
Parameters
[in] Pointer to a constructed database.
Definition at line 1178 of file Dragon.cxx.
References midas::Database::ReadValue().
 {
   /*!
    * \param [in] Pointer to a constructed database.
    */
   bool success = check_db(db, "dragon::Tail::set_variables");
 #ifndef DRAGON_OMIT_DSSSD
   if(success) success = dsssd.variables.set(db);
 #endif
 #ifndef DRAGON_OMIT_IC
   if(success) success = ic.variables.set(db);
 #endif
   if(success) success = mcp.variables.set(db);
   if(success) success = sb.variables.set(db);
 #ifndef DRAGON_OMIT_NAI
   if(success) success = nai.variables.set(db);
 #endif
 #ifndef DRAGON_OMIT_GE
   if(success) success = ge.variables.set(db);
 #endif
   if(success) success = trf.variables.set(db, "/dragon/tail/variables/rf_tdc");
   if(success) success = this->variables.set(db);
   if(success) {
     dragon::utils::ChangeErrorIgnore dummy(9001);
     int period = 0;
     if(db->ReadValue("/dragon/errormessage/v1190/period", period))
       v1190.fMessagePeriod = period;
     else
       v1190.fMessagePeriod = 0;
   }
   return success;
 }
unpack()
void dragon::Tail::unpack (const midas::Event & event)
Unpack raw data into VME modules.
Parameters
[in] event Reference to a Midas event structure
Here is where the low-level work is done to take bitpacked data read directly from a MIDAS file and convert it into the corresponding measurement values of various ADC modules.
In the specific case of unpacking the dragon::Tail VME data, we delegate the work to the unpack() routines of the relevant vme::* classes.
Note
Recompile with report = true to print warning messages for missing banks
Definition at line 1092 of file Dragon.cxx.
 {
   /*!
    * \param [in] event Reference to a Midas event structure
    *
    * Here is where the low-level work is done to take bitpacked data read directly
    * from a MIDAS file and convert it into the corresponding measurement values
    * of various ADC modules.
    *
    * In the specific case of unpacking the dragon::Tail VME data, we delegate
    * the work to the unpack() routines of the relevant vme::* classes.
    *
    * \note Recompile with <c> report = true </c> to print warning messages
    *  for missing banks
    */
   const bool report = false;
   io32.unpack (event, variables.bk_io32, report);
   for (int i=0; i< NUM_ADC; ++i) {
     v785[i].unpack(event, variables.bk_adc[i], report);
   }
   v1190.unpack(event, variables.bk_tdc, report);
   event.CopyHeader(header);
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/Dragon.hxx
/Users/dragon/packages/dragon/analyzer/src/Dragon.cxx