DRAGON Analyzer: midas::Event Class Reference
midas::Event Class Reference
Derived class of TMidasEvent for timestamped dragon events.
#include <Event.hxx>
Classes
struct CompareId
Class to compare by event id.
struct CompareSerial
Class to compare by serial number.
struct CompareTrigger
Class to compare trigger times.
Public Types
typedef TMidas_EVENT_HEADER Header
Provide typdef for EventHeader_t.
Public Member Functions
Event ()
Empty constructor.
Event (const void *header, const void *data, int size, const Bank_t tsbank, double coinc_window)
Construct from event callback parameters, with TSC handling.
Event (char *buf, int size, const Bank_t tsbank, double coinc_window)
Construct from direct polling parameters, with TSC handling.
Event (const void *header, const void *data, int size)
Construct from event callback parameters, without TSC handling.
Event (char *buf, int size)
Construct from direct polling parameters, without TSC handling.
Event (const Event &other)
Copy constructor.
Event & operator= (const Event &other)
Assignment operator.
void CopyHeader (Header &destination) const
Copies event header information into another one.
bool ReadFromFile (TMidasFile &file)
Read an event from a TMidasFile.
double TriggerTime () const
Returns trigger time in uSec.
uint64_t ClockTime () const
Returns the trigger time in clock cycles.
void CopyFifo (std::vector< uint64_t > *pfifo) const
Copy fifo values to an external vector array.
bool IsCoinc (const Event &other) const
Checks if two events are coincident.
bool operator< (const Event &rhs) const
Less than operator.
void PrintSingle (FILE *where=stdout) const
Prints timestamp information for a singles event.
void PrintCoinc (const Event &other, FILE *where=stdout) const
Prints timestamp information for coincidence events.
double TimeDiff (const Event &other) const
Calculates difference of timestamps.
virtual ~Event ()
Destructor, empty.
template<typename T >
T * GetBankPointer (const Bank_t name, int *length, bool reportMissing=false, bool checkType=false) const
Bank finding routine (templated)
Static Public Attributes
static const uint32_t MAX_FIFO = 4
Number of fifo channels.
static const uint32_t TRIGGER_CHANNEL = 0
FIFO channel w/ the trigger as input.
Private Member Functions
void CopyDerived (const Event &other)
Helper function for copy constructor / assignment operator.
void Init (const char *tsbank, const void *header, const void *addr, int size)
Helper function for constructors.
Private Attributes
double fCoincWindow
Coincidence window (in us)
uint64_t fClock
Timestamp value in clock cycles since BOR.
std::vector< uint64_t > fFifo [MAX_FIFO]
TSC4 fifo values.
double fTriggerTime
Timestamp value in uSec.
Detailed Description
Derived class of TMidasEvent for timestamped dragon events.
Stores timestamp values as fields for easy access. Also provides constructors to set an event from the addresses returned by polling.
Definition at line 32 of file Event.hxx.
Member Typedef Documentation
Header
typedef TMidas_EVENT_HEADER midas::Event::Header
Provide typdef for EventHeader_t.
struct EventHeader_t {
  uint16_t fEventId;      // event id
  uint16_t fTriggerMask;  // event trigger mask
  uint32_t fSerialNumber; // event serial number
  uint32_t fTimeStamp;    // event timestamp in seconds
  uint32_t fDataSize;     // event size in bytes
 };
Definition at line 47 of file Event.hxx.
Constructor & Destructor Documentation
Event() [1/4]
midas::Event::Event (const void * header, const void * data, int size, const Bank_t tsbank, double coinc_window)
Construct from event callback parameters, with TSC handling.
Parameters
header Pointer to event header (midas::Event::Header struct)
data Pointer to the data portion of an event
size Size in bytes of the data portion of the event
tsbank Bank name of the TSC4 data; if NULL, tsc features are ignored
coinc_window Desired window to be considered a coincidence match w/ another event.
Definition at line 42 of file Event.cxx.
References Init().
                                                                                                          :
   fCoincWindow(coinc_window),
   fClock (std::numeric_limits<uint64_t>::max()),
   fTriggerTime(0.)
 {
   /*!
    * \param header Pointer to event header (midas::Event::Header struct)
    * \param data Pointer to the data portion of an event
    * \param size Size in bytes of the data portion of the event
    * \param tsbank Bank name of the TSC4 data; if NULL, tsc features are ignored
    * \param coinc_window Desired window to be considered a coincidence match w/ another event.
    */
   Init(tsbank, header, data, size);
 }
Event() [2/4]
midas::Event::Event (char * buf, int size, const Bank_t tsbank, double coinc_window)
Construct from direct polling parameters, with TSC handling.
Parameters
buf Buffer containing the entirity of the event data (header + actual data)
size Size of the data portion of the event (not including the header)
tsbank Bank name of the TSC4 data; if NULL, tsc features are ignored
coinc_window Desired window to be considered a coincidence match w/ another event.
Definition at line 57 of file Event.cxx.
References Init().
                                                                               :
   fCoincWindow(coinc_window),
   fClock (std::numeric_limits<uint64_t>::max()),
   fTriggerTime(0.)
 {
   /*!
    * \param buf Buffer containing the entirity of the event data (header + actual data)
    * \param size Size of the data portion of the event (not including the header)
    * \param tsbank Bank name of the TSC4 data; if NULL, tsc features are ignored
    * \param coinc_window Desired window to be considered a coincidence match w/ another event.
    */
   Init(tsbank, buf, buf+sizeof(midas::Event::Header), size);
 }
Event() [3/4]
midas::Event::Event (const void * header, const void * data, int size)
Construct from event callback parameters, without TSC handling.
Parameters
header Pointer to event header (midas::Event::Header struct)
data Pointer to the data portion of an event
size Size in bytes of the data portion of the event
Definition at line 83 of file Event.cxx.
References Init().
                                                                :
   fCoincWindow(0),
   fClock (std::numeric_limits<uint64_t>::max()),
   fTriggerTime(0.)
 {
   /*!
    * \param header Pointer to event header (midas::Event::Header struct)
    * \param data Pointer to the data portion of an event
    * \param size Size in bytes of the data portion of the event
    */
   Init(0, header, data, size);
 }
Event() [4/4]
midas::Event::Event (char * buf, int size)
Construct from direct polling parameters, without TSC handling.
Parameters
buf Buffer containing the entirity of the event data (header + actual data)
size Size of the data portion of the event (not including the header)
Definition at line 71 of file Event.cxx.
References Init().
                                     :
   fCoincWindow(0),
   fClock (std::numeric_limits<uint64_t>::max()),
   fTriggerTime(0.)
 {
   /*!
    * \param buf Buffer containing the entirity of the event data (header + actual data)
    * \param size Size of the data portion of the event (not including the header)
    */
   Init(0, buf, buf+sizeof(midas::Event::Header), size);
 }
Member Function Documentation
CopyDerived()
void midas::Event::CopyDerived (const Event & other) private
Helper function for copy constructor / assignment operator.
Copies all data fields and calls TMidasEvent::Copy().
Definition at line 96 of file Event.cxx.
References CopyFifo(), fClock, fCoincWindow, and fTriggerTime.
Referenced by Event(), and operator=().
 {
   /*!
    * Copies all data fields and calls TMidasEvent::Copy().
    */
   fClock       = other.fClock;
   fTriggerTime = other.fTriggerTime;
   fCoincWindow = other.fCoincWindow;
   other.CopyFifo(fFifo);
   TMidasEvent::Copy(other);
 }
CopyFifo()
void midas::Event::CopyFifo (std::vector< uint64_t > * pfifo) const
Copy fifo values to an external vector array.
Attention
Input pointer must point to an array w/ length >= 4.
Definition at line 108 of file Event.cxx.
Referenced by CopyDerived().
 {
   /*!
    * \attention Input pointer must point to an array w/ length >= 4.
    */
   for(uint32_t i=0; i< MAX_FIFO; ++i) {
     (pfifo+i)->clear();
     (pfifo+i)->resize(fFifo[i].size());
     std::copy(fFifo[i].begin(), fFifo[i].end(), pfifo[i].begin());
   }
 }
GetBankPointer()
template<typename T > T* midas::Event::GetBankPointer (const Bank_t name, int * length, bool reportMissing = false, bool checkType = false) const inline
Bank finding routine (templated)
Parameters
[in] name Name of the bank to search for
[out] Length of the returned bank
[in] reportMissing True means a warning message is printed if the bank is absent
[in] checkType Specifies whether or not to check that the template parameter matches the TID of the bank. If this parameter is set to true and the types do not match, the error is fatal.
Returns
Pointer to the beginning of the bank
Definition at line 136 of file Event.hxx.
     {
       /*!
        * \param [in] name Name of the bank to search for
        * \param [out] Length of the returned bank
        * \param [in] reportMissing True means a warning message is printed if the bank is absent
        * \param [in] checkType Specifies whether or not to check that the template parameter
        *  matches the TID of the bank. If this parameter is set to true and the types do
        *  not match, the error is fatal.
        * \returns Pointer to the beginning of the bank
        */
       void *pbk;
       int type;
       int bkfound = FindBank(name, length, &type, &pbk);
       if(!bkfound && reportMissing) {
         dragon::utils::Warning("midas::Event::GetBankPointer<T>", __FILE__, __LINE__)
           << "Couldn't find the MIDAS bank \"" << name  << "\". Skipping...\n";
       }
       if (bkfound && checkType) {
         switch (type) {
         case 1:  assert (typeid(T) == typeid(unsigned char)); break; // TID_BYTE   1
         case 2:  assert (typeid(T) == typeid(char));          break; // TID_SBYTE  2
         case 3:  assert (typeid(T) == typeid(unsigned char)); break; // TID_CHAR   3
         case 4:  assert (typeid(T) == typeid(uint16_t));      break; // TID_WORD   4
         case 5:  assert (typeid(T) == typeid(int16_t));       break; // TID_SHORT  5
         case 6:  assert (typeid(T) == typeid(uint32_t));      break; // TID_DWORD  6
         case 7:  assert (typeid(T) == typeid(int32_t));       break; // TID_INT    7
         case 8:  assert (typeid(T) == typeid(bool));          break; // TID_BOOL   8
         case 9:  assert (typeid(T) == typeid(float));         break; // TID_FLOAT  9
         case 10: assert (typeid(T) == typeid(double));        break; // TID_DOUBLE 10
         default:
           fprintf(stderr, "Unknown type id: %i\n", type);
           assert(false); break;
         }
       }
       return bkfound ? reinterpret_cast<T*>(pbk) : 0;
     }
operator<()
bool midas::Event::operator< (const Event & rhs) const inline
Less than operator.
Returns
false if the two event's trigger times are within the coincidence window; otherwise returns true if the trigger time of 'this' is less than the trigger time of 'other'
Definition at line 116 of file Event.hxx.
References IsCoinc(), and TimeDiff().
     {
       if (IsCoinc(rhs)) return false;
       return TimeDiff(rhs) < 0.;
     }
TimeDiff()
double midas::Event::TimeDiff (const Event & other) const
Calculates difference of timestamps.
Takes into account rollover by checking that the abslute difference is < 0x1fffffff
Note
'this' - 'other'
Definition at line 199 of file Event.cxx.
References fTriggerTime.
Referenced by midas::CoincEvent::CoincEvent(), IsCoinc(), midas::Event::CompareTrigger::operator()(), and operator<().
 {
   /*!
    * Takes into account rollover by checking that the abslute difference is < 0x1fffffff
    * \note 'this' - 'other'
    */
   return fTriggerTime - other.fTriggerTime;
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/midas/Event.hxx
/Users/dragon/packages/dragon/analyzer/src/midas/Event.cxx