DRAGON Analyzer: dragon::Mcp::Variables Class Reference
dragon::Mcp::Variables Class Reference
#include <Dragon.hxx>
Public Member Functions
Variables ()
Constructor, sets data to generic values.
void reset ()
Restet variables to default values.
bool set (const char *dbfile)
Set data values from an database (file or online)
bool set (const midas::Database *db)
Set data values from a constructed database.
Public Attributes
dragon::utils::AdcVariables< MAX_CHANNELS > adc
Adc variables for the anode signals.
dragon::utils::AdcVariables< 1 > tac_adc
Adc variables for the TAC signal.
dragon::utils::TdcVariables< NUM_DETECTORS > tdc
Tdc variables.
Detailed Description
MCP Variables
Definition at line 292 of file Dragon.hxx.
Constructor & Destructor Documentation
Variables()
dragon::Mcp::Variables::Variables ()
Constructor, sets data to generic values.
Calls reset()
Definition at line 550 of file Dragon.cxx.
 {
   /*! Calls reset() */
   reset();
 }
Member Function Documentation
reset()
void dragon::Mcp::Variables::reset ()
Restet variables to default values.
::
Definition at line 556 of file Dragon.cxx.
References DEFAULT_HI_MODULE, dragon::utils::index_fill(), MCP_ADC0, MCP_TAC_ADC0, and MCP_TDC0.
 {
   /// ::
   std::fill(adc.module, adc.module + MAX_CHANNELS, DEFAULT_HI_MODULE);
   dutils::index_fill(adc.channel, adc.channel + MAX_CHANNELS, MCP_ADC0);
   std::fill(adc.pedestal, adc.pedestal + MAX_CHANNELS, 0);
   std::fill(adc.offset, adc.offset + MAX_CHANNELS, 0.);
   std::fill(adc.slope, adc.slope + MAX_CHANNELS, 1.);
   tac_adc.module   = DEFAULT_HI_MODULE;
   tac_adc.channel  = MCP_TAC_ADC0;
   tac_adc.pedestal = 0;
   tac_adc.offset   = 0.;
   tac_adc.slope    = 1.;
   std::fill(tdc.module, tdc.module + NUM_DETECTORS, 0); // unused
   dutils::index_fill(tdc.channel, tdc.channel + NUM_DETECTORS, MCP_TDC0);
   std::fill(tdc.offset, tdc.offset + NUM_DETECTORS, 0.);
   std::fill(tdc.slope, tdc.slope + NUM_DETECTORS, 1.);
 }
set() [1/2]
bool dragon::Mcp::Variables::set (const char * dbfile)
Set data values from an database (file or online)
Parameters
[in] dbfile Path of the odb file from which you are extracting variable values
Definition at line 580 of file Dragon.cxx.
 {
   /*!
    * \param [in] dbfile Path of the odb file from which you are extracting variable values
    */
   return do_setv(this, dbfile);
 }
set() [2/2]
bool dragon::Mcp::Variables::set (const midas::Database * db)
Set data values from a constructed database.
Parameters
[in] db Pointer to a constructed database.
Definition at line 588 of file Dragon.cxx.
References midas::Database::ReadArray(), and midas::Database::ReadValue().
 {
   /*!
    * \param [in] db Pointer to a constructed database.
    */
   bool success = check_db(db, "dragon::Mcp");
   if(success) success = db->ReadArray("/dragon/mcp/variables/adc/channel",  adc.channel,  MAX_CHANNELS);
   if(success) success = db->ReadArray("/dragon/mcp/variables/adc/module",   adc.module,   MAX_CHANNELS);
   if(success) success = db->ReadArray("/dragon/mcp/variables/adc/slope",    adc.slope,    MAX_CHANNELS);
   if(success) success = db->ReadArray("/dragon/mcp/variables/adc/offset",   adc.offset,   MAX_CHANNELS);
   if(success) success = db->ReadValue("/dragon/mcp/variables/tac_adc/channel",  tac_adc.channel);
   if(success) success = db->ReadValue("/dragon/mcp/variables/tac_adc/module",   tac_adc.module);
   if(success) success = db->ReadValue("/dragon/mcp/variables/tac_adc/slope",    tac_adc.slope);
   if(success) success = db->ReadValue("/dragon/mcp/variables/tac_adc/offset",   tac_adc.offset);
   if(success) success = db->ReadArray("/dragon/mcp/variables/tdc/channel", tdc.channel, NUM_DETECTORS);
   if(success) success = db->ReadArray("/dragon/mcp/variables/tdc/slope",   tdc.slope,   NUM_DETECTORS);
   if(success) success = db->ReadArray("/dragon/mcp/variables/tdc/offset",  tdc.offset,  NUM_DETECTORS);
   return success;
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx