DRAGON Analyzer: dragon::TdcChannel< MAX_HITS >::Variables Class Reference
dragon::TdcChannel< MAX_HITS >::Variables Class Reference
TcdChannel variables.
#include <Dragon.hxx>
Public Member Functions
Variables ()
Constructor, sets data to generic values.
void reset ()
Reset variables to default values.
bool set (const char *dbfile, const char *dir)
Set data values from an database (file or online)
bool set (const midas::Database *db, const char *dir)
Set data values from a constructed database.
Public Attributes
dragon::utils::TdcVariables< 1 > tdc
TDC variables, common for all hits.
Detailed Description
template<int MAX_HITS>
class dragon::TdcChannel< MAX_HITS >::Variables
TcdChannel variables.
Definition at line 472 of file Dragon.hxx.
Constructor & Destructor Documentation
Variables()
template<int MAX_HITS> dragon::TdcChannel< MAX_HITS >::Variables::Variables () inline
Constructor, sets data to generic values.
::
Definition at line 1060 of file Dragon.hxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
reset()
template<int MAX_HITS> void dragon::TdcChannel< MAX_HITS >::Variables::reset () inline
Reset variables to default values.
Implementation:
Definition at line 1067 of file Dragon.hxx.
References HEAD_CROSS_TDC.
 {
   /// Implementation:
   tdc.channel = HEAD_CROSS_TDC - 2;
   tdc.slope  = 1.;
   tdc.offset = 0.;
 }
set() [1/2]
template<int MAX_HITS> bool dragon::TdcChannel< MAX_HITS >::Variables::set (const char * dbfile, const char * dir) inline
Set data values from an database (file or online)
Parameters
dbfile Name of midas database file (or "online")
dir ODB path of the variables for this TDC channel
Definition at line 1076 of file Dragon.hxx.
References midas::Database::IsZombie().
 {
   /// \param dbfile Name of midas database file (or "online")
   /// \param dir ODB path of the variables for this TDC channel
   ///
   midas::Database db(dbfile);
   if(db.IsZombie()) {
     dragon::utils::Error("TdcChannel::Variables::set", __FILE__, __LINE__)
       << "Zombie database: " << dbfile;
     return false;
   }
   return set(&db, dir);
 }
set() [2/2]
template<int MAX_HITS> bool dragon::TdcChannel< MAX_HITS >::Variables::set (const midas::Database * db, const char * dir) inline
Set data values from a constructed database.
Parameters
db Pointer to valid midas database
dir ODB path of the variables for this TDC channel (note: no trailing slash).
Definition at line 1092 of file Dragon.hxx.
References midas::Database::IsZombie(), and midas::Database::ReadValue().
 {
   /// \param db Pointer to valid midas database
   /// \param dir ODB path of the variables for this TDC channel (note: no trailing slash).
   ///
   std::string dirname = dir + std::string("/");
   bool success = db && !db->IsZombie();
   if(!success) {
     dragon::utils::Error("dragon::TdcChannel::Variables::Set", __FILE__, __LINE__)
       << "Invalid database: 0x" << db;
   }
   if(success) success = db->ReadValue( (dirname + std::string("channel")).c_str(), tdc.channel);
   if(success) success = db->ReadValue( (dirname + std::string("slope")).c_str(),   tdc.slope);
   if(success) success = db->ReadValue( (dirname + std::string("offset")).c_str(),  tdc.offset);
   return success;
 }
The documentation for this class was generated from the following file:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx