DRAGON Analyzer: dragon::Kin2Body Class Reference
dragon::Kin2Body Class Reference
Public Member Functions
Kin2Body (const char *projectile, const char *target, Double_t enregy=0, const char *frame="CM", Int_t qb=0)
Default ctor for radiative capture.
Kin2Body (const char *projectile, const char *target, const char *ejectile, Double_t enregy=0, const char *frame="CM", Int_t qb=0)
Overload ctor for particle ejectiles.
Double_t CalcTLabTheta (Double_t theta, const char *which, Bool_t negative=kFALSE)
Double_t GetMaxAngle (const char *which)
Get CM energy.
TMultiGraph * PlotTLabvsThetaLab (Option_t *option_e="", Option_t *option_r="")
Public Attributes
Double_t fBeta_b
Beam velocity in units of c.
Double_t fBeta0rec
Recoil velocity in units of c (0° γ)
Double_t fBeta90rec
Recoil velocity in units of c (90° γ)
Double_t fBeta180rec
Recoil velocity in units of c (180° γ)
Double_t fBrho
Beam magnetic rigidity in T*m.
Double_t fChi
CM rapidity.
Double_t fEb
Total energy of beam nuclide [MeV].
Double_t fEcm
Center of mass kinetic energy [MeV].
Double_t fE0rec
Total energy of recoil nuclide (0° γ) [MeV].
Double_t fE90rec
Total energy of recoil nuclide (90° γ) [MeV].
Double_t fE180rec
Total energy of recoil nuclide (180° γ) [MeV].
Double_t fEx
Excitation energy [MeV].
Double_t fGamma_b
Lorentz factor of beam [MeV].
Double_t fGamma0rec
Lorentz factor of recoil (0° γ) [MeV].
Double_t fGamma90rec
Lorentz factor of recoil (90° γ) [MeV].
Double_t fGamma180rec
Lorentz factor of recoil (180° γ) [MeV].
Double_t fM1amu
Beam mass [AMU].
Double_t fM1
Beam mass [MeV/c^2].
Double_t fM2
Target mass [MeV/c^2].
Double_t fM3
Ejectile mass [MeV/c^2].
Double_t fM4
Recoil mass [MeV/c^2].
Double_t fMcpTofb
Beam MCP TOF [ns].
Double_t fMcpTofrec0
Recoil MCP TOF (0° γ) [MeV] [ns].
Double_t fMcpTofrec90
Recoil MCP TOF (90° γ) [MeV] [ns].
Double_t fMcpTofrec180
Recoil MCP TOF (180° γ) [MeV] [ns].
Double_t fPb
momentum of projectile
Double_t fPcm
CM momentum of projectile and target.
Double_t fPprime
CM momentum of ejectile and recoil.
Double_t fQrxn
Reaction Q value [MeV].
Int_t fqb
Beam charge state.
Double_t fS
Invariant 4-momentum.
Double_t fSepTofb
Beam separator TOF [ns].
Double_t fSepTofrec0
Recoil separator TOF (0° γ) [μs].
Double_t fSepTofrec90
Recoil separator TOF (90° γ) [μs].
Double_t fSepTofrec180
Recoil separator TOF (180° γ) [μs].
Double_t fTb
Total kinetic energy of the beam in the laboratory frame MeV.
Double_t fTbA
Total kinetic energy of the beam in the laboratory frame A MeV.
Double_t fTtgt
Total kinetic energy of the the target frame.
Double_t fV2b
Total kinetic energy of the the beam in MeV / u.
const TAtomicMassTable::Nucleus_t * fProj
Projectile Nuclide.
const TAtomicMassTable::Nucleus_t * fTgt
Target Nuclide.
const TAtomicMassTable::Nucleus_t * fEj
Ejectile Nuclide.
const TAtomicMassTable::Nucleus_t * fRec
Recoil Nuclide.
const char * fRxnString
Reaction string.
const char * fProjString
Projectile string.
const char * fTgtString
Projectile string.
const char * fEjString
Projectile string.
const char * fRecString
Projectile string.
Private Member Functions
void Init (const char *projectile, const char *target, Double_t energy, const char *frame, Int_t qb)
void Init (const char *projectile, const char *target, const char *ejectile, Double_t energy, const char *frame, Int_t qb)
void Set4Mom (Double_t energy, const char *frame)
Detailed Description
Definition at line 40 of file Kin2Body.hxx.
Constructor & Destructor Documentation
dragon::Kin2Body::Kin2Body (const char * projectile, const char * target, Double_t energy = 0, const char * frame = "CM", Int_t qb = 0)
Default ctor for radiative capture.
Class dragon::Kin2Body //////////////////////////////// Class for relativistic 2 body reaction kinematics
Calculates relativistic kinematic relationships for 2 body reactions. Consider the reaction
where, by convention, the projectile with mass and kinetic energy and is incident on a (stationary) target of mass . The kinematics of this reaction can be described by its (invariant) squared 4-momentum
Default ctor for radiative capture Sets beam and target masses from AME12 compilation. Energies are initially unset, use SetE*() functions to specify an energy.
Parameters
projectile string specifying projectile nucleus (e.g. - "7Be", "22Ne", etc.)
target string specifying projectile nucleus (e.g. - "p", "1H", "4He", "alpha", etc.)
projectile string specifying ejectile nucleus (e.g. - "p", "d", etc.)
energy beam energy in units corresponding to specified frame string
frame string specifying frame / units of beam energy
qb charge state of beam (default = 0)
Definition at line 58 of file Kin2Body.cxx.
References Init().
 {
   Init(projectile, target, energy, frame, qb);
 }
dragon::Kin2Body::Kin2Body (const char * projectile, const char * target, const char * ejectile, Double_t energy = 0, const char * frame = "CM", Int_t qb = 0)
Overload ctor for particle ejectiles.
Overloaded Ctor for particle ejectiles Sets beam and target masses from AME12 compilation. Energies are initially unset, use SetE*() functions to specify an energy.
Parameters
projectile string specifying projectile nucleus (e.g. - "7Be", "22Ne", etc.)
target string specifying projectile nucleus (e.g. - "p", "1H", "4He", "alpha", etc.)
projectile string specifying ejectile nucleus (e.g. - "p", "d", etc.)
energy beam energy in units corresponding to specified frame string
frame string specifying frame / units of beam energy
qb charge state of beam (default = 0)
Definition at line 76 of file Kin2Body.cxx.
 {
   Init(projectile, target, ejectile, energy, frame, qb);
 }
Member Function Documentation
Double_t dragon::Kin2Body::CalcTLabTheta (Double_t theta, const char * which, Bool_t negative = kFALSE)
Calculate the energy of the ejectile as a function of angle
Parameters
theta angle of ejectile / recoil in degrees
which ejectile or recoil
Definition at line 197 of file Kin2Body.cxx.
 {
   Double_t mass;
   if (strncmp(which, "recoil", 6) == 0){
     mass = fM4;
   } else {
     mass = fM3;
   }
   if (theta == 90.0){
     if (mass*sinh(fChi) / fPprime > 1){
       return 0.0;
     } else {
       Double_t p = fPprime*sqrt(1 - pow(mass*sinh(fChi) / fPprime,2) / (1 + pow(sinh(fChi),2)) );
       Double_t T = sqrt(p*p + mass*mass) - mass;
       if (T < 0.001) {
         return 0;
       } else {
         return T;
       }
     }
   }
   if (theta >= GetMaxAngle(which)) {
     theta = GetMaxAngle(which);
     theta /= 180.;
     theta *= TMath::Pi();
     Double_t pe = cos(theta)*sinh(fChi)*sqrt(mass*mass + fPprime*fPprime);
     pe /= ( 1+pow(sin(theta)*sinh(fChi),2) );
     return sqrt(pe*pe + mass*mass) - mass;
   } else if (!negative){
     theta /= 180.;
     theta *= TMath::Pi();
     Double_t pe = cos(theta)*sinh(fChi)*sqrt(mass*mass + fPprime*fPprime);
     pe += cosh(fChi)*sqrt( fPprime*fPprime - pow(mass*sin(theta)*sinh(fChi),2) );
     pe /= ( 1+pow(sin(theta)*sinh(fChi),2) );
     return sqrt(pe*pe + mass*mass) - mass;
   } else {
     theta /= 180.;
     theta *= TMath::Pi();
     Double_t pe = cos(theta)*sinh(fChi)*sqrt(mass*mass + fPprime*fPprime);
     pe -= cosh(fChi)*sqrt( fPprime*fPprime - pow(mass*sin(theta)*sinh(fChi),2) );
     pe /= ( 1+pow(sin(theta)*sinh(fChi),2) );
     return sqrt(pe*pe + mass*mass) - mass;
   }
 }
Double_t dragon::Kin2Body::GetMaxAngle (const char * which)
Get CM energy.
Get maximum cone half angle for ejectile or recoil
Parameters
which index of particle
Definition at line 276 of file Kin2Body.cxx.
 {
   if (strncmp(which, "ejectile", 8) == 0){
     if ( fabs( fPprime / (fM3*sinh(fChi)) ) >= 1){
       if ( CalcTLabTheta(90, which) > 0){
         return 180.;
       } else {
         return 90.;
       }
     } else {
       return 180*asin(fPprime / (fM3*sinh(fChi))) / TMath::Pi();
     }
   } else if (strncmp(which, "recoil", 6) == 0){
     if ( fabs( fPprime / (fM4*sinh(fChi)) ) >= 1){
       if ( CalcTLabTheta(90, which) > 0){
         return 180.;
       } else {
         return 90.;
       }
     } else {
       return 180*asin(fPprime / (fM4*sinh(fChi))) / TMath::Pi();
     }
   } else if (strncmp(which, "residue", 7) == 0) {
     if ( fabs( fPprime / (fM4*sinh(fChi)) ) >= 1){
       if ( CalcTLabTheta(90, "recoil") > 0){
         return 180.;
       } else {
         return 90.;
       }
     } else {
       return 180*asin(fPprime / (fM4*sinh(fChi))) / TMath::Pi();
     }
   } else {
     dutils::Error("Kin2Body::GetMaxAngle", __FILE__, __LINE__) << "particle string " << which << " invalid; must one of \"ejectile\", \"recoil\", or \"residue.\"\n";
     return 0;
   }
 }
void dragon::Kin2Body::Init (const char * projectile, const char * target, Double_t energy, const char * frame, Int_t qb) private
Ctor helper for initializing radiative capture kinematics variables
Definition at line 85 of file Kin2Body.cxx.
References TAtomicMassTable::GetNucleus(), TAtomicMassTable::IonMass(), TAtomicMassTable::IonMassAMU(), dragon::Constants::Ldra(), dragon::Constants::Lmcp(), and TAtomicMassTable::QValue().
Referenced by Kin2Body().
 {
   TAtomicMassTable mt; // AME16
   fProj    = mt.GetNucleus(projectile);
   fTgt     = mt.GetNucleus(target);
   fRec     = mt.GetNucleus(fProj->fZ+fTgt->fZ, fProj->fA+fTgt->fA);
   fRxnString  = Form("{}^{%i}%s(^{%i}%s,#gamma)^{%i}%s",fTgt->fA,fTgt->fSymbol,fProj->fA,fProj->fSymbol, fRec->fA, fRec->fSymbol);
   fProjString = Form("{}^{%i}%s",fProj->fA,fProj->fSymbol);
   fTgtString  = Form("{}^{%i}%s",fTgt->fA,fTgt->fSymbol);
   fEjString   = "#gamma";
   fRecString  = Form("{}^{%i}%s",fRec->fA,fRec->fSymbol);
   fM1      = mt.IonMass(fProj->fZ, fProj->fA, 0) / 1.e3;
   fM1amu   = mt.IonMassAMU(fProj->fZ, fProj->fA, 0);
   fM2      = mt.IonMass(fTgt->fZ, fTgt->fA, 0) / 1.e3;
   fM3      = 0;
   fM4      = mt.IonMass(fRec->fZ, fRec->fA, 0) / 1.e3;
   fqb      = qb;
   fQrxn    = mt.QValue(projectile, target, "g", false) / 1.e3;
   Set4Mom(energy, frame);
   fPcm     = sqrt( (pow(fS - fM1*fM1 - fM2*fM2, 2) - 4*pow(fM1*fM2, 2) ) / (4*fS) );
   fPprime  = sqrt( (pow(fS - fM4*fM4, 2) ) / (4*fS) );
   fChi     = log( (fPcm + sqrt(fM2*fM2 + fPcm*fPcm) ) / fM2 );
   fEcm     = sqrt(fS) - fM1 - fM2;
   fEx      = fEcm + fQrxn;
   fTb      = ( fS - pow(fM1 + fM2,2) ) / (2*fM2);
   fPb      = sqrt(pow(fTb,2) + 2*fTb*fM1);
   fTtgt    = ( fS - pow(fM1 + fM2,2) ) / (2*fM1);
   fTbA     = fTb / fProj->fA;
   fV2b     = fTb / fM1amu;
   if (fqb != 0){
     fBrho  = ( 3.3356 / (1.e3*fqb) )*sqrt( ( (fS - pow(fM1+fM2,2)) / (2*fM2) )*( (fS - pow(fM1+fM2,2)) / (2*fM2) + 2*fM1) );
   } else {
     fBrho  = 0;
   }
   fEb           = fTb + fM1;
   fGamma_b      = fEb / fM1;
   fBeta_b       = sqrt(1 - 1/pow(fGamma_b,2));
   fMcpTofb      = dragon::Constants::Lmcp() / (fBeta_b*TMath::C())*1.0e9;
   fSepTofb      = dragon::Constants::Ldra() / (fBeta_b*TMath::C())*1.0e6;
   fE90rec       = sqrt(fPb*fPb + fM4*fM4);
   fGamma90rec   = fE90rec / fM4;
   fBeta90rec    = sqrt(1 - 1/pow(fGamma90rec,2));
   fMcpTofrec90  = dragon::Constants::Lmcp() / (fBeta90rec*TMath::C())*1.0e9;
   fSepTofrec90  = dragon::Constants::Ldra() / (fBeta90rec*TMath::C())*1.0e6;
   fE0rec        = sqrt( pow(fPb*(1 - fEx / sqrt(fEb*fEb - fM1*fM1)),2) + fM4*fM4 );
   fGamma0rec    = fE0rec / fM4;
   fBeta0rec     = sqrt(1 - 1/pow(fGamma0rec,2));
   fMcpTofrec0   = dragon::Constants::Lmcp() / (fBeta0rec*TMath::C())*1.0e9;
   fSepTofrec0   = dragon::Constants::Ldra() / (fBeta0rec*TMath::C())*1.0e6;
   fE180rec      = sqrt( pow(fPb*(1 + fEx / sqrt(fEb*fEb - fM1*fM1)),2) + fM4*fM4 );
   fGamma180rec  = fE180rec / fM4;
   fBeta180rec   = sqrt(1 - 1/pow(fGamma180rec,2));
   fMcpTofrec180 = dragon::Constants::Lmcp() / (fBeta180rec*TMath::C())*1.0e9;
   fSepTofrec180 = dragon::Constants::Ldra() / (fBeta180rec*TMath::C())*1.0e6;
 }
void dragon::Kin2Body::Init (const char * projectile, const char * target, const char * ejectile, Double_t energy, const char * frame, Int_t qb) private
Ctor helper for initializing kinematics variables (particle ejectiles)
Definition at line 145 of file Kin2Body.cxx.
References TAtomicMassTable::GetNucleus(), TAtomicMassTable::IonMass(), TAtomicMassTable::IonMassAMU(), and TAtomicMassTable::QValue().
 {
   TAtomicMassTable mt; // AME16
   fProj = mt.GetNucleus(projectile);
   fTgt  = mt.GetNucleus(target);
   fEj   = mt.GetNucleus(ejectile);
   fRec  = mt.GetNucleus(fProj->fZ+fTgt->fZ-fEj->fZ, fProj->fA+fTgt->fA-fEj->fA);
   if ( strncmp(projectile, ejectile, 5) == 0 ){ // elastic scattering
     std::cout << "Elastic scattering!\n";
     fM1      = mt.IonMass(fProj->fZ, fProj->fA, 0) / 1.e3;
     fM1amu   = mt.IonMassAMU(fProj->fZ, fProj->fA, 0);
     fM2      = mt.IonMass(fTgt->fZ, fTgt->fA, 0) / 1.e3;
     fM3      = fM1;
     fM4      = fM2;
   } else {
     fM1      = mt.IonMass(fProj->fZ, fProj->fA, 0) / 1.e3;
     fM1amu   = mt.IonMassAMU(fProj->fZ, fProj->fA, 0);
     fM2      = mt.IonMass(fTgt->fZ, fTgt->fA, 0) / 1.e3;
     fM3      = mt.IonMass(fEj->fZ, fEj->fA, 0) / 1.e3;
     fM4      = mt.IonMass(fRec->fZ, fRec->fA, 0) / 1.e3;
   }
   fRxnString = Form("{}^{%i}%s(^{%i}%s,{}^{%i}%s)^{%i}%s",fTgt->fA,fTgt->fSymbol,fProj->fA,fProj->fSymbol,fEj->fA,fEj->fSymbol, fRec->fA, fRec->fSymbol);
   fProjString = Form("{}^{%i}%s",fProj->fA,fProj->fSymbol);
   fTgtString = Form("{}^{%i}%s",fTgt->fA,fTgt->fSymbol);
   fEjString = Form("{}^{%i}%s",fEj->fA,fEj->fSymbol);
   fRecString = Form("{}^{%i}%s",fRec->fA,fRec->fSymbol);
   fqb      = qb;
   fQrxn    = mt.QValue(projectile, target, ejectile, false) / 1.e3;
   Set4Mom(energy, frame);
   fPcm     = sqrt( (pow(fS - fM1*fM1 - fM2*fM2, 2) - 4*pow(fM1*fM2, 2) ) / (4*fS) );
   fPprime  = sqrt( (pow(fS - fM3*fM3 - fM4*fM4, 2) - 4*pow(fM3*fM4, 2) ) / (4*fS) );
   fPb      = sqrt(pow(fTb,2) + 2*fTb*fM1);
   fChi     = log( (fPcm + sqrt(fM2*fM2 + fPcm*fPcm) ) / fM2 );
   fEcm     = sqrt(fS) - fM1 - fM2;
   fEx      = fEcm + fQrxn;
   fTb      = ( fS - pow(fM1 + fM2,2) ) / (2*fM2);
   fTtgt    = ( fS - pow(fM1 + fM2,2) ) / (2*fM1);
   fTbA     = fTb / fProj->fA;
   fV2b     = fTb / fM1amu;
   if (fqb != 0){
     fBrho  = ( 3.3356 / (1.e3*fqb) )*sqrt( ( (fS - pow(fM1+fM2,2)) / (2*fM2) )*( (fS - pow(fM1+fM2,2)) / (2*fM2) + 2*fM1) );
   } else {
     fBrho  = 0;
   }
 }
void dragon::Kin2Body::Set4Mom (Double_t energy, const char * frame) private
Set 4-momentum of system
Parameters
energy Energy of beam
frame string specifying frame / units of beam energy
Definition at line 249 of file Kin2Body.cxx.
 {
   if (strncmp(frame, "CM", 2) == 0){
     fS = pow(fM1 + fM2 + energy, 2);
   } else if (strncmp(frame, "Lab", 3) == 0){
     fS  = pow(fM1 + fM2,2) + 2*fM2*energy;
   } else if (strncmp(frame, "Target", 6) == 0){
     fS  = pow(fM1 + fM2,2) + 2*fM1*energy;
   } else if (strncmp(frame, "ALab", 4) == 0){
     fS  = pow(fM1 + fM2,2) + 2*fM2*fProj->fA*energy;
   } else if (strncmp(frame, "V2", 2) == 0){
     fS  = pow(fM1 + fM2,2) + 2*fM2*fM1amu*energy;
   } else if (strncmp(frame, "Excitation", 10) == 0){
     fS  = pow(fM1 + fM2 + energy-fQrxn, 2);
   } else if (strncmp(frame, "Brho",4) == 0){
     fTb = (-2*fM1 + sqrt(4*(fM1*fM1 + pow(fqb*energy / 3.3356,2) ) ) ) / 2;
     fS  = pow(fM1 + fM2,2) + 2*fM2*fTb;
   } else {
     dutils::Error("Kin2Body::Set4Mom", __FILE__, __LINE__) << "frame string \"" << frame << "\" invalid; must match one of \"CM\", \"Lab\", \"Target\", \"LabA\", \"V2\", \"Excitation\", \"Brho\".\n";
   }
 }
The documentation for this class was generated from the following files:
/Users/dragon/packages/dragon/analyzer/src/utils/Kin2Body.hxx
/Users/dragon/packages/dragon/analyzer/src/utils/Kin2Body.cxx