DRAGON Analyzer: dragon::Coinc Class Reference
dragon::Coinc Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
Coinc ()
Empty.
Coinc (const Head &head_, const Tail &tail_)
Construct from a head and tail event.
void reset ()
Reset all modules (set data to defaults)
bool set_variables (const char *dbfile)
Reads all variable values from an database (file or online)
bool set_variables (const midas::Database *db)
Reads all variable values from a constructed database.
void compose_event (const Head &head_, const Tail &tail_)
Copy data from head and tail coincidence events.
void unpack (const midas::CoincEvent &coincEvent)
Unpack raw data from a midas::CoincEvent.
void calculate ()
Calculates both singles and coincidence parameters.
Public Attributes
Head head
Head (gamma-ray) part of the event.
Tail tail
Tail (heavy-ion) part of the event.
double xtrig
(tail - head) io32 trigger times (usec)
double xtofh
Crossover time-of-flight from the head TDC.
double xtoft
Crossover time-of-flight from the tail TDC.
Variables variables
Variables instance.
Detailed Description
A complete Dragon (coincidence) event
Definition at line 722 of file Dragon.hxx.
Constructor & Destructor Documentation
Coinc() [1/2]
dragon::Coinc::Coinc ()
Empty.
::
Definition at line 1438 of file Dragon.cxx.
References dragon::Scaler::reset().
 {
   /// ::
   reset();
 }
Coinc() [2/2]
dragon::Coinc::Coinc (const Head & head_, const Tail & tail_)
Construct from a head and tail event.
::
Definition at line 1444 of file Dragon.cxx.
 {
   /// ::
   compose_event(head_, tail_);
 }
Member Function Documentation
calculate()
void dragon::Coinc::calculate ()
Calculates both singles and coincidence parameters.
Does head and tail calculations.
Definition at line 1500 of file Dragon.cxx.
References dragon::utils::calculate_tof().
 {
   /*!
    * Does head and tail calculations.
    */
   head.calculate();
   tail.calculate();
   xtrig = dutils::calculate_tof(tail.io32.tsc4.trig_time, head.io32.tsc4.trig_time);
   xtoft = dutils::calculate_tof(tail.tcal0, tail.tcalx);
   xtofh = dutils::calculate_tof(head.tcalx, head.tcal0);
 }
compose_event()
void dragon::Coinc::compose_event (const Head & head_, const Tail & tail_)
Copy data from head and tail coincidence events.
Parameters
[in] head_ Head (gamma-ray) event
[in] tail_ Tail (heavy-ion) event
Definition at line 1480 of file Dragon.cxx.
 {
   /*!
    * \param [in] head_ Head (gamma-ray) event
    * \param [in] tail_ Tail (heavy-ion) event
    */
   head = head_;
   tail = tail_;
 }
reset()
void dragon::Coinc::reset ()
Reset all modules (set data to defaults)
::
Definition at line 1450 of file Dragon.cxx.
References dragon::utils::reset_data().
 {
   /// ::
   head.reset();
   tail.reset();
   dutils::reset_data(xtrig, xtofh, xtoft);
 }
set_variables() [1/2]
bool dragon::Coinc::set_variables (const char * dbfile)
Reads all variable values from an database (file or online)
Parameters
[in] dbfile Name of the ODB file (*.xml or *.mid) from which to read
Note
Passing "online" looks at the experiment's ODB, if connected
Definition at line 1458 of file Dragon.cxx.
 {
   /*!
    * \param [in] dbfile Name of the ODB file (*.xml or *.mid) from which to read
    * \note Passing \c "online" looks at the experiment's ODB, if connected
    */
   return do_setv(this, dbfile);
 }
set_variables() [2/2]
bool dragon::Coinc::set_variables (const midas::Database * db)
Reads all variable values from a constructed database.
Parameters
[in] db Pointer to a constructed database from which to read the variables.
Definition at line 1467 of file Dragon.cxx.
References dragon::Scaler::Variables::set(), and dragon::Scaler::variables.
 {
   /*!
    * \param [in] db Pointer to a constructed database from which to read the variables.
    */
   bool success = check_db(db, "dragon::Coinc::set_varibles");
   if(success) success = head.set_variables(db);
   if(success) success = tail.set_variables(db);
   if(success) success = variables.set(db);
   return success;
 }
unpack()
void dragon::Coinc::unpack (const midas::CoincEvent & coincEvent)
Unpack raw data from a midas::CoincEvent.
Calls the respective unpack() functions on the head and tail part of the coincidence events.
Definition at line 1490 of file Dragon.cxx.
References midas::CoincEvent::fGamma, and midas::CoincEvent::fHeavyIon.
 {
   /*!
    * Calls the respective unpack() functions on the head and tail part
    * of the coincidence events.
    */
   head.unpack( *(coincEvent.fGamma) );
   tail.unpack( *(coincEvent.fHeavyIon) );
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx