DRAGON Analyzer: dragon::IonChamber Class Reference
dragon::IonChamber Class Reference
#include <Dragon.hxx>
Classes
class Variables
Public Member Functions
IonChamber ()
Constructor, initialize data.
void reset ()
Reset all data to VME::none.
void read_data (const vme::V785 adcs[], const vme::V1190 &tdc)
Read midas event data.
void calculate ()
Calculate higher-level parameters.
Public Attributes
double anode [MAX_CHANNELS]
Calibrated anode signals.
double tcal [MAX_TDC]
Time signals.
double sum
Sum of anode signals.
IonChamber::Variables variables
Variables instance.
Static Public Attributes
static const int MAX_CHANNELS = 5
Number of anodes.
static const int MAX_TDC = 4
Number of time signals.
Detailed Description
Ionization chamber
Definition at line 202 of file Dragon.hxx.
Constructor & Destructor Documentation
IonChamber()
dragon::IonChamber::IonChamber ()
Constructor, initialize data.
::
Definition at line 397 of file Dragon.cxx.
 {
   /// ::
   reset();
 }
Member Function Documentation
calculate()
void dragon::IonChamber::calculate ()
Calculate higher-level parameters.
Calibrates anode and time signals, calculates anode sum
Definition at line 421 of file Dragon.cxx.
References dragon::utils::calculate_sum(), dragon::utils::is_valid_any(), and dragon::utils::linear_calibrate().
 {
   /*!
    * Calibrates anode and time signals, calculates anode sum
    */
   dutils::linear_calibrate(anode, MAX_CHANNELS, variables.adc);
   dutils::linear_calibrate(tcal, MAX_TDC, variables.tdc);
   if(dutils::is_valid_any(anode, MAX_CHANNELS)) {
     sum = dutils::calculate_sum(anode, anode + MAX_CHANNELS);
   }
 }
read_data()
void dragon::IonChamber::read_data (const vme::V785 adcs[], const vme::V1190 & tdc)
Read midas event data.
Parameters
modules Heavy-ion module structure
[in] v1190_trigger_ch Channel number of the v1190b trigger
Definition at line 411 of file Dragon.cxx.
References dragon::utils::channel_map().
 {
   /*!
    * \param modules Heavy-ion module structure
    * \param [in] v1190_trigger_ch Channel number of the v1190b trigger
    */
   dutils::channel_map(anode, MAX_CHANNELS, variables.adc.channel, variables.adc.module, adcs);
   dutils::channel_map(tcal, MAX_TDC, variables.tdc.channel, tdc);
 }
reset()
void dragon::IonChamber::reset ()
Reset all data to VME::none.
::
Definition at line 403 of file Dragon.cxx.
References dragon::utils::reset_array(), and dragon::utils::reset_data().
 {
   /// ::
   dutils::reset_array(MAX_CHANNELS, anode);
   dutils::reset_array(MAX_TDC, tcal);
   dutils::reset_data(sum);
 }
The documentation for this class was generated from the following files:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.hxx
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/Dragon.cxx