DRAGON Analyzer: dragon Namespace Reference
dragon Namespace Reference
Namespaces
utils
Encloses various 'utility' functions.
Classes
class ASelector
Generic selector class.
class BeamNorm
Class to handle calculation of beam normalization.
class Bgo
class Coinc
class CoincBusytime
Class to calculate total busy time for coincidence events.
class CoincSelector
Selector class for coincidence events.
class Constants
Class containing useful physical constants as static members.
class CrossSectionCalculator
Class to calculate cross sections from target data and yield.
class Dsssd
class DsssdCalibrate
Class to recalibrate the DSSSD channels.
class Epics
class Ge
class Head
class HeadSelector
Selector class for head singles events.
class HiTof
Generic time-of-flight class for heavy-ion detectors.
class IonChamber
class Kin2Body
class LabCM
Helper class for lab -> CM conversions (fully relativistic)
class LinearFitter
class LiveTimeCalculator
Live time calculator.
class Mcp
class MetricPrefix
Utility class to convert metrix prefix strings into multiplication factors.
class NaI
struct NoData
Determines "throwaway" data value when some parameter is absent.
class ResonanceStrengthCalculator
Class to calculate resonance strength (omega-gamma) from yield & stopping power measurements.
class RossumData
Class to extract data from rossum output files.
class RunParameters
class Scaler
class ScalerSelector
Selector class for scaler events.
class StoppingPowerCalculator
Stopping power calculator.
class SurfaceBarrier
class Tail
class TailSelector
Selector class for tail singles events.
class TdcChannel
Class for tdc stuff.
class TTreeFilter
Filters TChains (or TTrees) based on cut conditions.
class Unpacker
Handles unpacking event data
Enumerations
enum MeasurementType_t { kGammaSingles = 1, kHiSingles = 3, kCoinc = 5 }
Functions
void MakeChains (const char *prefix, const Int_t *runnumbers, Int_t nruns, const char *format="$DH/rootfiles/run%d.root", Bool_t sonik=kFALSE)
Chain together all trees in multiple DRAGON files.
void MakeChains (const Int_t *runnumbers, Int_t nruns, const char *format="$DH/rootfiles/run%d.root", Bool_t sonik=kFALSE)
Chain together all trees in multiple DRAGON files.
void MakeChains (const std::vector< Int_t > &runnumbers, const char *format="$DH/rootfiles/run%d.root", Bool_t sonik=kFALSE)
Chain together trees using a vector instead of array.
void MakeChains (const char *prefix, const std::vector< Int_t > &runnumbers, const char *format="$DH/rootfiles/run%d.root", Bool_t sonik=kFALSE)
Chain together trees using a vector instead of array.
void FriendChain (TChain *chain, const char *friend_name, const char *friend_alias, const char *format="$DH/rootfiles/run%d.root", const char *friend_format="$DH/rootfiles/run%d_dsssd_recal.root")
Add another chain of files as a friend to an existing one.
TFile * OpenRun (int runnum, const char *format="$DH/rootfiles/run%d.root")
Open a file just by run number.
template<class InputIterator >
UDouble_t MeasurementWeightedAverage (InputIterator begin, InputIterator end)
Calculate weighted average of measurements.
Detailed Description
Encloses dragon detector classes
Function Documentation
FriendChain()
void dragon::FriendChain (TChain * chain, const char * friend_name, const char * friend_alias, const char * format = "$DH/rootfiles/run%d.root", const char * friend_format = "$DH/rootfiles/run%d_dsssd_recal.root")
Add another chain of files as a friend to an existing one.
Create a friend chain
Parameters
chain Initial chain, the one to which we are adding friends.
friend_name Name of the TTree inside the friend files that you want to friend with chain
friend_alias Desired alias that you want to give to the friend tree
format printf style format for the original file names
friend_format printf style format for the friend file names
Definition at line 209 of file RootAnalysis.cxx.
 {
   Int_t runnum;
   TChain* friendchain = new TChain(friend_name);
   TString format0(format);
   gSystem->ExpandPathName(format0);
   for(Int_t i=0; i< chain->GetNtrees(); ++i) {
     TString filename0 = chain->GetListOfFiles()->At(i)->GetTitle();
     gSystem->ExpandPathName(filename0);
     sscanf(filename0, format0, &runnum);
     TString filename1 = Form(friend_format, runnum);
     gSystem->ExpandPathName(filename1);
     friendchain->AddFile(filename1);
   }
   chain->AddFriend(friendchain, friend_alias, kTRUE);
 }
MakeChains() [1/4]
void dragon::MakeChains (const char * prefix, const Int_t * runnumbers, Int_t nruns, const char * format = "$DH/rootfiles/run%d.root", Bool_t sonik = kFALSE)
Chain together all trees in multiple DRAGON files.
Make chains of dragon event branches from an array of run numbers
Parameters
[in] runnumbers Pointer to a valid array of desired run numbers to chain together.
[in] nruns Length of runnumbers.
format String specifying the file name format, uses printf syntax.
Note
Does not return anything, but creates new heap-allocated TChains that become part of the present ROOT directory; these must be deleted by the user.
Definition at line 102 of file RootAnalysis.cxx.
Referenced by MakeChains().
 {
   if ( !(sonik) ) {
     TChain* chain[] = {new TChain(Form("%s1",  "t"), "Head singles event."),
                        new TChain(Form("%s2",  "t"), "Head scaler event."),
                        new TChain(Form("%s3",  "t"), "Tail singles event."),
                        new TChain(Form("%s4",  "t"), "Tail scaler event."),
                        new TChain(Form("%s5",  "t"), "Coincidence event."),
                        new TChain(Form("%s20", "t"), "Epics event."),
                        new TChain(Form("%s6",  "t"), "Timestamp diagnostics."),
                        new TChain(Form("%s7",  "t"), "Glocal run parameters.")
     };
     Int_t nchains = sizeof(chain) / sizeof(TChain*);
     for(Int_t i=0; i< nruns; ++i) {
       char fname[4096];
       sprintf(fname, format, runnumbers[i]);
       {
         TFile file(fname);
         if(file.IsZombie()) {
           dutils::Warning("MakeChains", __FILE__, __LINE__)
             << "Skipping run " << runnumbers[i] << ", could not find file " << fname;
         }
       }
       for(int j=0; j< nchains; ++j) {
         chain[j]->AddFile(fname);
       }
     }
     chain[0]->SetName(Form("%s1",  prefix));
     chain[1]->SetName(Form("%s2",  prefix));
     chain[2]->SetName(Form("%s3",  prefix));
     chain[3]->SetName(Form("%s4",  prefix));
     chain[4]->SetName(Form("%s5",  prefix));
     chain[5]->SetName(Form("%s20", prefix));
     chain[6]->SetName(Form("%s6",  prefix));
     chain[7]->SetName(Form("%s7",  prefix));
   } else {
     TChain* chain[] = {new TChain(Form("%s0",  "t"), "SONIK event."),
                        // new TChain(Form("%s1",  "t"), "Head singles event."), Head DAQ not used with SONIK
                        // new TChain(Form("%s2",  "t"), "Head scaler event."),
                        new TChain(Form("%s3",  "t"), "Tail singles event."),
                        new TChain(Form("%s4",  "t"), "Tail scaler event."),
                        // new TChain(Form("%s5",  "t"), "Coincidence event."), Coincidence events N/A for SONIK
                        new TChain(Form("%s20", "t"), "Epics event."),
                        new TChain(Form("%s6",  "t"), "Timestamp diagnostics."),
                        new TChain(Form("%s7",  "t"), "Glocal run parameters.")
     };
     Int_t nchains = sizeof(chain) / sizeof(TChain*);
     for(Int_t i=0; i< nruns; ++i) {
       char fname[4096];
       sprintf(fname, format, runnumbers[i]);
       {
         TFile file(fname);
         if(file.IsZombie()) {
           dutils::Warning("MakeChains", __FILE__, __LINE__)
             << "Skipping run " << runnumbers[i] << ", could not find file " << fname;
         }
       }
       for(int j=0; j< nchains; ++j) {
         chain[j]->AddFile(fname);
       }
     }
     chain[0]->SetName(Form("%s0",  prefix));
     chain[1]->SetName(Form("%s3",  prefix));
     chain[2]->SetName(Form("%s4",  prefix));
     chain[3]->SetName(Form("%s20", prefix));
     chain[4]->SetName(Form("%s6",  prefix));
     chain[5]->SetName(Form("%s7",  prefix));
   }
 }
MakeChains() [2/4]
void dragon::MakeChains (const Int_t * runnumbers, Int_t nruns, const char * format = "$DH/rootfiles/run%d.root", Bool_t sonik = kFALSE)
Chain together all trees in multiple DRAGON files.
MakeChains overload.
Definition at line 177 of file RootAnalysis.cxx.
References MakeChains().
 {
   MakeChains("t", runnumbers, nruns, format, sonik);
 }
MakeChains() [3/4]
void dragon::MakeChains (const std::vector< Int_t > & runnumbers, const char * format = "$DH/rootfiles/run%d.root", Bool_t sonik = kFALSE)
Chain together trees using a vector instead of array.
Make chains of dragon event branches from a vector of run numbers
Parameters
runnumbers vector of desired run numbers
format same as the other version
Definition at line 195 of file RootAnalysis.cxx.
References MakeChains().
 {
   MakeChains(&runnumbers[0], runnumbers.size(), format, sonik);
 }
MakeChains() [4/4]
void dragon::MakeChains (const char * prefix, const std::vector< Int_t > & runnumbers, const char * format = "$DH/rootfiles/run%d.root", Bool_t sonik = kFALSE)
Chain together trees using a vector instead of array.
MakeChains overload.
Definition at line 185 of file RootAnalysis.cxx.
References MakeChains().
 {
   MakeChains(prefix, &runnumbers[0], runnumbers.size(), format, sonik);
 }
MeasurementWeightedAverage()
template<class InputIterator > UDouble_t dragon::MeasurementWeightedAverage (InputIterator begin, InputIterator end)
Calculate weighted average of measurements.
Procedure:
Calculate num = \Sum_i { x_i * (1./sigma_i^2) }
Calculateden= { 1./sigma_i^2 }
Final result: nominal value = num/den, error = sqrt(den)
Attention
Assumes symmetric errors.
Definition at line 67 of file RootAnalysis.hxx.
Referenced by dragon::CrossSectionCalculator::Calculate().
   {
   ///
   /// Procedure:
   ///   -# Calculate `num` = `\Sum_i { x_i * (1./sigma_i^2) }
   ///   -# Calculate `den` = `\Sum_i { 1./sigma_i^2 }
   ///   -# Final result: nominal value = `num/den`, error = `sqrt(den)`
   ///
   /// \attention Assumes symmetric errors.
   ///
   Double_t num = 0, den = 0;
   while (begin != end) {
       Double_t val = begin->GetNominal(), weight = 1. / pow(begin->GetRelErrLow(), 2);
       num += val*weight;
       den += weight;
       ++begin;
   }
   return UDouble_t (num/den, sqrt(1./den));
   }
OpenRun()
TFile * dragon::OpenRun (int runnum, const char * format = "$DH/rootfiles/run%d.root")
Open a file just by run number.
Open a dragon rootfile.
Definition at line 230 of file RootAnalysis.cxx.
 {
   TFile* f = TFile::Open(Form(format, runnum));
   if(f && f->IsZombie() == kFALSE)
     gROOT->ProcessLine(Form("TFile* frun%d = (TFile*)%p;", runnum, f));
   else if (f) { f->Close(); f = 0; }
   return f;
 }