DRAGON Analyzer: dragon::utils Namespace Reference
dragon::utils Namespace Reference
Encloses various 'utility' functions.
Classes
struct AdcVariables
Adc variables.
struct AdcVariables2
Adc variables.
struct AdcVariables2< 1 >
Template specialization of AdcVariables2<N> for a single channel.
struct AdcVariables< 1 >
Template specialization of AdcVariables<N> for a single channel.
struct AdcVariablesN
Adc variables.
struct AdcVariablesN< 1, Order >
Template specialization of AdcVariablesN<N> for a single channel.
class ADelayedMessagePrinter
Abstract delayed error handler.
class AStrm
Base stream class.
class AutoPtr
Simple smart pointer class.
class BgoCalibrator
class ChangeErrorIgnore
Utility to temporarily change the error ignore level.
class DelayedMessageFactory
Factory class to create and store DelayedMessagePrinters.
class DelayedMessagePrinter
Class for delayed error printing.
class DsssdCalibrator
class Error
Specialized Strm class to print error messages.
struct greater_and_valid
Functor for sorting in descending order, taking into account validity.
class Info
Specialized Strm class to print informational messages.
struct less_and_valid
Functor for sorting in ascending order, taking into account validity.
struct PositionVariables
Defines position in a cartesian system.
struct PositionVariables< 1 >
Template specialization of Position<N> for one channel.
class Strm
Class to print messages using C++ stream operators.
struct TdcVariables
Tdc variables.
struct TdcVariables2
Tdc variables.
struct TdcVariables2< 1 >
Template specialization of TdcVariables<N> for a single channel.
struct TdcVariables< 1 >
Template specialization of TdcVariables<N> for a single channel.
struct TdcVariablesN
Tdc variables.
struct TdcVariablesN< 1, Order >
Template specialization of TdcVariables<N> for a single channel.
class Warning
Specialized Strm class to print warning messages.
Functions
void set_bank_name (const midas::Bank_t from, midas::Bank_t to)
Sets a MIDAS bank name.
template<class T1 , class T2 >
double calculate_tof (const T1 &t1, const T2 &t2)
Calculates time-of-flight if both parameters are valid.
template<class T >
double calculate_sum (T begin, T end)
Sums all values in an array, <e>ignoring "null" values</e>
template<class T >
void index_fill (T begin, T end, int offset=0)
Fills an array with it's index values.
template<class T >
void index_fill_n (T begin, int n, int offset=0)
Fills an array with it's index values.
template<class T , class Order >
void index_sort (T begin, T end, int *indices, Order order)
Sort function which returns sorted indices instead of modifying the array.
template<class T >
void index_sort (T begin, T end, int *indices)
Sort function which returns sorted indices instead of modifying the array.
template<class T , class M >
void channel_map (T *output, int numch, const int *channels, const M &module)
Maps raw vme data into another array.
template<class T , class M >
void channel_map (T *output, int numch, const int *channels, const int *modules, const M *moduleArr)
Maps raw vme data into another array, from an array of possible modules.
template<class T , class M >
void channel_map (T &output, int channel, const M &module)
Channel maps a single value.
template<class T , class M >
void channel_map (T &output, int channel, int module, const M *moduleArr)
Channel maps a single value.
template<class T >
void channel_map_from_array (T *output, int numch, const int *const indices, const T *const input)
Channel mapping from a plain array, not a module.
template<class T , class TR >
void transform (T *output, int numch, TR transform)
Transforms data within an array.
template<class T , class TR >
void transform (T &output, TR transform)
Transforms a single value.
template<class T , class V >
void pedestal_subtract (T &value, const V &variables)
Perform pedestal subtraction on a single value.
template<class T , class L , class V >
void pedestal_subtract (T *array, L length, const V &variables)
Perform pedestal subtraction on an array.
template<class T , class L , class V >
void linear_calibrate (T *array, L length, const V &variables)
Perform linear calibration on an array.
template<class T , class T2 >
void zero_suppress (T &value, const T2 &threshold)
Perform zero suppression on a single value.
template<class T , class T2 , class L >
void zero_suppress (T *values, L length, const T2 *thresholds)
Perform zero suppression on an array.
template<class T , class T2 , class L >
void zero_suppress1 (T *values, L length, const T2 &threshold)
Perform zero suppression on an array with a single suppression value.
template<class T , class V >
void linear_calibrate (T &value, const V &variables)
Perform linear calibration on a single value.
template<class T , class L , class V >
void quadratic_calibrate (T *array, L length, const V &variables)
Perform quadratic calibration on an array.
template<class T , class V >
void quadratic_calibrate (T &value, const V &variables)
Perform quadratic calibration on a single value.
template<class T , class L , class V >
void polynomial_calibrate (int order, T *array, L length, const V &variables)
Perform nth order polynomial calibration on an array.
template<class T , class V >
void polynomial_calibrate (int order, T &value, const V &variables)
Perform nth order polynomial calibration on a single value.
template<class InputIterator >
std::iterator_traits< InputIterator >::value_type calculate_mean (InputIterator first, InputIterator last)
Calculate the mean of a range of values.
template<class InputIterator , class InputIteratorWeights >
std::iterator_traits< InputIterator >::value_type calculate_weighted_mean (InputIterator first, InputIterator last, InputIteratorWeights firstWeight)
Calculate weighted mean of a range of values.
template<class InputIterator >
std::iterator_traits< InputIterator >::value_type calculate_stddev (InputIterator first, InputIterator last, typename std::iterator_traits< InputIterator >::value_type mean)
Calculate the standard deviation of a range of values.
template<class InputIterator >
std::iterator_traits< InputIterator >::value_type calculate_stddev (InputIterator first, InputIterator last)
Calculate the standard deviation of a range of values.
template<class T >
void reset_array (int len, T *array)
Reset all elements of an array to NO_DATA.
template<class T0 >
bool is_valid (const T0 &t0)
Check if a single value is valid.
template<class T >
bool is_valid_all (T *const tArray, int len)
Check if all elements in an array are valid.
template<class T >
bool is_valid_any (T *const tArray, int len)
Check if any element in an array is valid.
template<class T0 >
void reset_data (T0 &t0)
Reset one datum to NO_DATA.
template<class T0 , class T1 >
bool is_valid (const T0 &t0, const T1 &t1)
Check if 2 data points are valid.
template<class T0 , class T1 >
void reset_data (T0 &t0, T1 &t1)
Reset 2 data points.
template<class T0 , class T1 , class T2 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2)
Check if 3 data points are valid.
template<class T0 , class T1 , class T2 >
void reset_data (T0 &t0, T1 &t1, T2 &t2)
Reset 3 data points.
template<class T0 , class T1 , class T2 , class T3 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3)
Check if 4 data points are valid.
template<class T0 , class T1 , class T2 , class T3 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3)
Reset 4 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4)
Check if 5 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4)
Reset 5 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5)
Check if 6 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5)
Reset 6 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6)
Check if 7 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6)
Reset 7 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7)
Check if 8 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7)
Reset 8 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8)
Check if 9 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8)
Reset 9 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9)
Check if 10 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9)
Reset 10 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10)
Check if 11 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10)
Reset 11 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11)
Check if 12 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11)
Reset 12 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12)
Check if 13 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12)
Reset 13 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13)
Check if 14 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13)
Reset 14 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14)
Check if 15 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14)
Reset 15 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15)
Check if 16 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15)
Reset 16 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16)
Check if 17 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16)
Reset 17 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17)
Check if 18 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17)
Reset 18 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18)
Check if 19 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18)
Reset 19 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19)
Check if 20 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19)
Reset 20 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20)
Check if 21 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20)
Reset 21 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21)
Check if 22 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21)
Reset 22 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22)
Check if 23 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22)
Reset 23 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22, const T23 &t23)
Check if 24 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22, T23 &t23)
Reset 24 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22, const T23 &t23, const T24 &t24)
Check if 25 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22, T23 &t23, T24 &t24)
Reset 25 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22, const T23 &t23, const T24 &t24, const T25 &t25)
Check if 26 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22, T23 &t23, T24 &t24, T25 &t25)
Reset 26 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22, const T23 &t23, const T24 &t24, const T25 &t25, const T26 &t26)
Check if 27 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22, T23 &t23, T24 &t24, T25 &t25, T26 &t26)
Reset 27 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22, const T23 &t23, const T24 &t24, const T25 &t25, const T26 &t26, const T27 &t27)
Check if 28 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22, T23 &t23, T24 &t24, T25 &t25, T26 &t26, T27 &t27)
Reset 28 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22, const T23 &t23, const T24 &t24, const T25 &t25, const T26 &t26, const T27 &t27, const T28 &t28)
Check if 29 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22, T23 &t23, T24 &t24, T25 &t25, T26 &t26, T27 &t27, T28 &t28)
Reset 29 data points.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 , class T29 >
bool is_valid (const T0 &t0, const T1 &t1, const T2 &t2, const T3 &t3, const T4 &t4, const T5 &t5, const T6 &t6, const T7 &t7, const T8 &t8, const T9 &t9, const T10 &t10, const T11 &t11, const T12 &t12, const T13 &t13, const T14 &t14, const T15 &t15, const T16 &t16, const T17 &t17, const T18 &t18, const T19 &t19, const T20 &t20, const T21 &t21, const T22 &t22, const T23 &t23, const T24 &t24, const T25 &t25, const T26 &t26, const T27 &t27, const T28 &t28, const T29 &t29)
Check if 30 data points are valid.
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 , class T29 >
void reset_data (T0 &t0, T1 &t1, T2 &t2, T3 &t3, T4 &t4, T5 &t5, T6 &t6, T7 &t7, T8 &t8, T9 &t9, T10 &t10, T11 &t11, T12 &t12, T13 &t13, T14 &t14, T15 &t15, T16 &t16, T17 &t17, T18 &t18, T19 &t19, T20 &t20, T21 &t21, T22 &t22, T23 &t23, T24 &t24, T25 &t25, T26 &t26, T27 &t27, T28 &t28, T29 &t29)
Reset 30 data points.
Variables
DelayedMessageFactory gDelayedMessageFactory
Global DelayedMessageFactory.
Detailed Description
Encloses various 'utility' functions.
Class Documentation
dragon::utils::AdcVariables
struct dragon::utils::AdcVariables
template<int N>
struct dragon::utils::AdcVariables< N >
Adc variables.
Template Parameters
N Number of ADC channels.
Definition at line 49 of file VariableStructs.hxx.
Class Members
int channel[N] Maps parameters to adc channel number.
int module[N] Maps parameters to adc module number.
double offset[N] Adc offset values (for linear calibration)
int pedestal[N] Adc pedestal values.
double slope[N] Adc slope values (for linear calibration)
dragon::utils::AdcVariables2
struct dragon::utils::AdcVariables2
template<int N>
struct dragon::utils::AdcVariables2< N >
Adc variables.
Template Parameters
N Number of ADC channels.
Definition at line 137 of file VariableStructs.hxx.
Class Members
int channel[N] Maps parameters to adc channel number.
int module[N] Maps parameters to adc module number.
double offset[N] Adc constant values (for quadratic calibration)
int pedestal[N] Adc pedestal values.
double slope[N] Adc 1st order values (for quadratic calibration)
double slope2[N] Adc 2nd order values (for quadratic calibration)
dragon::utils::AdcVariables2< 1 >
struct dragon::utils::AdcVariables2< 1 >
template<>
struct dragon::utils::AdcVariables2< 1 >
Template specialization of AdcVariables2<N> for a single channel.
Arrays are converted into a single value
Definition at line 162 of file VariableStructs.hxx.
Class Members
int channel Maps parameters to adc channel number.
int module Maps parameters to adc module number.
double offset Adc constant values (for quadratic calibration)
int pedestal Adc pedestal values.
double slope Adc 1st order values (for quadratic calibration)
double slope2 Adc 2nd order values (for quadratic calibration)
dragon::utils::AdcVariables< 1 >
struct dragon::utils::AdcVariables< 1 >
template<>
struct dragon::utils::AdcVariables< 1 >
Template specialization of AdcVariables<N> for a single channel.
Arrays are converted into a single value
Definition at line 71 of file VariableStructs.hxx.
Class Members
int channel Maps parameters to adc channel number.
int module Maps parameters to adc module number.
double offset Adc offset values (for linear calibration)
int pedestal Adc pedestal values.
double slope Adc slope values (for linear calibration)
dragon::utils::AdcVariablesN
struct dragon::utils::AdcVariablesN
template<int N, int Order>
struct dragon::utils::AdcVariablesN< N, Order >
Adc variables.
Template Parameters
N Number of ADC channels.
Order Order of the ADC calibration
Definition at line 238 of file VariableStructs.hxx.
Class Members
int channel[N] Maps parameters to adc channel number.
double coeff[Order][N] Adc calibration coefficient values.
int module[N] Maps parameters to adc module number.
int pedestal[N] Adc pedestal values.
dragon::utils::AdcVariablesN< 1, Order >
struct dragon::utils::AdcVariablesN< 1, Order >
template<int Order>
struct dragon::utils::AdcVariablesN< 1, Order >
Template specialization of AdcVariablesN<N> for a single channel.
Arrays are converted into a single value
Definition at line 257 of file VariableStructs.hxx.
Class Members
int channel Maps parameters to adc channel number.
double coeff[Order] Adc calibration coefficient values.
int module Maps parameters to adc module number.
int pedestal Adc pedestal values.
dragon::utils::BgoCalibrator
class dragon::utils::BgoCalibrator
Todo:
write dutils::BgoCalibrator class to use γ singles data to calibrate the BGO array using the room background lines from 40K (Eγ = 1.461 MeV) and 208Tl (Eγ = 2.614 MeV).
Definition at line 65 of file Calibration.hxx.
dragon::utils::PositionVariables
struct dragon::utils::PositionVariables
template<int N>
struct dragon::utils::PositionVariables< N >
Defines position in a cartesian system.
Template Parameters
N Number of channels
Definition at line 13 of file VariableStructs.hxx.
Class Members
double x[N] X-axis position.
double y[N] Y-axis position.
double z[N] Z-axis position.
dragon::utils::PositionVariables< 1 >
struct dragon::utils::PositionVariables< 1 >
template<>
struct dragon::utils::PositionVariables< 1 >
Template specialization of Position<N> for one channel.
Definition at line 28 of file VariableStructs.hxx.
Class Members
double x X-axis position.
double y Y-axis position.
double z Z-axis position.
dragon::utils::TdcVariables
struct dragon::utils::TdcVariables
template<int N>
struct dragon::utils::TdcVariables< N >
Tdc variables.
Template Parameters
N Number of TDC channels.
Definition at line 93 of file VariableStructs.hxx.
Class Members
int channel[N] Maps parameters to tdc channel number.
int module[N] Maps parameters to tdc module number.
double offset[N] Tdc offset values (for linear calibration)
double slope[N] Tdc slope values (for linear calibration)
dragon::utils::TdcVariables2
struct dragon::utils::TdcVariables2
template<int N>
struct dragon::utils::TdcVariables2< N >
Tdc variables.
Template Parameters
N Number of TDC channels.
Definition at line 187 of file VariableStructs.hxx.
Class Members
int channel[N] Maps parameters to tdc channel number.
int module[N] Maps parameters to tdc module number.
double offset[N] Tdc constant values (for quadratic calibration)
double slope[N] Tdc 1st order values (for quadratic calibration)
double slope2[N] Tdc 2nd order values (for quadratic calibration)
dragon::utils::TdcVariables2< 1 >
struct dragon::utils::TdcVariables2< 1 >
template<>
struct dragon::utils::TdcVariables2< 1 >
Template specialization of TdcVariables<N> for a single channel.
Arrays are converted into a single value
Definition at line 209 of file VariableStructs.hxx.
Class Members
int channel Maps parameters to tdc channel number.
int module Maps parameters to tdc module number.
double offset Tdc constant values (for quadratic calibration)
double slope Tdc 1st order values (for quadratic calibration)
double slope2 Tdc 2nd order values (for quadratic calibration)
dragon::utils::TdcVariables< 1 >
struct dragon::utils::TdcVariables< 1 >
template<>
struct dragon::utils::TdcVariables< 1 >
Template specialization of TdcVariables<N> for a single channel.
Arrays are converted into a single value
Definition at line 112 of file VariableStructs.hxx.
Class Members
int channel Maps parameters to tdc channel number.
int module Maps parameters to tdc module number.
double offset Tdc offset values (for linear calibration)
double slope Tdc slope values (for linear calibration)
dragon::utils::TdcVariablesN
struct dragon::utils::TdcVariablesN
template<int N, int Order>
struct dragon::utils::TdcVariablesN< N, Order >
Tdc variables.
Template Parameters
N Number of ADC channels.
Order Order of the ADC calibration
Definition at line 278 of file VariableStructs.hxx.
Class Members
int channel[N] Maps parameters to tdc channel number.
double coeff[Order][N] Tdc calibration coefficient values.
int module[N] Maps parameters to tdc module number.
dragon::utils::TdcVariablesN< 1, Order >
struct dragon::utils::TdcVariablesN< 1, Order >
template<int Order>
struct dragon::utils::TdcVariablesN< 1, Order >
Template specialization of TdcVariables<N> for a single channel.
Arrays are converted into a single value
Definition at line 293 of file VariableStructs.hxx.
Class Members
int channel Maps parameters to tdc channel number.
double coeff[Order] Tdc calibration coefficient values.
int module Maps parameters to tdc module number.
Function Documentation
calculate_mean()
template<class InputIterator > std::iterator_traits<InputIterator>::value_type dragon::utils::calculate_mean (InputIterator first, InputIterator last)
Calculate the mean of a range of values.
Example:
double array[] = { 1, 2, 3, 4, 5 };
std::cout << "mean is " << calculate_mean(array, array + 5) << "\n";
Definition at line 679 of file Functions.hxx.
Referenced by dragon::RossumData::AverageCurrent(), calculate_stddev(), and dragon::BeamNorm::ReadSbCounts().
 {
   const typename std::iterator_traits<InputIterator>::value_type init = 0;
   return std::accumulate(first, last, init) / std::distance(first, last);
 }
calculate_stddev() [1/2]
template<class InputIterator > std::iterator_traits<InputIterator>::value_type dragon::utils::calculate_stddev (InputIterator first, InputIterator last, typename std::iterator_traits< InputIterator >::value_type mean)
Calculate the standard deviation of a range of values.
Uses previously calculated mean value Example:
double array[] = { 1, 2, 3, 4, 5 };
double mean = dragon::utils::mean(array, array + 5);
std::cout << "mean is " << mean << ", stddev is "
          << dragon::utils::calculate_stddev(array, array + 5, mean) << "\n";
Definition at line 718 of file Functions.hxx.
Referenced by dragon::RossumData::AverageCurrent(), calculate_stddev(), and dragon::BeamNorm::ReadSbCounts().
 {
   const typename std::iterator_traits<InputIterator>::value_type init = 0;
   const StddevAccum<typename std::iterator_traits<InputIterator>::value_type> accumulator(mean);
   return sqrt(std::accumulate(first, last, init, accumulator) / std::distance(first, last));
 }
calculate_stddev() [2/2]
template<class InputIterator > std::iterator_traits<InputIterator>::value_type dragon::utils::calculate_stddev (InputIterator first, InputIterator last)
Calculate the standard deviation of a range of values.
Calculates mean value in an initial pass of the range Example:
double array[] = { 1, 2, 3, 4, 5 };
std::cout << "stddev is " << dragon::utils::calculate_stddev(array, array + 5) << "\n";
Definition at line 736 of file Functions.hxx.
References calculate_mean(), and calculate_stddev().
 {
   const typename std::iterator_traits<InputIterator>::value_type mean =
     dragon::utils::calculate_mean(first, last);
   return dragon::utils::calculate_stddev(first, last, mean);
 }
calculate_sum()
template<class T > double dragon::utils::calculate_sum (T begin, T end) inline
Sums all values in an array, <e>ignoring "null" values</e>
Example:
double anodes = { 300., 200., 100., 1., 0., -1. }; // dragon::DR_NO_DATA == -1
double sum = utils::sum(anodes, anodes + 6);
// sum = 601.
Parameters
begin First element to sum
end One past the last element to sum
Template Parameters
T Type contained in the array
Definition at line 58 of file Functions.hxx.
References is_valid().
Referenced by dragon::Bgo::calculate(), dragon::IonChamber::calculate(), and dragon::Mcp::calculate().
 {
   /*!
    * Example:
    * \code
    * double anodes = { 300., 200., 100., 1., 0., -1. }; // dragon::DR_NO_DATA == -1
    * double sum = utils::sum(anodes, anodes + 6);
    * // sum = 601.
    * \endcode
    * \param begin First element to sum
    * \param end One past the last element to sum
    * \tparam T Type contained in the array
    */
   double sum = 0.;
   for(; begin != end; ++begin) {
     if(is_valid(*begin))
       sum += *begin;
   }
   return sum;
 }
calculate_tof()
template<class T1 , class T2 > double dragon::utils::calculate_tof (const T1 & t1, const T2 & t2) inline
Calculates time-of-flight if both parameters are valid.
Parameters
t1 Later time
t2 Earlier time
Returns
t1 - t2 if both parameters are valid; otherwise: dragon::DR_NO_DATA
Definition at line 43 of file Functions.hxx.
References is_valid(), and dragon::NoData< T >::value().
Referenced by dragon::HiTof::calculate(), and dragon::Coinc::calculate().
 {
   /*!
    * \param t1 Later time
    * \param t2 Earlier time
    * \returns <c>t1 - t2</c> if both parameters are valid; otherwise: \c dragon::DR_NO_DATA
    */
   if (utils::is_valid(t1) && utils::is_valid(t2))
     return t1 - t2;
   else
     return NoData<int32_t>::value();
 }
calculate_weighted_mean()
template<class InputIterator , class InputIteratorWeights > std::iterator_traits<InputIterator>::value_type dragon::utils::calculate_weighted_mean (InputIterator first, InputIterator last, InputIteratorWeights firstWeight)
Calculate weighted mean of a range of values.
Example:
double array[] = { 1, 2, 3, 4, 5 };
double weights[] = { 5, 4, 3, 2, 1 };
std::cout << "weighted mean is " << calculate_weighted_mean(array, array + 5, weights) << "\n";
Definition at line 696 of file Functions.hxx.
 {
   const typename std::iterator_traits<InputIterator>::value_type init = 0;
   WeightedAccum<typename std::iterator_traits<InputIterator>::value_type, InputIteratorWeights>
     accumulator(firstWeight);
   return std::accumulate(first, last, init, accumulator);
 }
channel_map() [1/4]
template<class T , class M > void dragon::utils::channel_map (T * output, int numch, const int * channels, const M & module) inline
Maps raw vme data into another array.
Template Parameters
T Basic type of the output array
M Type of the vme module
Parameters
[out] output Array containing the mapped values
[in] numch Number of channels in the output array
[in] channels Array containing the channel mapping
[in] module Vme module class containing the raw data
Example:
vme::V792 adc;
adc.unpack(someEvent, "ADC0"); // adc.data = { 21, 24, 26, ... }
int channels = { 2, 0, 1, ... };
double output[32];
channel_map(output, 32, channels, adc); // output = { 26, 21, 24, ... }
Definition at line 256 of file Functions.hxx.
Referenced by dragon::Head::calculate(), dragon::Tail::calculate(), Sonik::read_data(), dragon::Bgo::read_data(), dragon::Dsssd::read_data(), dragon::IonChamber::read_data(), dragon::Mcp::read_data(), dragon::SurfaceBarrier::read_data(), dragon::NaI::read_data(), and dragon::Ge::read_data().
 {
   for (int i=0; i< numch; ++i) {
     output[i] = module.get_data( channels[i] );
   }
 }
channel_map() [2/4]
template<class T , class M > void dragon::utils::channel_map (T * output, int numch, const int * channels, const int * modules, const M * moduleArr) inline
Maps raw vme data into another array, from an array of possible modules.
Template Parameters
T Basic type of the output array
M Type of the vme module
Parameters
[out] output Array containing the mapped values
[in] numch Number of channels in the
[in] channels Array containing the channel mapping
[in] channels Array containing the module mapping
[in] moduleArr Array of vme modules containing the raw data
Example:
vme::V792[2] adc;
adc[0].unpack(someEvent, "ADC0"); // adc[0].data = { 21, 24, 26, ... }
adc[1].unpack(someEvent, "ADC1"); // adc[1].data = { 27, 22, 19, ... }
int channels = { 2, 0, 1, ... };
int modules = { 0, 1, 0, ... };
double output[32];
channel_map(output, 32, channels, modules, adc); // output = { 26, 27, 24, ... }
Definition at line 286 of file Functions.hxx.
 {
   for (int i=0; i< numch; ++i) {
     output[i] = moduleArr[ modules[i] ].get_data( channels[i] );
   }
 }
channel_map() [3/4]
template<class T , class M > void dragon::utils::channel_map (T & output, int channel, const M & module) inline
Channel maps a single value.
See array version of channel_map()
Definition at line 296 of file Functions.hxx.
 {
   /*!
    * See array version of channel_map()
    */
   output = module.get_data(channel);
 }
channel_map() [4/4]
template<class T , class M > void dragon::utils::channel_map (T & output, int channel, int module, const M * moduleArr) inline
Channel maps a single value.
See array version of channel_map()
Definition at line 306 of file Functions.hxx.
 {
   /*!
    * See array version of channel_map()
    */
   output = moduleArr[module].get_data(channel);
 }
channel_map_from_array()
template<class T > void dragon::utils::channel_map_from_array (T * output, int numch, const int *const indices, const T *const input) inline
Channel mapping from a plain array, not a module.
Parameters
[out] output Output array
[in] numch Length of the input array
[in] indices Array containing mapping values
[in] input Array of input data
Example:
double input[5] = { 1., 2., 3., 4., 5. };
double output[5];
int indices[5] = { 3, 2, 1, 4, 0 };
utils::channel_map_from_array(output, 5, indices, input);
// output = { 4., 3., 2., 5., 1. }
Definition at line 317 of file Functions.hxx.
Referenced by dragon::Bgo::calculate().
 {
   /*!
    * \param [out] output Output array
    * \param [in] numch Length of the input array
    * \param [in] indices Array containing mapping values
    * \param [in] input Array of input data
    *
    * Example:
    * \code
    * double input[5] = { 1., 2., 3., 4., 5. };
    * double output[5];
    * int indices[5] = { 3, 2, 1, 4, 0 };
    * utils::channel_map_from_array(output, 5, indices, input);
    * // output = { 4., 3., 2., 5., 1. }
    * \endcode
    */
   for (int i=0; i< numch; ++i)
     output[i] = input[ indices[i] ];
 }
index_fill()
template<class T > void dragon::utils::index_fill (T begin, T end, int offset = 0) inline
Fills an array with it's index values.
Example:
double arr[4];
vme::index_fill(arr, arr + 4);
// arr = { 0., 1., 2., 3. }
vme::index_fill(arr, arr + 4, 5);
// arr = { 5., 6., 7., 8. }
Template Parameters
Type contained in the array
Parameters
begin Beginning of the array (vector, etc.)
end End of the array (vector, etc.)
offset Optional offset for the filled values
Definition at line 81 of file Functions.hxx.
Referenced by index_sort(), Sonik::Variables::reset(), dragon::Bgo::Variables::reset(), dragon::Dsssd::Variables::reset(), dragon::IonChamber::Variables::reset(), dragon::Mcp::Variables::reset(), dragon::SurfaceBarrier::Variables::reset(), and dragon::NaI::Variables::reset().
 {
   /*!
    * Example:
    * \code
    * double arr[4];
    * vme::index_fill(arr, arr + 4);
    * // arr = { 0., 1., 2., 3. }
    * vme::index_fill(arr, arr + 4, 5);
    * // arr = { 5., 6., 7., 8. }
    * \endcode
    * \tparam Type contained in the array
    * \param begin Beginning of the array (vector, etc.)
    * \param end End of the array (vector, etc.)
    * \param offset Optional offset for the filled values
    */
   for(int i=0; begin != end; ++i, ++begin)
     *begin = i + offset;
 }
index_fill_n()
template<class T > void dragon::utils::index_fill_n (T begin, int n, int offset = 0) inline
Fills an array with it's index values.
Example:
double arr[4];
vme::index_fill_n(arr, 4);
// arr = { 0., 1., 2., 3. }
vme::index_fill_n(arr, 4, 5);
// arr = { 5., 6., 7., 8. }
Parameters
begin Beginning of the array (vector, etc.)
n Number of indices past begin to fill
offset Optional offset for the filled values
Definition at line 103 of file Functions.hxx.
 {
   /*!
    * Example:
    * \code
    * double arr[4];
    * vme::index_fill_n(arr, 4);
    * // arr = { 0., 1., 2., 3. }
    * vme::index_fill_n(arr, 4, 5);
    * // arr = { 5., 6., 7., 8. }
    * \endcode
    * \param begin Beginning of the array (vector, etc.)
    * \param n Number of indices past begin to fill
    * \param offset Optional offset for the filled values
    */
   for(int i=0; i< n; ++i, ++begin)
     *begin = i + offset;
 }
index_sort() [1/2]
template<class T , class Order > void dragon::utils::index_sort (T begin, T end, int * indices, Order order) inline
Sort function which returns sorted indices instead of modifying the array.
Template Parameters
T type in the array
Order Functor defining the strict weak ordering of the array to sort
Parameters
[in] begin Beginning of the array whose sorted values you desire
[in] end End of the array whose sorted values you desire
[out] indices Pointer to the beginning of an array in which you will store the sorted indices. This array must contain space for every index.
[in] order instance of Order class for sorting.
Example:
double data[5] = { 1., 5., -12., 21., -31. };
int sortedData[5];
utils::index_sort(data, data+5, sortedData, std::greater<double>());
for(int i=0; i< 5; ++i) cout << data[ sortedData[i] ] << " ";
cout << "\n";
// Output:
// 21 5 1 -12 -31
Definition at line 216 of file Functions.hxx.
References index_fill().
Referenced by dragon::Bgo::calculate().
 {
   std::ptrdiff_t size = end - begin;
   index_fill(indices, indices + size);
   std::sort(indices, indices + size,  Isort<T, Order>(begin, order));
 }
index_sort() [2/2]
template<class T > void dragon::utils::index_sort (T begin, T end, int * indices) inline
Sort function which returns sorted indices instead of modifying the array.
Same as index_sort(), except defaulting to std::less<> for the comparison, i.e. the returned indices sort in ascending order.
Definition at line 229 of file Functions.hxx.
References index_fill().
 {
   std::ptrdiff_t size = end - begin;
   index_fill(indices, indices + size);
   std::sort(indices, indices + size,  IsortLess<T> (begin));
 }
is_valid() [1/30]
template<class T0 > bool dragon::utils::is_valid (const T0 & t0) inline
Check if a single value is valid.
Implementation:
Definition at line 65 of file Valid.hxx.
Referenced by dragon::Bgo::calculate(), calculate_sum(), calculate_tof(), linear_calibrate(), pedestal_subtract(), polynomial_calibrate(), quadratic_calibrate(), zero_suppress(), and zero_suppress1().
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() );
 }
is_valid() [2/30]
template<class T0 , class T1 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1) inline
Check if 2 data points are valid.
Implementation:
Definition at line 99 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() );
 }
is_valid() [3/30]
template<class T0 , class T1 , class T2 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2) inline
Check if 3 data points are valid.
Implementation:
Definition at line 116 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() );
 }
is_valid() [4/30]
template<class T0 , class T1 , class T2 , class T3 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3) inline
Check if 4 data points are valid.
Implementation:
Definition at line 134 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() );
 }
is_valid() [5/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4) inline
Check if 5 data points are valid.
Implementation:
Definition at line 153 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() );
 }
is_valid() [6/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5) inline
Check if 6 data points are valid.
Implementation:
Definition at line 173 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() );
 }
is_valid() [7/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6) inline
Check if 7 data points are valid.
Implementation:
Definition at line 194 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() );
 }
is_valid() [8/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7) inline
Check if 8 data points are valid.
Implementation:
Definition at line 216 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() );
 }
is_valid() [9/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8) inline
Check if 9 data points are valid.
Implementation:
Definition at line 239 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() );
 }
is_valid() [10/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9) inline
Check if 10 data points are valid.
Implementation:
Definition at line 263 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() );
 }
is_valid() [11/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10) inline
Check if 11 data points are valid.
Implementation:
Definition at line 288 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() );
 }
is_valid() [12/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11) inline
Check if 12 data points are valid.
Implementation:
Definition at line 314 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() );
 }
is_valid() [13/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12) inline
Check if 13 data points are valid.
Implementation:
Definition at line 341 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() );
 }
is_valid() [14/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13) inline
Check if 14 data points are valid.
Implementation:
Definition at line 369 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() );
 }
is_valid() [15/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14) inline
Check if 15 data points are valid.
Implementation:
Definition at line 398 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() );
 }
is_valid() [16/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15) inline
Check if 16 data points are valid.
Implementation:
Definition at line 428 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() );
 }
is_valid() [17/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16) inline
Check if 17 data points are valid.
Implementation:
Definition at line 459 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() );
 }
is_valid() [18/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17) inline
Check if 18 data points are valid.
Implementation:
Definition at line 491 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() );
 }
is_valid() [19/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18) inline
Check if 19 data points are valid.
Implementation:
Definition at line 524 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() );
 }
is_valid() [20/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19) inline
Check if 20 data points are valid.
Implementation:
Definition at line 558 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() );
 }
is_valid() [21/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20) inline
Check if 21 data points are valid.
Implementation:
Definition at line 593 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() );
 }
is_valid() [22/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21) inline
Check if 22 data points are valid.
Implementation:
Definition at line 629 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() );
 }
is_valid() [23/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22) inline
Check if 23 data points are valid.
Implementation:
Definition at line 666 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() );
 }
is_valid() [24/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22, const T23 & t23) inline
Check if 24 data points are valid.
Implementation:
Definition at line 704 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() && t23 != dragon::NoData<T23>::value() );
 }
is_valid() [25/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22, const T23 & t23, const T24 & t24) inline
Check if 25 data points are valid.
Implementation:
Definition at line 743 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() && t23 != dragon::NoData<T23>::value() && t24 != dragon::NoData<T24>::value() );
 }
is_valid() [26/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22, const T23 & t23, const T24 & t24, const T25 & t25) inline
Check if 26 data points are valid.
Implementation:
Definition at line 783 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() && t23 != dragon::NoData<T23>::value() && t24 != dragon::NoData<T24>::value() && t25 != dragon::NoData<T25>::value() );
 }
is_valid() [27/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22, const T23 & t23, const T24 & t24, const T25 & t25, const T26 & t26) inline
Check if 27 data points are valid.
Implementation:
Definition at line 824 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() && t23 != dragon::NoData<T23>::value() && t24 != dragon::NoData<T24>::value() && t25 != dragon::NoData<T25>::value() && t26 != dragon::NoData<T26>::value() );
 }
is_valid() [28/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22, const T23 & t23, const T24 & t24, const T25 & t25, const T26 & t26, const T27 & t27) inline
Check if 28 data points are valid.
Implementation:
Definition at line 866 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() && t23 != dragon::NoData<T23>::value() && t24 != dragon::NoData<T24>::value() && t25 != dragon::NoData<T25>::value() && t26 != dragon::NoData<T26>::value() && t27 != dragon::NoData<T27>::value() );
 }
is_valid() [29/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22, const T23 & t23, const T24 & t24, const T25 & t25, const T26 & t26, const T27 & t27, const T28 & t28) inline
Check if 29 data points are valid.
Implementation:
Definition at line 909 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() && t23 != dragon::NoData<T23>::value() && t24 != dragon::NoData<T24>::value() && t25 != dragon::NoData<T25>::value() && t26 != dragon::NoData<T26>::value() && t27 != dragon::NoData<T27>::value() && t28 != dragon::NoData<T28>::value() );
 }
is_valid() [30/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 , class T29 > bool dragon::utils::is_valid (const T0 & t0, const T1 & t1, const T2 & t2, const T3 & t3, const T4 & t4, const T5 & t5, const T6 & t6, const T7 & t7, const T8 & t8, const T9 & t9, const T10 & t10, const T11 & t11, const T12 & t12, const T13 & t13, const T14 & t14, const T15 & t15, const T16 & t16, const T17 & t17, const T18 & t18, const T19 & t19, const T20 & t20, const T21 & t21, const T22 & t22, const T23 & t23, const T24 & t24, const T25 & t25, const T26 & t26, const T27 & t27, const T28 & t28, const T29 & t29) inline
Check if 30 data points are valid.
Implementation:
Definition at line 953 of file Valid.hxx.
 {
   /// Implementation:
   return ( t0 != dragon::NoData<T0>::value() && t1 != dragon::NoData<T1>::value() && t2 != dragon::NoData<T2>::value() && t3 != dragon::NoData<T3>::value() && t4 != dragon::NoData<T4>::value() && t5 != dragon::NoData<T5>::value() && t6 != dragon::NoData<T6>::value() && t7 != dragon::NoData<T7>::value() && t8 != dragon::NoData<T8>::value() && t9 != dragon::NoData<T9>::value() && t10 != dragon::NoData<T10>::value() && t11 != dragon::NoData<T11>::value() && t12 != dragon::NoData<T12>::value() && t13 != dragon::NoData<T13>::value() && t14 != dragon::NoData<T14>::value() && t15 != dragon::NoData<T15>::value() && t16 != dragon::NoData<T16>::value() && t17 != dragon::NoData<T17>::value() && t18 != dragon::NoData<T18>::value() && t19 != dragon::NoData<T19>::value() && t20 != dragon::NoData<T20>::value() && t21 != dragon::NoData<T21>::value() && t22 != dragon::NoData<T22>::value() && t23 != dragon::NoData<T23>::value() && t24 != dragon::NoData<T24>::value() && t25 != dragon::NoData<T25>::value() && t26 != dragon::NoData<T26>::value() && t27 != dragon::NoData<T27>::value() && t28 != dragon::NoData<T28>::value() && t29 != dragon::NoData<T29>::value() );
 }
is_valid_all()
template<class T > bool dragon::utils::is_valid_all (T *const tArray, int len) inline
Check if all elements in an array are valid.
Implementation:
Definition at line 73 of file Valid.hxx.
Referenced by dragon::Mcp::calculate().
 {
   /// Implementation:
   T* const end = tArray + len;
   return std::find(tArray, end, dragon::NoData<T>::value()) == end;
 }
is_valid_any()
template<class T > bool dragon::utils::is_valid_any (T *const tArray, int len) inline
Check if any element in an array is valid.
Implementation:
Definition at line 82 of file Valid.hxx.
Referenced by Sonik::calculate(), dragon::Dsssd::calculate(), and dragon::IonChamber::calculate().
 {
   /// Implementation:
   T* const end = tArray + len;
   return std::find_if(tArray, end, is_valid<T>) != end;
 }
linear_calibrate() [1/2]
template<class T , class L , class V > void dragon::utils::linear_calibrate (T * array, L length, const V & variables) inline
Perform linear calibration on an array.
New = slope * Old + offset
Template Parameters
T type of the values in the array
L type of the array length identifier
V variables class, must have public slope[] and offset[] fields
Usage example:
dragon::AdcVariables<3> vars;
vars.offset = { 0., 1., 2. }; // (only allowed in C++11, but you get the point)
vars.slope  = { 2., 1., 0. }; // (only allowed in C++11, but you get the point)
double values = { 1., 2., 3. };
utils::linear_calibrate(values, 3, vars);
// values = { 2., 3., 2. }
Note
Any values initially set to dragon::DR_NO_DATA are left untouched
Definition at line 461 of file Functions.hxx.
References is_valid().
Referenced by Sonik::calculate(), dragon::Bgo::calculate(), dragon::Dsssd::calculate(), dragon::IonChamber::calculate(), dragon::Mcp::calculate(), dragon::SurfaceBarrier::calculate(), dragon::NaI::calculate(), dragon::Ge::calculate(), dragon::TdcChannel< MAX_RF_HITS >::calculate(), dragon::Head::calculate(), and dragon::Tail::calculate().
 {
   for (L i=0; i< length; ++i) {
     if(is_valid(array[i]))
       array[i] = variables.offset[i] + array[i] * variables.slope[i];
   }
 }
linear_calibrate() [2/2]
template<class T , class V > void dragon::utils::linear_calibrate (T & value, const V & variables) inline
Perform linear calibration on a single value.
New = slope * Old + offset
Template Parameters
T type of the values in the array
V variables class, must have public slope[] and offset[] fields
See array version for more information.
Note
Any values initially set to dragon::DR_NO_DATA are left untouched
Definition at line 545 of file Functions.hxx.
References is_valid().
 {
   if(is_valid(value))
     value = variables.offset + value * variables.slope;
 }
pedestal_subtract() [1/2]
template<class T , class V > void dragon::utils::pedestal_subtract (T & value, const V & variables) inline
Perform pedestal subtraction on a single value.
Shifts adc channels down by the pedestal value, then "suppresses" all values below an optional offset.
Template Parameters
T type of the values in the array
V variables class, must have public pedestal field
Usage example:
dragon::AdcVariables<1> vars;
vars.pedestal = 32.;
double value1 = 100., value2 = 31.;
utils::pedestal_subtract(value1, vars);
utils::pedestal_subtract(value2, vars);
// value1 = 100., value2 = -1.
// n.b. dragon::DR_NO_DATA == -1.
Definition at line 407 of file Functions.hxx.
References is_valid().
Referenced by dragon::Bgo::calculate().
 {
   if(is_valid(value) == false) return;
   value -= variables.pedestal; // shift
 }
pedestal_subtract() [2/2]
template<class T , class L , class V > void dragon::utils::pedestal_subtract (T * array, L length, const V & variables) inline
Perform pedestal subtraction on an array.
Shifts adc channels down by the pedestal value.
Template Parameters
T type of the values in the array
L type of the array length identifier
V variables class, must have public pedestal[] field
Usage example:
dragon::AdcVariables<4> vars;
vars.pedestal = { 32, 17, 21, 46 }; // (only allowed in C++11, but you get the point)
double values = { 13., 16., 21., 444. };
utils::pedestal_subtract(values, 4, vars);
// values = { -1., -1., 21., 444. }
// n.b. dragon::DR_NO_DATA == -1.
Definition at line 432 of file Functions.hxx.
References is_valid().
 {
   for (L i=0; i< length; ++i) {
     if(is_valid(array[i]) == false) continue;
     array[i] -= variables.pedestal[i]; // shift
   }
 }
polynomial_calibrate() [1/2]
template<class T , class L , class V > void dragon::utils::polynomial_calibrate (int order, T * array, L length, const V & variables) inline
Perform nth order polynomial calibration on an array.
New = offset + slope * Old + slope2*Old*Old + slope3*Old*Old*Old + ...
Template Parameters
T type of the values in the array
L type of the array length identifier
V variables class, must have public coeff[][] field
Behaves identically to linear_calibrate(), except performing a quadratic calibration instead
Note
Any values initially set to dragon::DR_NO_DATA are left untouched
Definition at line 602 of file Functions.hxx.
References is_valid().
 {
   for(L i=0; i< length; ++i) {
     if(is_valid(array[i])) {
       T value0 = array[i];
       array[i] = 0;
       for(int j=0; j< order; ++j) {
         array[i] += variables.coeff[j][i] * pow(value0, j);
       }
     }
   }
 }
polynomial_calibrate() [2/2]
template<class T , class V > void dragon::utils::polynomial_calibrate (int order, T & value, const V & variables) inline
Perform nth order polynomial calibration on a single value.
New = offset + slope * Old + slope2*Old*Old + slope3*Old*Old*Old + ...
Template Parameters
T type of the values in the array
V variables class, must have public coeff[] field
See array version for more information.
Note
Any values initially set to dragon::DR_NO_DATA are left untouched
Definition at line 626 of file Functions.hxx.
References is_valid().
 {
   if(is_valid(value)) {
     T value0 = value;
     value = 0;
     for(int j=0; j< order; ++j) {
       value += variables.coeff[j] * pow(value0, j);
     }
   }
 }
quadratic_calibrate() [1/2]
template<class T , class L , class V > void dragon::utils::quadratic_calibrate (T * array, L length, const V & variables) inline
Perform quadratic calibration on an array.
New = slope2 * Old*Old + slope * Old + offset
Template Parameters
T type of the values in the array
L type of the array length identifier
V variables class, must have public slope2[], slope[], and offset[] fields
Behaves identically to linear_calibrate(), except performing a quadratic calibration instead
Note
Any values initially set to dragon::DR_NO_DATA are left untouched
Definition at line 564 of file Functions.hxx.
References is_valid().
 {
   for (L i=0; i< length; ++i) {
     if(is_valid(array[i]))
       array[i] = variables.offset[i] + array[i] * variables.slope[i] + pow(array[i], 2) * variables.slope2[i];
   }
 }
quadratic_calibrate() [2/2]
template<class T , class V > void dragon::utils::quadratic_calibrate (T & value, const V & variables) inline
Perform quadratic calibration on a single value.
New = slope2 * Old*Old + slope * Old + offset
Template Parameters
T type of the values in the array
V variables class, must have public slope2, slope, and offset fields
See array version for more information.
Note
Any values initially set to dragon::DR_NO_DATA are left untouched
Definition at line 583 of file Functions.hxx.
References is_valid().
 {
   if(is_valid(value))
     value = variables.offset + value * variables.slope + pow(value, 2) * variables.slope2;
 }
reset_array()
template<class T > void dragon::utils::reset_array (int len, T * array) inline
Reset all elements of an array to NO_DATA.
Implementation:
Definition at line 57 of file Valid.hxx.
Referenced by Sonik::reset(), dragon::Bgo::reset(), dragon::Dsssd::reset(), vme::V792::reset(), dragon::IonChamber::reset(), dragon::Mcp::reset(), dragon::SurfaceBarrier::reset(), dragon::NaI::reset(), and dragon::TdcChannel< MAX_RF_HITS >::reset().
 {
   /// Implementation:
   std::fill_n(array, len, dragon::NoData<T>::value());
 }
reset_data() [1/30]
template<class T0 > void dragon::utils::reset_data (T0 & t0) inline
Reset one datum to NO_DATA.
Implementation:
Definition at line 91 of file Valid.hxx.
References dragon::NoData< T >::value().
Referenced by vme::Io32::reset(), Sonik::reset(), dragon::Bgo::reset(), vme::V1190::reset(), dragon::Dsssd::reset(), dragon::IonChamber::reset(), dragon::Mcp::reset(), dragon::Ge::reset(), dragon::HiTof::reset(), dragon::Head::reset(), dragon::Tail::reset(), dragon::Coinc::reset(), and dragon::Epics::reset().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
 }
reset_data() [2/30]
template<class T0 , class T1 > void dragon::utils::reset_data (T0 & t0, T1 & t1) inline
Reset 2 data points.
Implementation:
Definition at line 107 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
 }
reset_data() [3/30]
template<class T0 , class T1 , class T2 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2) inline
Reset 3 data points.
Implementation:
Definition at line 124 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
 }
reset_data() [4/30]
template<class T0 , class T1 , class T2 , class T3 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3) inline
Reset 4 data points.
Implementation:
Definition at line 142 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
 }
reset_data() [5/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4) inline
Reset 5 data points.
Implementation:
Definition at line 161 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
 }
reset_data() [6/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5) inline
Reset 6 data points.
Implementation:
Definition at line 181 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
 }
reset_data() [7/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6) inline
Reset 7 data points.
Implementation:
Definition at line 202 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
 }
reset_data() [8/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7) inline
Reset 8 data points.
Implementation:
Definition at line 224 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
 }
reset_data() [9/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8) inline
Reset 9 data points.
Implementation:
Definition at line 247 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
 }
reset_data() [10/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9) inline
Reset 10 data points.
Implementation:
Definition at line 271 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
 }
reset_data() [11/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10) inline
Reset 11 data points.
Implementation:
Definition at line 296 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
 }
reset_data() [12/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11) inline
Reset 12 data points.
Implementation:
Definition at line 322 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
 }
reset_data() [13/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12) inline
Reset 13 data points.
Implementation:
Definition at line 349 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
 }
reset_data() [14/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13) inline
Reset 14 data points.
Implementation:
Definition at line 377 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
 }
reset_data() [15/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14) inline
Reset 15 data points.
Implementation:
Definition at line 406 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
 }
reset_data() [16/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15) inline
Reset 16 data points.
Implementation:
Definition at line 436 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
 }
reset_data() [17/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16) inline
Reset 17 data points.
Implementation:
Definition at line 467 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
 }
reset_data() [18/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17) inline
Reset 18 data points.
Implementation:
Definition at line 499 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
 }
reset_data() [19/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18) inline
Reset 19 data points.
Implementation:
Definition at line 532 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
 }
reset_data() [20/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19) inline
Reset 20 data points.
Implementation:
Definition at line 566 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
 }
reset_data() [21/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20) inline
Reset 21 data points.
Implementation:
Definition at line 601 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
 }
reset_data() [22/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21) inline
Reset 22 data points.
Implementation:
Definition at line 637 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
 }
reset_data() [23/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22) inline
Reset 23 data points.
Implementation:
Definition at line 674 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
 }
reset_data() [24/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22, T23 & t23) inline
Reset 24 data points.
Implementation:
Definition at line 712 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
   t23 = dragon::NoData<T23>::value();
 }
reset_data() [25/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22, T23 & t23, T24 & t24) inline
Reset 25 data points.
Implementation:
Definition at line 751 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
   t23 = dragon::NoData<T23>::value();
   t24 = dragon::NoData<T24>::value();
 }
reset_data() [26/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22, T23 & t23, T24 & t24, T25 & t25) inline
Reset 26 data points.
Implementation:
Definition at line 791 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
   t23 = dragon::NoData<T23>::value();
   t24 = dragon::NoData<T24>::value();
   t25 = dragon::NoData<T25>::value();
 }
reset_data() [27/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22, T23 & t23, T24 & t24, T25 & t25, T26 & t26) inline
Reset 27 data points.
Implementation:
Definition at line 832 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
   t23 = dragon::NoData<T23>::value();
   t24 = dragon::NoData<T24>::value();
   t25 = dragon::NoData<T25>::value();
   t26 = dragon::NoData<T26>::value();
 }
reset_data() [28/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22, T23 & t23, T24 & t24, T25 & t25, T26 & t26, T27 & t27) inline
Reset 28 data points.
Implementation:
Definition at line 874 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
   t23 = dragon::NoData<T23>::value();
   t24 = dragon::NoData<T24>::value();
   t25 = dragon::NoData<T25>::value();
   t26 = dragon::NoData<T26>::value();
   t27 = dragon::NoData<T27>::value();
 }
reset_data() [29/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22, T23 & t23, T24 & t24, T25 & t25, T26 & t26, T27 & t27, T28 & t28) inline
Reset 29 data points.
Implementation:
Definition at line 917 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
   t23 = dragon::NoData<T23>::value();
   t24 = dragon::NoData<T24>::value();
   t25 = dragon::NoData<T25>::value();
   t26 = dragon::NoData<T26>::value();
   t27 = dragon::NoData<T27>::value();
   t28 = dragon::NoData<T28>::value();
 }
reset_data() [30/30]
template<class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 , class T19 , class T20 , class T21 , class T22 , class T23 , class T24 , class T25 , class T26 , class T27 , class T28 , class T29 > void dragon::utils::reset_data (T0 & t0, T1 & t1, T2 & t2, T3 & t3, T4 & t4, T5 & t5, T6 & t6, T7 & t7, T8 & t8, T9 & t9, T10 & t10, T11 & t11, T12 & t12, T13 & t13, T14 & t14, T15 & t15, T16 & t16, T17 & t17, T18 & t18, T19 & t19, T20 & t20, T21 & t21, T22 & t22, T23 & t23, T24 & t24, T25 & t25, T26 & t26, T27 & t27, T28 & t28, T29 & t29) inline
Reset 30 data points.
Implementation:
Definition at line 961 of file Valid.hxx.
References dragon::NoData< T >::value().
 {
   /// Implementation:
   t0 = dragon::NoData<T0>::value();
   t1 = dragon::NoData<T1>::value();
   t2 = dragon::NoData<T2>::value();
   t3 = dragon::NoData<T3>::value();
   t4 = dragon::NoData<T4>::value();
   t5 = dragon::NoData<T5>::value();
   t6 = dragon::NoData<T6>::value();
   t7 = dragon::NoData<T7>::value();
   t8 = dragon::NoData<T8>::value();
   t9 = dragon::NoData<T9>::value();
   t10 = dragon::NoData<T10>::value();
   t11 = dragon::NoData<T11>::value();
   t12 = dragon::NoData<T12>::value();
   t13 = dragon::NoData<T13>::value();
   t14 = dragon::NoData<T14>::value();
   t15 = dragon::NoData<T15>::value();
   t16 = dragon::NoData<T16>::value();
   t17 = dragon::NoData<T17>::value();
   t18 = dragon::NoData<T18>::value();
   t19 = dragon::NoData<T19>::value();
   t20 = dragon::NoData<T20>::value();
   t21 = dragon::NoData<T21>::value();
   t22 = dragon::NoData<T22>::value();
   t23 = dragon::NoData<T23>::value();
   t24 = dragon::NoData<T24>::value();
   t25 = dragon::NoData<T25>::value();
   t26 = dragon::NoData<T26>::value();
   t27 = dragon::NoData<T27>::value();
   t28 = dragon::NoData<T28>::value();
   t29 = dragon::NoData<T29>::value();
 }
set_bank_name()
void dragon::utils::set_bank_name (const midas::Bank_t from, midas::Bank_t to) inline
Sets a MIDAS bank name.
Parameters
[in] from Array of 4 chars containing the desired bank name.
[out] to Array of 4 chars to populate with the desired bank name.
Note
The MIDAS banks are arrays of 4 char only, not a "length 4 string", which would also include a 5th NULL char.
Attention
It is the user's responsibility to ensire that the arrays are properly allocated.
Definition at line 26 of file Functions.hxx.
Referenced by dragon::Head::Variables::reset(), dragon::Tail::Variables::reset(), dragon::Scaler::Variables::reset(), and dragon::Epics::Variables::reset().
 {
   /*!
    * \param [in] from Array of 4 `char`s containing the desired bank name.
    * \param [out] to Array of 4 `char`s to populate with the desired bank name.
    * \note The MIDAS banks are arrays of 4 `char` _only_, not a "length 4 string",
    *  which would also include a 5th NULL `char`.
    * \attention It is the user's responsibility to ensire that the arrays are properly
    *  allocated.
    */
   std::copy (from, from + 4, to);
   to[4] = '\0';
 }
transform() [1/2]
template<class T , class TR > void dragon::utils::transform (T * output, int numch, TR transform) inline
Transforms data within an array.
Template Parameters
T Basic type of the output array
TR Type of the transformation, should either be a function returning void and taking as arguments a double& (the value to transform) and an int (the channel number) or a class overloading operator() to do the same.
Parameters
[out] output Array containing the values to transform
[in] numch Number of channels in the output array
[in] transform Instance of the transformation class (or function)
Example:
class LinearCalibrate {
  int slope, offset;
public:
  LinearCalibrate(int slope_, int offset_):
    slope(slope_), offset(offset_) { }
  void operator() (double value, int channel)
    { value = value * slope_ + offset_; }
};
vme::V792 adc;
adc.unpack(someEvent, "ADC0"); // adc.data = { 21, 24, 26, ... }
int channels = { 2, 0, 1, ... };
double output[32] = { 26., 21., 24. };
transform(output, 32, LinearCalibrate(2., 1.)); // output = { 53., 43., 49, ... }
Definition at line 369 of file Functions.hxx.
Referenced by transform().
 {
   for (int i=0; i< numch; ++i) {
     transform(output[i], i);
   }
 }
transform() [2/2]
template<class T , class TR > void dragon::utils::transform (T & output, TR transform) inline
Transforms a single value.
Same as the array transform(), except operating only on a single value (passed by reference);
Definition at line 378 of file Functions.hxx.
References transform().
 {
   /*!
    * Same as the array transform(), except operating only on a single value
    * (passed by reference);
    */
   transform(output, 0);
 }
zero_suppress() [1/2]
template<class T , class T2 > void dragon::utils::zero_suppress (T & value, const T2 & threshold) inline
Perform zero suppression on a single value.
Parameters
[out] value Value to zero-suppress
[in] threshold Zero suppression threshold
 if(value < threshold) value = 0;
Template Parameters
T type of the value to zero-suppress
T2 Type of the threshold value
Definition at line 480 of file Functions.hxx.
References is_valid().
 {
   if(is_valid(value) == false) return;
   if(value < threshold) value = 0;
 }
zero_suppress() [2/2]
template<class T , class T2 , class L > void dragon::utils::zero_suppress (T * values, L length, const T2 * thresholds) inline
Perform zero suppression on an array.
Parameters
[out] values Array of values to zero-suppress
[in] thresholds Array of zero suppression thresholds
[in] length Length of both arrrays
 for(L i=0; i< length; ++i) {
   if(values[i] < thresholds[i])
     values[i] = 0;
 }
Template Parameters
T type of the value to zero-suppress
T2 Type of the threshold value
L Type of the length parameter
Definition at line 502 of file Functions.hxx.
References is_valid().
 {
   for(L i=0; i< length; ++i) {
     if(is_valid(values[i]) == false) continue;
     if(values[i] < thresholds[i]) values[i] = 0;
   }
 }
zero_suppress1()
template<class T , class T2 , class L > void dragon::utils::zero_suppress1 (T * values, L length, const T2 & threshold) inline
Perform zero suppression on an array with a single suppression value.
Parameters
[out] values Array of values to zero-suppress
[in] thresholds Zero suppression threshold for the whole array
[in] length Length of values
 for(L i=0; i< length; ++i) {
   if(values[i] < threshold)
     values[i] = 0;
 }
Template Parameters
T type of the value to zero-suppress
T2 Type of the threshold value
L Type of the length parameter
Definition at line 526 of file Functions.hxx.
References is_valid().
Referenced by dragon::Bgo::calculate().
 {
   for(L i=0; i< length; ++i) {
     if(is_valid(values[i]) == false) continue;
     if(values[i] < threshold) values[i] = 0;
   }
 }