DRAGON Analyzer: dragon::NoData< T > Struct Template Reference
dragon::NoData< T > Struct Template Reference
Determines "throwaway" data value when some parameter is absent.
#include <Valid.hxx>
Static Public Member Functions
static const T value ()
Get the throwaway value.
Detailed Description
template<class T>
struct dragon::NoData< T >
Determines "throwaway" data value when some parameter is absent.
Definition at line 44 of file Valid.hxx.
Member Function Documentation
value()
template<class T > static const T dragon::NoData< T >::value () inline static
Get the throwaway value.
Returns
-1 if a signed type, maximim value if an unsigned type
Definition at line 46 of file Valid.hxx.
Referenced by dragon::utils::calculate_tof(), vme::V1190::get_data(), vme::V792::get_data(), and dragon::utils::reset_data().
     {
       /// \returns -1 if a signed type, maximim value if an unsigned type
       return no_data_impl::Impl<T, std::numeric_limits<T>::is_signed>::value();
     }
The documentation for this struct was generated from the following file:
/Volumes/Data/Users/elzoido238/packages/dragon/analyzer/src/utils/Valid.hxx